### ISSUE TITLE
Advanced Search feature

### ISSUE THREAD

**Issue by wfoster** [osTicket/osTicket-1.8#1140]
Hi Guys

Would like you to explain how this feature works because my users on the ticket system get the funniest results out from the system when using the advanced search. They for example will do an advanced search for closed ticket in a date frame of last week and get tickets from the beginning of the year in there and have nothing showing in the search for last week?
Just curious that we might be using the advanced search incorrectly or is it actually still a WIP?
We would like to use this feature to fill out time sheets but cannot do it at the moment with the incorrect data it is resolving

Thanks

**Comment by harrisyn** [comment]
for the current version, I piped the ticket responses into a file and read from it.
it works for me since then
