### ISSUE TITLE
Images not displaying in httpS since 1.9.3

### ISSUE THREAD

**Issue by aurelienGITHUB** [osTicket/osTicket-1.8#1192]
Since 1.9.3 images are not displaying in HTTPS with valid certificate.  Working in HTTP

Image database storage used.

This happen on IIS in Win 2012 R2 but an other  user (https://github.com/steadhouse) reported the same problem on Apache/2.2.22 (Ubuntu) 

![https](https://cloud.githubusercontent.com/assets/7781809/4066722/c37bad92-2e26-11e4-8989-6966507c0c05.jpg)

The missing images are on logo page, knowledgebase, in ticket. Logo image on page https://helpdesk.wanopc.org/scp/settings.php?t=pages are correctly displaying.

**Comment by greezybacon** [comment]
@aurelienGITHUB any change on the issue? We implemented a new file serving script since 1.9.5

**Comment by aurelienGITHUB** [comment]
Problem is solved form me in 1.9.6 !

Many tks !!!
