### ISSUE TITLE
Allow Custom Form Fields to be used in Ticket Filter Rules Matching Criteria

### ISSUE THREAD

**Issue by MALfunction84** [osTicket/osTicket-1.8#1193]
Not sure if this is a bug or just an enhancement request.

1. Manage > Forms > Add New Custom Form
1. Create a form with a single field.
1. Manage > Ticket Filters > Add New Filter
1. Under Filter Rules, click the left dropdown.

The field for the custom form is not available as a selection.  It does not appear to be possible to filter tickets using custom fields.

If addressed, the Properties of List Items should also be available for filtering.

**Comment by greezybacon** [comment]
This is in the product as of the current version. Thanks for the feature request
