### ISSUE TITLE
osTicket (v1.9.4-rc2) - Missing subject - Subject = 0

### ISSUE THREAD

**Issue by skubla** [osTicket/osTicket-1.8#1286]
After upgrade osTicket Core, v1.9.3 to osTicket Core, v1.9.4-rc1 od rc2 "missing subject" Subject = 0

![image](https://cloud.githubusercontent.com/assets/8791966/4286632/bd04ab5a-3d97-11e4-8889-515876d9a530.png)

![image](https://cloud.githubusercontent.com/assets/8791966/4286659/11adf3be-3d98-11e4-85db-9a3b187f73d6.png)

**Comment by greezybacon** [comment]
@skubla how did you fix the issue?

**Comment by skubla** [comment]
Upgrade osTicket to a higher version 1.9.4 and later.
