### ISSUE TITLE
V. 1.9.x Some content - e.g. the copyright text from the footer and the ticket activity graph - gets sometimes only rendered by a page refresh

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#1353]
I have noticed an issue that occurs in every 1.9.x Version:

Some parts for example the footer with the copyright text only gets rendered when you refresh the page or some special conditions (after the login or when you switch from admin panel to staff panel or vice versa).

When I login in the scp I can see the copyright text only the first time.

But when I navigate to another section, for example to "tickets" or "user" the copyright text is missing

When I make a page refresh the missing text is rendered.

The graph in the dashboard seems to have the same problem.

Version 1.8.x doesn't have this issue.

I'm using Apache 2.4.9 PHP 5.5.11 MySQL 5.6.16.

This is the missing copyright text:

![copyright](https://cloud.githubusercontent.com/assets/5539456/4491906/eefeb400-4a3c-11e4-8dd8-750e90f6e656.JPG)

**Comment by greezybacon** [comment]
Can someone verify if the patch in #1856 addresses the blank graph on navigation issue?

**Comment by mfelber** [comment]
The patch in #1856 works fine, so I close this issue :-)
