### ISSUE TITLE
Probelm with cyrillic words in ticket export

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1526]
Ticket export generate csv file with UTF-8 w/o BOM encoding but MS Excel not understand this encoding. If open exported csv you get text in MS Excel like  Р‘СѓР»Р°РЅРѕРІ РњР°РєСЃРёРј" with cyrillic words. If change file encoding to UTF-8 the MS Excel show cyrillic words as expected. 

Need change ticket export file encoding to UTF-8.

**Comment by greezybacon** [comment]
@infectormp could you test with the patch in #1869?

**Comment by infectormp** [comment]
tested, work fine now.
