### ISSUE TITLE
Collaborators answers shown as Ticketcreator

### ISSUE THREAD

**Issue by Hannibal226** [osTicket/osTicket-1.8#1618]
Hello guys,

I hope this isn't a dublicate ticket, but we've recognized, that if a collaborator
answers to a ticket, it will not shown his name/adress.
It's like always the ticketcreator is posting to ticket.

Maybe it's possible to check if user exists (if from email fetch) or at least showing adress..

CHEERS ;)

**Comment by Hannibal226** [comment]
@greezybacon I'm not sure about how to make Screenshots from this problem.

I try to make it with the good old X and Y example :P

A ticket is opened by person X and he's adding a collaborator Y (via Cc in Email or directly in ticketsystem). 
Now when collaborator Y is writing/answering to the ticket, the staff will see that, but posted by person X not by the collaborator.

I know there r a lot of problems and some Screenshots making things easier, but like I said it's quite senseless and difficult to show this issue with images xD

Thanks for looking at this anyway.

CHEERS ;)

**Comment by greezybacon** [comment]
> I know there r a lot of problems and some Screenshots making things easier, but like I said it's quite senseless and difficult to show this issue with images xD

I'm sure you noticed this issue by looking a the system. So seeing what you're seeing would help me understand the context of the problem. If you noticed the problem by studying the source code, which you apparently expect me to do, then you should cite where in the code you noticed the problem.

**Comment by Hannibal226** [comment]
Hmm ok. I'll try to do some screenshots. I don't know how but I'll try.

**Comment by ntozier** [comment]
Windows7 comes with something called "snipping tool" which is great for taking partial or total screen grabs.

**Comment by Hannibal226** [comment]
@ntozier 
Thanks Mr. "jokeman" :P 
I mean u can't take a screenshow from who is writing and who is showing in post and so on.

CHEERS

**Comment by ntozier** [comment]
You can it you log in as someone else. :)

**Comment by Hannibal226** [comment]
Even I didn't test know completly with collaborators it seems to be related to the same thing from this issue #1861

As I'm a bit to lazy to make screenshots and it seems to be understandable without (see other ticket), I will now close this one. Maybe it's fixed and if now it's not so important for myself.

**Comment by Hannibal226** [comment]
PLS Close, I can't
