### ISSUE TITLE
develeop -next - error: db-Error - delete ticket with attachment

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#1650]
DB Error #1064

[DELETE FROM ost_attachment a INNER JOIN ost_thread_entry e ON(e.id = a.object_id AND a.`type`= "H") WHERE e.thread_id=2] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'a INNER JOIN ost_thread_entry e ON(e.id = a.object_id AND a.' at line 1

---- Backtrace ----
#0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1064', '[DELETE FROM os...')
#1 (root)/include/class.thread.php(168): db_query('DELETE FROM ost...')
#2 (root)/include/class.thread.php(192): Thread->deleteAttachments()
#3 (root)/include/class.ticket.php(2262): Thread->delete()
#4 (root)/include/class.ticket.php(1039): Ticket->delete('')
#5 (root)/include/ajax.tickets.php(729): Ticket->setStatus(Object(TicketStatus), '', Array)
#6 [internal function]: TicketsAjaxAPI->setSelectedTicketsStatus('deleted')
#7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
#8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('status/deleted', Array)
#9 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('status/deleted', Array)
#10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tickets/status...', NULL)
#11 (root)/scp/ajax.php(214): Dispatcher->resolve('/tickets/status...')
#12 {main}

**Comment by greezybacon** [comment]
This is quite puzzling. It seems to imply that `a` is a reserved word in your MySQL instance. What version are you running?

**Comment by gmt-it** [comment]
MySQL 5.5.40

**Comment by yakatz** [comment]
The simple solution is to escape table names (good practice anyway) with backticks. Then it does not matter whether it is a reserved word. Not sure how much work that would be to implement.

**Comment by gmt-it** [comment]
Thanks! Escaping works. We changed it to:
<pre>
 $sql = 'DELETE a.* FROM '.ATTACHMENT_TABLE. ' a '
		    . 'INNER JOIN '.THREAD_ENTRY_TABLE.' e
                    ON (e.id = a.object_id AND a.`type`= "H") '
		    . ' WHERE e.thread_id='.db_input($this->getId());
</pre>

**Comment by greezybacon** [comment]
@gmt-it thanks for the working post. @yakatz I think the `DELETE a.* FROM` is the ticket

**Comment by yakatz** [comment]
@greezybacon I was going based on the backtrace. I don't know where else there is attachment-related code.

**Comment by gmt-it** [comment]
Works now.
