### ISSUE TITLE
[1.9.5] Bug: Version = 1.8-git(?)

### ISSUE THREAD

**Issue by Hannibal226** [osTicket/osTicket-1.8#1658]
I think this was just forgotten, but anyway as a quick info ;)

![2015-01-07 13_04_10-osticket __ admin control panel](https://cloud.githubusercontent.com/assets/8488784/5645274/ca459fa2-966d-11e4-9385-3f83cd8296c6.png)

**Comment by greezybacon** [comment]
This is a nuance from running off a git repo, which isn't recommended for production. If you download a packaged zip file from osticket.com, package it yourself with the `setup/cli/package.php` script or use the `setup/cli/manage.php deploy` script, the version will be set correctly.

**Comment by Hannibal226** [comment]
@greezybacon 
Sorry I'm not sure what u mean exactly. So I used the source.zip from the 1.9.5 announcment here on GitHub.
All working fine just the version number isn't correct. But I deleted the Setup folder and what u mean with the .php's u mentioned? I', not sure what to do with them or I have to start he setup again?

CHEERS

**Comment by greezybacon** [comment]
Yup. I wish I could turn that feature of GitHub off, but I can't. Downloading the zip file from GitHub is the same a running from a git repo.

**Comment by Hannibal226** [comment]
Ah understand now. Thanks for fast reply ;)

**Comment by Hannibal226** [comment]
@greezybacon 
Sorry but u said "isn't reaccomended for production".
Is it ok to run it now as it is here and just wait for official release or anything which should/couldn't work now or is bad for company use?
For now I can't see any big difference except a few files more in folder...

CHEERS

**Comment by mckaygerhard** [comment]
ping? so then was the difference between the releases here and the ones in the web page.. i could fount any diff inside files more rhater that some more directories and few lines ...

**Comment by Hannibal226** [comment]
can get closed again...

**Comment by greezybacon** [comment]
You guys, this is a development site. The code is organized and configured for development use. The packaging system in `setup/cli/package.php` removes the error_reporting flags, sets the version code, and rewrites javascript and css includes to include the current commit hash, which is useful for browser cache invalidation when upgrading versions.
