### ISSUE TITLE
develeop-next - Schema Signature

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#1659]
Seems you have to update the signature:

core: Unknown or invalid schema signature (5cd0a25a54fd27ed95f00d62edda4c6d .. 3020a42a3a5c74b287085d3ddfcc5450)

**Comment by greezybacon** [comment]
Is this fixed now? Peter set me straight

**Comment by gmt-it** [comment]
No. No chance to make a clean install. Error is the same.

**Comment by LucasBurg** [comment]
I is also with this error

**Comment by Renatfg** [comment]
Have same error. I cloned directly from the repo to windows. 

Then i replace file "setup/inc/streams/core/install-mysql.sql" from zip file, and its worked.

**Comment by greezybacon** [comment]
I've performed several installs of `develop-next` recently. I'm confident it installs clean. Please continue this discussion in #1989 if it persists
