### ISSUE TITLE
Update to 1.9.5 makes old attachments invalid

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket-1.8#1668]
Hi, I recently updated to 1.9.5 (from 1.9.4). All attachments from tickets which were created before the update are not accessible. I get links like http://support.one-bath.de/file.php?key=e679fab958e04b3fcf7ac39f1142daae&expires=1421193600&signature=426ed2bd7845bf2a681b18333153d56ac44618a0 with the error message: "Unbekannte oder ungültige Datei" (unknown or invalid file).

I did not use any plugin to store the attachments on the disk.
I think the update in how the attachments are linked broke it? New tickets work like expected.

**Comment by t-oster** [comment]
An entry in the file table exists with that key, but the signature is NULL. I am checking, where exactly it breaks.

**Comment by ntozier** [comment]
Wasn't this fixed in 1.9.5.1?
https://github.com/osTicket/osTicket-1.8/releases/tag/v1.9.5.1

**Comment by t-oster** [comment]
sorry, did not see the new release. I will test tomorrow and probably close this issue.

**Comment by ntozier** [comment]
No worries!  Please let us know if you how you make out on this.

**Comment by greezybacon** [comment]
This was definitely addressed in v1.9.5.1. @t-oster please confirm when you are able

**Comment by t-oster** [comment]
Yes, I can confirm that it works now. Thank you.
