### ISSUE TITLE
Custom Forms, Form Fields

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket-1.8#1669]
Hi
I made a new "Form Fields" it show up in the front end as expected. When entering the ticket data and for my new field too, I submit the ticket.

How and where can I now see the new "Form Fields"? I dont understand the meaning with it? I have hoped it will show up in the backend where the "supporter" handled all the ticket?

I dont understand "Form Fields"?

**Comment by ntozier** [comment]
This seems like more of a question for the forums.
http://www.osticket.com/forum
You also have not provided us with enough information to actually assist you.  What built in form did you add the fields to? Or did you make a custom form and add it to a Help Topic?

**Comment by gitfve** [comment]
Just made the "Field" on the standard Form my customer see when making a ticket. Maybe I dont understand this at all? I have looked at wiki and google and the forum, but I still dont understand it.

**Comment by greezybacon** [comment]
@gitfve perhaps you could submit a screenshot? I can't figure out what you're trying to ask. I could try and explain the custom forms and fields feature, but it's pretty extensive. So I want to try and answer your question, whatever it is, specifically.

**Comment by gitfve** [comment]
Hi

osTicket 1.9.5 Release from osTicket.

1)​
P1 is where I yesterday have made a new "Field" named >SerialNumber<​​ it was a short text and user must enter there serial number on our product. (I have removed is again)
![p1](https://cloud.githubusercontent.com/assets/6228825/5725924/8214a4fa-9b57-11e4-98dc-8fb84387f0ee.png)

P2 Is where the "Field" show up, and it is working.
I entered all information including the new serial number. Then I submit the new ticket. (I have removed it again)
![p2](https://cloud.githubusercontent.com/assets/6228825/5725928/8e3cd8c4-9b57-11e4-9083-4918d8b479ec.png)

2)
P3 I expect my "Field" show up in the back-end, between all the other label information.
It was here I was wrong, because nothing show up? And that confusing me...
![p3](https://cloud.githubusercontent.com/assets/6228825/5725932/9637acb6-9b57-11e4-822c-b2d18e4bca36.png)

Thanks.​​​​

**Comment by ntozier** [comment]
You clearly added the field to Contact Information form.
You should have added it to the Ticket Details form if you want it to show up under ticket details.

**Comment by gitfve** [comment]
After doing it on your way, all is working, thanks. I'm embarrassed.

**Comment by shubh-adept** [comment]
@gitfve PLEASE also help me in integrating OSTICKET in my website I have files and database also.
