### ISSUE TITLE
Wrong email priority/ bug in parsePriority

### ISSUE THREAD

**Issue by gniusj** [osTicket/osTicket-1.8#1674]
Hello

I think there is a mistake in parsePriority since a version of 1.8.x
Since then all mails with high priority that are imported via IMAP will get low priority in osTicket an vice versa.

I think there are two mistakes in the switch statement of parsePriority function in class.mailparse.php:

```php
switch ($matching_char[1]) {
    			case 'h' :
    			case 'H' :// high
    			case 'u':
    			case 'U': //Urgent
    			case 6 :
    			case 5 :
    				return 1;
    			case 'n' : // normal
    			case 'N' :
    			case 4 :
    			case 3 :
    				return 2;
    			case 'l' : // low
    			case 'L' :
    			case 2 :
    			case 1 :
    				return 3;
    		}
    	}
    	return 0;
    }
```
From my understanding the cases 1 and 2 have to be switched with 5 and 6. 
Mail priority 1 and 2 are high priorties, 5 and 6 are low.
In the ticket_priority table is 1 for low and 3 for high. Therefore the return values also have to be switched.

If I change these values (the four cases and the two return values) it works as expected.

**Comment by gniusj** [comment]
Sorry, I made a mistake, I'm catching via POP instead of IMAP, but I think this would make no difference...

**Comment by greezybacon** [comment]
@gniusj is there any sort of standard (rfc) you could reference for the priority numbers? What mail client / header are you expecting the priority to be parsed from?

**Comment by gniusj** [comment]
@greezybacon Didn't found anything like that but you can find some references on different web pages. Some examples:
http://www.chilkatsoft.com/p/p_471.asp
http://stackoverflow.com/questions/15568583/php-mail-priority-types
http://blog.alex.org.uk/2013/06/10/rant-why-your-email-is-not-high-priority-after-all/

I've tested with different mail clients like Tobit David (a german mail server and client), Outlook 2013, Windows Phone 8.1 and outlook.com.

The parsePriority function was rewritten in 1.8.x (old one can be found in the latest 1.7.x release). Before that it was working like I expected it.

As it seems that the values don't follow a standard and every mail client dev could make his own decision perhaps an admin configuration option would be ideal...?

**Comment by greezybacon** [comment]
@gniusj, yeah, I agree, it looks backwards in osTicket.

**Comment by greezybacon** [comment]
@gniusj could you test again with the patch in #1870

**Comment by gniusj** [comment]
@greezybacon Last friday I've downloaded the zip file and replaced the mailfetch and mailparse files. Since then the import doesn't work anymore. So I rolled back to the old files (my fixed ones) today and the import works again.

I'm using the translated 1.9.5.1 version from http://www.osticket.com.de/downloads.php.
Perhaps it has something to do with that?

**Comment by Chefkeks** [comment]
@gniusj 
The translated version from osticket.com.DE is NOT an OFFICIAL version and you should not use it!

The official homepage is http://www.osticket.com -> get osTicket and the official language packs from their (osticket.com/download) and not from anywhere else!

From my point, I think the page osticket.com.DE tricks users on purpose and make them think it's related to the official osTicket. Just look at the almost similar addresses... they just added .DE at the end - but trust me it is definitely not related to the official osTicket!

What they basically did is the following:
They took the source code, modified it and translated all the phrases to German and then sell it as some kind of "German osTicket version" without clearly saying / mentioning that it's not the official osTicket nor the official osTicket translation - really shameless acting in my personal opinion.

As a side note I'm a forum moderator at the official forum (osticket.com/forum) and a proofreader/translator for the official German language pack, so I am 100% sure about that! ;)

Michael

PS: If possible, please get rid of the osticket.com.DE version and switch to the official osTicket.

**Comment by gniusj** [comment]
@Chefkeks I had the official version running in the first days of use but our customers had problems with the language. At this time there had been no official german version / translation.
On their website are hints that it isn't an official version so I had always known it. 

The last time I tested the official version (I think it was in december?) the translation wasn't completed, especially in the customer section, so it wasn't an alternative...

I wouldn't use a "third party" version if the official version would fill all my rep. our customers needs.

Greets
Jens

**Comment by gniusj** [comment]
@greezybacon I switched to the official 1.9.6 for testing. Same problem here, no import with the two files applied, import works (but the wrong way) with the original 1.9.6 files.

**Comment by Chefkeks** [comment]
@gniusj 
If I remember correctly, the German translation was finished in August 2014, so when you mention that it was not complete, I guess it's due to the fact that the multi-language feature itself is currently not yet finished (it's in phase 3 of 4) and so some content (e.g. the German email templates) is only available on a new/fresh installation (with German as the default / primary language) or still missing since custom content (e.g. help topic names) is not yet translate-able, but the option to translate such content will come to osTicket once the multi-language feature is fully implemented.

And yes there are some hints, but they are not really obvious in my opinion and as someone who does not know osTicket really well or just discovered it, you could think that there is some kind of relation between osticket.com.DE and the official osTicket, which is definitely not the case.

**Comment by gniusj** [comment]
@greezybacon Sorry, my last answer was wrong. It just took a while until the ticket was there although I had manually triggered the import and the mail was deleted in my inbox.

High and normal mails are correct now, but the ones with low prio are imported as "normal".

The header of my testmail has the following flags:

Importance: low
X-Priority: 5

Greets
Jens

**Comment by ntozier** [comment]
"although I had manually triggered the import and the mail was deleted in my inbox."
Did you setup cron?
How did you configure the email?

What do you have at:
Admin panel -> Settings -> Tickets -> Default Priority:?

I bet its Normal.

What do you have at:
Admin panel -> Settings -> Emails -> Emailed Tickets Priority:?

I bet its not enabled.

Do you set priorities using Ticket Filters?
Admin panel -> Manage -> Ticket Filters
Do you set priorities using Help Topics?
Admin panel -> Manage -> Help Topics

**Comment by gniusj** [comment]
@ntozier Thank you for your answer but I think you misunderstood something. I am using the email ticket import for a long time now and it is all working. But there is a bug regarding the email priority in the import process. @greezybacon has already applied a patch which is working for high and normal priority mails but not for ones with low priority set in the email header.

**Comment by greezybacon** [comment]
@gniusj what are your `priority_urgency` values from your database?

**Comment by gniusj** [comment]
@greezybacon 
id - priority - priority_urgency
1 - low - 4
2 - normal - 3
3 - high - 2
4 - emergency - 1

I think these are the default values. Before I initiated this ticket here I made a new test installation and compared these values.

**Comment by greezybacon** [comment]
@gniusj I think I'm going to punt (give up) for the time being. I have no idea why the code would return incorrect results for low priority.
