### ISSUE TITLE
"Alert User" in New Ticket is ignored, when department's auto-reply is disabled.

### ISSUE THREAD

**Issue by t-oster** [osTicket/osTicket-1.8#1681]
I have a department, where I disabled the "auto-reply" for new tickets in the department's settings, because I do not want people, who send an e-mail to that address to get an auto-reply every time.

However if I create a new ticket and select "notify-user" in the form, I explicitely want them to get this e-mail. But if auto-reply is disabled, no e-mail is sent to the user.

It worked before the update to 1.9.5 or 1.9.5.1.

Was this change intended?

**Comment by greezybacon** [comment]
I believe this was a regression of v1.9.5 and was fixed in either 1.9.5.1 or 1.9.6. Can you verify if it is still a problem?

**Comment by t-oster** [comment]
I cannot check this atm, but since no one else complaints, I think it is fixed.
