### ISSUE TITLE
Autostore every 10 seconds while editting text

### ISSUE THREAD

**Issue by send2nirwana** [osTicket/osTicket-1.8#1682]
Is there any option to change or disabling the autostore-time while editting text of tickets?

**Comment by ntozier** [comment]
Sorry I don't follow your question.  You cannot edit the text of tickets.

Do you mean while composing a new response?
and what version are you running?

**Comment by protich** [comment]
@ntozier --  I think the user is asking if there is a place to change the frequency of draft auto-save. The answer is no, it's hardcoded at the moment.

**Comment by send2nirwana** [comment]
Yes, while composing a new response. Thanks for your answer, Protich.
