### ISSUE TITLE
1.9.5.1 - Admin -> Settings -> Tickets -> 'Exclude assigned tickets from open queue' option does not work

### ISSUE THREAD

**Issue by TraceElements** [osTicket/osTicket-1.8#1690]
Using v1.9.5.1 , in Admin Panel -> Settings -> Tickets menu there is an option called 'Exclude assigned tickets from open queue'.

When I check this box, tickets that are assigned to both individuals and teams still appear in the open queue. My understanding is that only tickets with a blank 'Assigned To' field should appear.

While #901 covers a bit about advanced search not working, and #1573 specifically talks about advanced search for 'unassigned' tickets not working, this report is specifically about the option in the Admin menu to filter on unassigned tickets in the open queue.

**Comment by TraceElements** [comment]
I found what caused the behaviour - there's a setting in the individual user preferences called 'Show Assigned Tickets' which defaults to checked and overrides the 'Exclude assigned tickets from open queue' setting in the Admin panel menu.

Since the user setting defaults to checked, the setting in the admin panel does nothing unless users uncheck 'show assigned tickets'.

The reason for this behaviour is line 113-116 of include/staff/tickets.inc.php which reads:

    if(!($cfg->showAssignedTickets() || $thisstaff->showAssignedTickets())) {
        $qwhere.=' AND ticket.staff_id=0 '; //XXX: NOT factoring in team assignments - only staff assignments.

I was thinking of closing this issue but found that the info bubble for the user option is quite incorrect.  It reads :  "Enable this to hide your name from the Open Tickets queue for those tickets which you have been assigned. Upon hiding, the Department name to which you belong will replace where your name would normally be displayed."

A more accurate description would be something like :  "Enable to show tickets assigned to other people in the Open Tickets queue.  Disable to show only tickets that do not have a staffmember assigned.".

It might also be good to add something to the info bubble on the admin menu option that users can override this.

**Comment by TraceElements** [comment]
Closing this - you folks are busy enough as it is :)

**Comment by greezybacon** [comment]
@protich should the preference setting match the *exclude* nature of the global setting?
