### ISSUE TITLE
error: (grave) reports are not updated when topics helps was changed/modifed/deleted

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket-1.8#1699]
i made 3 tickets with the folowing topic helps( 1 for infor of an error, 2 of report a problem)

so when user ganets goes to the dashboard, show in topic tab of reports :

1 opened for  "infor of an error" and 2 for report a problem.

then now goes to create two new topics, "erro1" and "problem1"

then now goes to the 3 tickets recently created and change the 1 to "problem1" and the 2 and 3 to "erro1"

and the delete the "infor of an error" topic help.

now then goes to the dashboard again and see the reports by the topic help :

still shows the olders topic and now show more that the opened tickets
1 for infor of and error
1 for problem
3 for erro1

osticket sumarize allt he olders and new ticket under same topic, when change the name... for the report

**Comment by mckaygerhard** [comment]
and for more combinatios problems goes more more complicated, and reports will inform erroneous and more thant created tickets..

**Comment by mckaygerhard** [comment]
ping? this error are critical?

**Comment by greezybacon** [comment]
The reports show historical statistics, not real time information. This is the source of your confusion

**Comment by mckaygerhard** [comment]
i suspect .. after some analisis of the report..

ok, i'll close it now.
