### ISSUE TITLE
SMTP: Some mails are not sent

### ISSUE THREAD

**Issue by TheSMa** [osTicket/osTicket-1.8#1700]
in very rare cases, we have the problem, that outgoing SMTP messages are not sent to a recipient. I can't find the message in our outbox in GMail (we use SMTP/IMAP via Google Apps for Work). In osTicket the message is saved without any note of a problem.
i can't find any reason for the problem.

We use osTicket in version 1.9.5 (RC5).

**Comment by greezybacon** [comment]
You're not crazy. We have observed the same issue in our own osTicket help desk. I can't explain what's going on yet.

**Comment by greezybacon** [comment]
Do the ones that are not going out happen to have attachments?

**Comment by TheSMa** [comment]
No, the most affected mails have no attachments.

**Comment by greezybacon** [comment]
I think #1712 fixes this. I bet if you look, you have new ticket auto responses disabled for some departments

**Comment by TheSMa** [comment]
ok but we have auto responses disabled in a filter for some Mailsenders, not in departments. Means that the same?

**Comment by greezybacon** [comment]
Yeah, the filter applies as well. The patch reverts that functionality

**Comment by TheSMa** [comment]
ok thx
