### ISSUE TITLE
New to osticket

### ISSUE THREAD

**Issue by Mijsons** [osTicket/osTicket-1.8#1704]
Hi! I am new one kindly help me by providing any helpful link through which I install & configure osticket easily....

**Comment by praveen-l** [comment]
Hi

Osticket is very easy to install...
Give me your number I'll help you...
Www.osticket.com


On Thursday, January 29, 2015, Mijsons <notifications@github.com> wrote:

> Hi! I am new one kindly help me by providing any helpful link through
> which I install & configure osticket easily....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/1704>.
>


-- 
Sent from Gmail Mobile

**Comment by Mijsons** [comment]
Thanx for your reply. I configured the osticket correctly  but now I am facing a little bit problem regarding email. When new ticket will create, email sent to the user but I also want that email will sent to support & admin on the creation of new ticket

**Comment by praveen-l** [comment]
Hi,

Go to admin panel -> settings -> alerts and notice -> here you can set
it...



On Thursday, January 29, 2015, Mujtaba <notifications@github.com> wrote:

> Thanx for your reply. I configured the osticket correctly but now I am
> facing a little bit problem regarding email. When new ticket will create,
> email sent to the user but I also want that email will sent to support &
> admin on the creation of new ticket
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/1704#issuecomment-72004878>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Mijsons** [comment]
I already set these things but now the new ticket email alert is send only to user not to admin/support...

**Comment by praveen-l** [comment]
Check your outbox logging into your mail account and try checking spam from
your admin mail id...

On Thursday, January 29, 2015, Mujtaba <notifications@github.com> wrote:

> I already set these things but now the new ticket email alert is send only
> to user not to admin/support...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/1704#issuecomment-72005542>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Mijsons** [comment]
Nothing found in spam . Kindly check this screenshot & tell me if I did anything wrong....
![os ticket](https://cloud.githubusercontent.com/assets/10754035/5956410/73c1663e-a7cf-11e4-930c-5e309694d7f3.png)

**Comment by praveen-l** [comment]
Settings seams to be perfect...
Check your mail settings once...  If you're on whatsapp ping me
+919731800800

On Thursday, January 29, 2015, Mujtaba <notifications@github.com> wrote:

> Nothing found in spam . Kindly check this screenshot & tell me if I did
> anything wrong....
> [image: os ticket]
> <https://cloud.githubusercontent.com/assets/10754035/5956410/73c1663e-a7cf-11e4-930c-5e309694d7f3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/1704#issuecomment-72006188>
> .
>


-- 
Sent from Gmail Mobile

**Comment by protich** [comment]
This is a discussion for [osTicket forum] (http://osticket.com/forum).
