### ISSUE TITLE
Mail with embedded table is not displayed

### ISSUE THREAD

**Issue by TheSMa** [osTicket/osTicket-1.8#1715]
We receive a lot of autogenerated (HTML-) mails with an embedded table, but in osTicket the table and data is not displayed.

We use osTicket in version 1.9.5 (RC5).

<b>Here the original mail, how it looks:</b>
![osticket_emptymail2](https://cloud.githubusercontent.com/assets/6357571/6036884/8c3a35ca-ac4c-11e4-9719-28da3937ab9b.jpg)

<b>And this is what osticket do:</b>
![osticket_emptymail](https://cloud.githubusercontent.com/assets/6357571/6036873/59c655ba-ac4c-11e4-95c5-448d1978e1e3.jpg)

<b>The code of the message:</b>
![osticket_emptymail3](https://cloud.githubusercontent.com/assets/6357571/6037093/961da5ce-ac4f-11e4-8a60-c59c27cae76d.jpg)

Is there a way to fix it?

**Comment by Hamsteren** [comment]
I think it might be the same issue as i'm facing #1711

**Comment by greezybacon** [comment]
Your table is terribly incorrectly written. The only thing allowed in a <tr> is a <td> (not text), and <td> elements must be inside <tr> elements (not <table>). The HTML scrubber is dropping the tags when trying to balance the HTML elements

**Comment by TheSMa** [comment]
Thank you @greezybacon. 
I will contact our provider to fix this :-)
