### ISSUE TITLE
Customer users can't post screenshots into their tickets via web UI

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket-1.8#1716]
If a customer creates a ticket / replies to an existing ticket via E-Mail, embedded screenshots in the e-mail will be integrated into the ticket: this is fine and OKAY

If a customer creates a ticket via http://www.ostickethacks.com/demo/open.php or replies to a ticket after login to the web UI of osTicket, there is just a simple text input box. The text input box doesn't accept screenshots from clipboard: this is MISSING

AFAIK, only the web UI for internal staff (/osticket/scp/...) accepts embedding of screenshots.

**Comment by ntozier** [comment]
My understanding is that not allowing inline images on ticket open is actually the designed behavior.  It's been like that for quite some time.

**Comment by jochenwezel** [comment]
I fear it is...that's why it might be time to re-design this behaviour ;-)
Or at least: make it configurable

**Comment by GeekSage** [comment]
Interesting... We don't see that behavior.  See screenshots below:

User creating new ticket from web interface:
![image](https://cloud.githubusercontent.com/assets/3441198/6043961/2985c126-ac5e-11e4-9c20-df41f02b5ef5.png)

A user reply to a ticket from web interface:
![image](https://cloud.githubusercontent.com/assets/3441198/6043903/cbd457a4-ac5d-11e4-839c-8d82956a6df8.png)

We have ours set so that the users must login to create tickets so that might be a difference from your setup?

**Comment by jochenwezel** [comment]
@GeekSage your screenshots look like they were created from the internal web UI - not from the external customer portal of osticket (external web UI usually at /osticket/ vs. internal web UI usually at /osticket/scp/)

**Comment by ntozier** [comment]
Actually I just went and checked my installation and I have the ability to post inline images. (as guest not signed in user, as well as signed in as a user).

**Comment by GeekSage** [comment]
@jochenwezel Nope, those were from the user side... Not the scp.

**Comment by jochenwezel** [comment]
well, I use osTicket v1.9.3 and MS IE 11 as well as Google Chrome v40

The official osTicket DEMO portal at http://www.ostickethacks.com/demo/open.php hasn't got the insert-screenshot-feature. I used this to double-check if the feature is really missing in the most current osTicket version. Maybe http://www.ostickethacks.com/demo/open.php is not the latest version?

Or can you use the inser-screenshot-feature with your web browsers at http://www.ostickethacks.com/demo/open.php ?

**Comment by gmt-it** [comment]
Hello Jochen, do you activate the upload at issue-detail form?
![issue_details](https://cloud.githubusercontent.com/assets/10116166/6046065/2249e568-ac9f-11e4-86ba-904eafbda5f3.JPG)

**Comment by mfelber** [comment]
@jochenwezel Why should http://www.ostickethacks.com/demo/open.php be a official portal? When you are in the scp, you see under "system preferences" that this is version 1.7.0.

**Comment by gmt-it** [comment]
At http://www.ostickethacks.com/demo/open.php its disabled:
![issue_details](https://cloud.githubusercontent.com/assets/10116166/6046317/41d7c02e-aca1-11e4-87c9-09e5e824fda5.JPG)

**Comment by ntozier** [comment]
"official osTicket DEMO"
There is no Offical osTicket Demo.

**Comment by GeekSage** [comment]
Yea, I was thinking the same thing... How could it be official if it's not actually from the OS Ticket website?  :)

**Comment by GeekSage** [comment]
Also, @mfelber is right... It's an old version (1.7.0) of OS Ticket anyway.  Was that feature even around when that version came out?

**Comment by jochenwezel** [comment]
Sorry for the confusion - I thought the demo is official but you're right: it's not an official part

Thank you all for the hints. This is my configuration, now:
![image](https://cloud.githubusercontent.com/assets/3033827/6051294/22153084-acc7-11e4-9ed3-efa0f4718fa7.png)

Everything is fine, works with MS IE 11 and Chrome :-)

**Comment by protich** [comment]
osTickethacks is not an official osTicket site. The fact that they have ads has caused users to think osTicket comes with ads :-1:

**Comment by GeekSage** [comment]
@protich  Yea, that's pretty sleazy of them

@jochenwezel Glad you have it working now.  The majority of our users are unable to use that feature because they are being held back on an older version of IE.  We are hoping that the powers that be will finally allow the upgrade to a newer version of IE at some point soon so they can paste images into the editor.
