### ISSUE TITLE
Feature request: answer indicator

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1740]
Would it be possible to add special indicator for ticket that will indicate who is write last answer to ticket user or agent. This feature have nice implementation in Manageengine ServiceDesk Plus and it's very helpful.

Green icon - last respons from agent 
Reg icon - last respons from user
![spd](https://cloud.githubusercontent.com/assets/9958813/6236380/657a31ba-b6fb-11e4-9a61-eae3e9804d8f.png)

**Comment by greezybacon** [comment]
In osTicket, tickets shown in the list in **bold** are last answered by the client.

**Comment by infectormp** [comment]
Thank you for explanation
