### ISSUE TITLE
Out of office reply re-opens a ticket accidently

### ISSUE THREAD

**Issue by jochenwezel** [osTicket/osTicket-1.8#1744]
Out of office replies are fine to be visible to the ticket for review purposes, but it's not required to "re-open" an already closed ticket

We could also say: re-opening a closed ticket just because of the out-of-office-reply usually means
1. additional time/costs for re-closing the ticket
2. statistics on re-opened tickets in osticket systems are useless

**Comment by ntozier** [comment]
Go to:
Admin panel -> Manage -> Ticket Filters

Make a filter like this:
Filter Name: Out of Office
Execution Order: 1
Filter Status: Active
Target Channel: Emails
Ticket\Issue Summary | Starts with | Out of Office:
Reject Ticket

No more "out of office" responses in your tickets.

**Comment by jochenwezel** [comment]
The string "out of office" may differ between the many languages of the world.
Is there an alternative focussing on the e-mail header information? (AFAIK there is some hidden markup for those out-of-office-e-mails)

**Comment by infectormp** [comment]
then you need create more rules

**Comment by infectormp** [comment]
also you can use regexp in filter. out of office|out of office2|out of office3 and so on.

**Comment by MyTinCan** [comment]
This is the same solution I came to, but then had a though that I should enter "out of office:" (with the colon on the end) Otherwise, if a user is opening a ticket because their actual out of office isn't working it will reject that as well!

**Comment by jochenwezel** [comment]
I would prefer a general solution like https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/

**Comment by ntozier** [comment]
So then does that mean you answered your own question?

**Comment by jochenwezel** [comment]
maybe it is one possible answer - but how could you make that possible in osticket? Does it needs development or does it needs some special customization?

**Comment by greezybacon** [comment]
@jochenwezel what version is this? #1529 was supposed to address this issue, which was released in 1.9.5

**Comment by jochenwezel** [comment]
oh, I see, we're not up-to-date, we've got osTicket (v1.9.3)
sorry for making noise unnecessarily
I'll close this ticket for now in expectation it will work with 1.9.5 and higher

**Comment by greezybacon** [comment]
Please reopen it if its still broken in v1.9.5
