### ISSUE TITLE
Odd failure attaching file in old browser

### ISSUE THREAD

**Issue by gohanman** [osTicket/osTicket-1.8#1746]
This is rather minor, but since there is an error code for unsupported browsers:

Attaching a file to a ticket thread entry in a browser that doesn't have a "Blob" constructor function fails in a very unintuitive way. The upload process crashes with a javascript error but the file is still displayed on screen below the comment box.

When the comment actually posts, ThreadEntry::create() ends up with $vars['cannedattachments'] = array(0 => 0). Because this is an array, it calls ThreadEntry::saveAttachments. Because zero is numeric, Thread::entrySaveAttachment accepts this as a file ID and creates a record in the ticket attachment table (with file_id=0). This makes little attachment icons show up in various places even though the file was never successfully uploaded.

In brief testing, doing this in filedrop.field.js presents an appropriate error dialog. Not being familiar with the code base I'm not sure if this is the best solution though.
```javascript
    // Respond to an upload
    function upload() {
      stop_loop = false;

      if (!files) {
        opts.error(errors[0]);
        return false;
      } else if (typeof Blob != "function") {
        opts.error(errors[0]);
        return false;
      }
```

**Comment by rabiajavaid** [comment]
HI gohanman,

Did you find the solution. In firefox version 3.6 when i click 'choose them', it don't response.

**Comment by gohanman** [comment]
I'd have to double check but I think this was around Firefox 12. I think there's a stretch of versions where some Blob methods exist but *not* a constructor.

**Comment by rabiajavaid** [comment]
Check it on 3.6. Is the same issue. Canned response attachment not working. But rich text box is ok. In faq richtext box is ok. At client and user side both are not working. But test canned attachment is ok. 
Leave rich text box but attachment should work at least.

**Comment by greezybacon** [comment]
It looks like Firefox 6-12 support the blob under the name `MozBlob`. I've opened #1776 to support it and to offer the meaningful error. Can anyone confirm if the patch addresses the issue?
