### ISSUE TITLE
Advanced Search Uncaught exception Error

### ISSUE THREAD

**Issue by si458** [osTicket/osTicket-1.8#1762]
just updated to latest git pull and I keep getting the following error when I click advanced search

Fatal error: Uncaught exception 'Exception' with message 'hasSpecialSearch: Call to undefined function' in /var/www/vhosts/hestor.com/tickets.hestor.com/include/class.forms.php:454 Stack trace: #0 /var/www/vhosts/hestor.com/tickets.hestor.com/include/staff/tickets.inc.php(661): FormField->__call('hasSpecialSearc...', Array) #1 /var/www/vhosts/hestor.com/tickets.hestor.com/include/staff/tickets.inc.php(661): TextboxField->hasSpecialSearch() #2 /var/www/vhosts/hestor.com/tickets.hestor.com/scp/tickets.php(492): require_once('/var/www/vhosts...') #3 {main} thrown in /var/www/vhosts/hestor.com/tickets.hestor.com/include/class.forms.php on line 454

**Comment by ntozier** [comment]
"just updated to latest git pull"

Which branch?

**Comment by si458** [comment]
My bad sorry
Im using the osTicket-1.8 repo and using the Develop branch

**Comment by krokodylowy** [comment]
I can confirm. Fail is on ticket advanced search,

**Comment by greezybacon** [comment]
Whoops. Thanks for the report. I reverted the offending code in 3331b72
