### ISSUE TITLE
Custom Field with Checkbox

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1769]
I add custom field to form Contact Information with Russian label name
Type - Checkbox
Visibility - Optional

In User forum i set this field and now can see in Contact Information this labels = yes

when i try unset this field nothing happen i still see this labels = yes

with english label name when i unset field i see this labels = no

**Comment by ntozier** [comment]
You may want to include more information such as version of osTicket and a screen shot showing what you are talking about.  You should always include full step by step descriptions of how we can attempt to recreate the problem.

**Comment by infectormp** [comment]
you may know i use 1.9.5.1

**Comment by greezybacon** [comment]
@infectormp could you include some screenshots so I can get a clearer picture of the issue?

**Comment by infectormp** [comment]
sure, a bit later

**Comment by infectormp** [comment]
hmm.. look like problem not in label langauge. 1st time i create only one field with checkbox. Now i create 2 field called Test1 and Test2.

1 step:
1.Create 2 custom field (Checkbox) in Manage\Forms\Organization Information - Test1 and Test2 
2.Go to Users\Organizations open Organizations form:
check Test1 and Test2, press update organization, open Organizations form again.
**Result:** Test1 and Test2 checked.

2 step:
1.open Organizations form and uncheck Test1 press update organization, open Organizations form again
**Result:** Test1 unchecked and Test2 checked.

3 step:
1.open Organizations form and **uncheck** Test2 press update organization, open Organizations form again
**Result:** Test1 unchecked and Test2 still **checked**.

4 step:
1.open Organizations form check Test1 and **uncheck** Test2 press update organization, open Organizations form again
**Result:** Test1 checked and Test2 **unchecked**.

look like one checkbox must be always selected

**Comment by infectormp** [comment]
another test case:
1.create only 1 custom field (Checkbox) 
2.go to ticket check custom field, save ticket
3.open ticket again, uncheck custom field, save ticket
4.open ticket again, custom field (Checkbox) still checked.

**Comment by greezybacon** [comment]
Can anyone test the patch in #1866 to see if it addresses the issue?

**Comment by infectormp** [comment]
now work as expected, thx.
