### ISSUE TITLE
Can't save Confirmation Email template

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1774]
Confirmation Email template can't be saved if subject contain only variable %{company.name}. 

OT 1.9.5.1
![confirmation email template](https://cloud.githubusercontent.com/assets/9958813/6409359/c6ee6982-be73-11e4-8b65-393d99752db4.png)

**Comment by infectormp** [comment]
same in Agent Welcome Email

**Comment by Hamsteren** [comment]
I just tried the same on my 1.9.5.1 install and do not have that problem.
It saves the template without issues. Have you tried checking the error console in your browser to see if there are any javascript errors.
Also try checking your php/apache logfile for any errors.

**Comment by infectormp** [comment]
no errors in logs, just get Loading...
if i add some words before variable form save normaly

**Comment by infectormp** [comment]
Client Sign-In Page not affected to this problem

**Comment by infectormp** [comment]
try chrome and firefox, same result

**Comment by Hamsteren** [comment]
Tried it in Chrome, Firefox and IE11 and all 3 works without and issue here.

**Comment by greezybacon** [comment]
I think you have two notices with the same subject field. That appears to be a problem

**Comment by greezybacon** [comment]
I've added #1778, which properly displays the errors on update from the backend. Can anyone test the patch in #1778 to see if it address the issue?

**Comment by infectormp** [comment]
greezybacon, you right i alredy have notices with the same subject field and in #1778 now give correct error - Name already exists.

fixed.
