### ISSUE TITLE
Agent Login Banner can't be saved if summary field are empty

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1775]
by default Agent Login Banner have empty summary field. If we try change subject field and save we will see Loading... banner without any result.

If we write any text to summary field Agent Login Banner saved successfully

OT 1.9.5.1

**Comment by ntozier** [comment]
Not to be difficult but what is an "Agent Login Banner"?

**Comment by greezybacon** [comment]
Can anyone test the patch in #1778 to see if it address the issue?

**Comment by infectormp** [comment]
cheked. fixed by patch in #1778
