### ISSUE TITLE
JSON API: osTicket is not recognizing properly encoded Base64 attachments

### ISSUE THREAD

**Issue by borgdylan** [osTicket/osTicket-1.8#1796]
I was working on a project for a client which requires that we add image attachments thru the API. When I view the ticket after sending it by means of the JSON API (and adding a BASE64 attachment) I get "Unable to save file" where the attachment should be.

**Comment by ntozier** [comment]
Did you close this because you solved your own problem?  
If so you may want to post a reply telling any others how you over came the problem.

**Comment by borgdylan** [comment]
Yes I solved my own problem. Ir regarded the proper use of JSON encoding by means of JSON.NET. I do not think it is relevant to osTicket itself. The problem arose from teh fact that all examples gave PHP code rather than a JSON example file which would have helped me a lot since I do not use PHP at all so I did not know the syntax for PHP.

**Comment by borgdylan** [comment]
If you would like me to write a small wiki page for .NET people wishing to write JSON acceptable by the API I will do so.

**Comment by ntozier** [comment]
I think that would be fantastic!
But please do not feel like you are obligated to do so.

**Comment by borgdylan** [comment]
It would be more of a direction/guide i.e I will not give a full code sample not to reproduce work code.

**Comment by ntozier** [comment]
Sounds good to me. :)

**Comment by borgdylan** [comment]
feel free to review and change:
https://github.com/osTicket/osTicket-1.8/wiki/Consuming-the-JSON-API-end-point-using-.NET
