### ISSUE TITLE
osTicket Installation

### ISSUE THREAD

**Issue by ssi-anik** [osTicket/osTicket-1.8#1815]
I've tried to install osTicket.
1. Renamed file osticket-config.php
2. filled out the form.
3. the form is then submitted to setup/install.php 
after that, doesn't happen. if I reaload ( not resubmit) the page, then it goes back to installation page again. 
What's the error? 
Am I doing something wrong?

**Comment by ntozier** [comment]
This seems like it might be better suited to the forums.
http://www.osticket.com/forum

You have not told really provided us with much information about your setup, version of osTicket, OS, etc.  Is there an error being displayed?  Have you consulted your web server and/or PHP and/or MySQL error logs?
