### ISSUE TITLE
Bug in Help Topics - Spelling mistake

### ISSUE THREAD

**Issue by agalloway83** [osTicket/osTicket-1.8#1819]
I'm using version 1.8-git (d700d4eb) (Which should be the latest version) and there is a spelling mistake when you delete a help topic. See screen shot.

Thanks!

![osticket bug 1](https://cloud.githubusercontent.com/assets/11160728/6595993/bd890186-c7ce-11e4-8d5c-e30baa519159.jpg)

**Comment by ntozier** [comment]
The typo appears to be in /scp/helptopics.php
line 101
                                _N('selected help topic', 'selected elp topics', $count));

**Comment by greezybacon** [comment]
Fixed in referenced pull request. Thanks for the bulletin
