### ISSUE TITLE
Make filter rule based on custom form

### ISSUE THREAD

**Issue by juraganerka** [osTicket/osTicket-1.8#1822]
i just want to know how to make filter rule based on custom form.
previously i only success how show custom form in filter rule. but when i try to make filter rule from custom form is not working for me. I think the problem is from class.ticket.php file.
please help me.
i create based on this tutorial.
https://github.com/greezybacon/osTicket-1.8/commit/81ab37ca81f6ea1f3ed4822104227317720af4ac

**Comment by greezybacon** [comment]
@juraganerka can you suggest what isn't working or provide a suitable test case so I can find the bug?

**Comment by juraganerka** [comment]
@greezybacon i think the problem is in this code

 if ($vars['topicId']) {
           if (($__topic=Topic::lookup($vars['topicId']))
                && $__form = $__topic->getForm()
            ) {
                $__form = $__form->instanciate();
                $__form->setSource($vars);
                $vars += $__form->getFilterData();
            }
        }

when i try to create ticket,it's shown "setSource" is not recognized.
can you show me a full code how to make custom form enabled use in filter rule.
I use os ticket v1.8.0.2.
thanks a lot before.

**Comment by greezybacon** [comment]
The code you're citing isn't from 1.8.0.2, correct? Can't you try upgrading and see if it works in a later version?

**Comment by juraganerka** [comment]
@greezybacon the latest version osticket in filter rule is include custom form.
but i'm afraid if i upgrade my os ticket version will be damaged my ticketing system.
as you know, my ticketing system is already running for 3 months.
so can you show how to mod my filter rule

**Comment by ntozier** [comment]
Re: damaged my ticketing system.
If you upgrade and it breaks you would just have to restore from back up.
1.8.0.2 is really quite old at this point, you should probably upgrade.
This article is a little dated but should assist you.
http://www.tmib.net/upgrading-osticket-1812-current-19rc

**Comment by juraganerka** [comment]
@ntozier thx a lot. Now my ticketing system use latest version

**Comment by ntozier** [comment]
And did that fix the problem that you were experiencing? :)

**Comment by juraganerka** [comment]
@ntozier absolutely fix my problem.
thanks a lot for your advice.

**Comment by ntozier** [comment]
Very welcome. 
Can you please close this issue.
