### ISSUE TITLE
Current time not show

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1823]
Current time not show in scp\users\manage account form
![no_time](https://cloud.githubusercontent.com/assets/9958813/6614182/dddfce22-c8a7-11e4-9139-78ffa32698c5.png)

same on scp\settings\system
![no_time_2](https://cloud.githubusercontent.com/assets/9958813/6614212/499a804e-c8a8-11e4-9724-2a9b425972be.png)

current time show only at Add New Agent form
![time_show](https://cloud.githubusercontent.com/assets/9958813/6614216/62bd54fc-c8a8-11e4-8543-1a8a41500fd0.png)

**Comment by ntozier** [comment]
It's my understanding that is a FORMATTING example of what the time will look like, not what it is.

**Comment by greezybacon** [comment]
The new version in the `develop-branch` drops this feature entirely in favor of the olsen database (America/Chicago), and has options for "System Default" and auto detection.
