### ISSUE TITLE
Dashboard graph comes up blank, needs one or more refreshes to display properly.

### ISSUE THREAD

**Issue by sstillwell** [osTicket/osTicket-1.8#1828]
This occurs pretty much every time I go to the dashboard - I'll have to refresh, leave the page, come back, refresh again, or some dance like that to get the dashboard to display properly.  At some point it will draw parts of the graph like the node labels, but have to do it several times to get the whole thing to show up.

![osticketblankdashboard](https://cloud.githubusercontent.com/assets/794215/6628688/98b840a8-c8d5-11e4-93e4-8ecb1ce83185.jpg)

This has been pretty consistent since I installed the software, through multiple updates.

Currently running on Debian wheezy, nginx 1.62, MySQL 5.5.41, php 5.4.37-1~dotdeb.1.  All patches up to date and currently on osTicket v1.9.6 (e3e77001)

**Comment by mfelber** [comment]
This seems to be a duplicate issue: https://github.com/osTicket/osTicket-1.8/issues/1353

**Comment by sstillwell** [comment]
@mfelber I already have that commit since I'm on branch 'develop' at e3e77001.  Verified that footer.inc.php already contains that change.  Ideas?

**Comment by mfelber** [comment]
@sstillwell This is still an open issue. The fix in #1353 only addresses correctly displaying the copyright text. I have no coding skills, so I can't tell you why this is happen or how it could be fixed.

**Comment by mckaygerhard** [comment]
i have same behaviour, i need to refresh the page to get reports displayed!

got that errors in console:

```
Error: Raphael is not defined
Source File: http://intranet1.net.ve/soporte/scp/js/g.line-min.js
Line: 7
Error: $("tabular-navigation").tab is not a function
Source File: http://intranet1.net.ve/soporte/scp/js/dashboard.inc.js
Line: 105
```

same problems with #1853

**Comment by greezybacon** [comment]
Can anyone verify if the patch in #1853 addresses the issue?

**Comment by mckaygerhard** [comment]
fixed this, so close it this issue, but still  error the pagination on reports

**Comment by mfelber** [comment]
@greezybacon I have tested this patch with osticket 1.9.5.1 and the ticket activity graph is now loading every time successful :-) Thank you! First I had some trouble with the patch, because in the file "include/staff/templates/navigation.tmpl.php" was this line missing: $tab['href'],$tab['desc']);
The "green" code lines which show what lines should be added doesn't show this line, but when I click on the "View"-Button in github, I see that it should be there after line 6 (and this line was not in this file before)..

**Comment by balojs** [comment]
:+1:

**Comment by mckaygerhard** [comment]
so the , issue now fixed but the style are bad now (only in firefox)

**Comment by mckaygerhard** [comment]
hey now that pagination are fixed, may i have to open a issue for the bad rendering related?

**Comment by greezybacon** [comment]
@mckaygerhard I cannot confirm the bad rendering in Firefox. You can submit a new issue if you would like
