### ISSUE TITLE
Search "unassigned" doesn't work

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#1832]
V.1.9.6

If I use "advanced search" and I search vor "unassigned" then i get not the right result.

I corrected the code in ticket.inc.php on line around 618
from; 
\<option value="0">&mdash; <?php echo __('Unassigned');?> &mdash;\</option>   to:
\<option value="s0">&mdash; <?php echo __('Unassigned');?> &mdash;\</option>

now it works

**Comment by mckaygerhard** [comment]
i confirmed this issue, maks as unnusable the system due does not works as expected! The problem its nore bad rather thatn explained here!

if selected "anyone", found same results as "unassigned"!

also confirmed the patch with os tiket 1.9.4 does not works perfectly with langs es and ru.

**Comment by mckaygerhard** [comment]
I detected that in langs spanish, russian an greek the lables for search in staff panel are swapped AND RESULST ALWAYS WIL RETURN BAD!!!

also the values are swaped, does s0 used as value in assignee html tag  for Unnassigned? or must be Anyone?

**Comment by greezybacon** [comment]
@markus4000 thanks for the code hint. Can you verify that #1857 fixes the issue?

**Comment by mckaygerhard** [comment]
hello @greezybacon  i try the commit and only works with english, if i load spanish, french or russian, does not work due languaje files are bad translated, the status tranlation are swaped

and in the v 1.9.5 does not work, with change need 1.9.5.1 or 1.9.6?

**Comment by C4RLOCO** [comment]
For what is worth, I could help out with English to Spanish translation...  Just need someone to point me into the right direction..

**Comment by mckaygerhard** [comment]
the problem its not the translation, @C4RLOCO the problem its that the translation tool (a web interface) does not permits verify some strings, due some are missing or some are not valid, others need tune..

**Comment by C4RLOCO** [comment]
Gotcha! I was just trying to be helpful.

**Comment by infectormp** [comment]
Confirm, fix work.

**Comment by C4RLOCO** [comment]
Thanks! it works!

**Comment by markus4000** [comment]
it works. I close it.

**Comment by mckaygerhard** [comment]
the search in english works, but in spanish are swaped, so i open a new issue!
