### ISSUE TITLE
Client Ticketview, Fileupload bug

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#1833]
v1.9.6
After the client made a fileupload, the files are still in the editor as attachment. So if the client sends then a second message, it will upload the files a second time. but it musstn't

**Comment by greezybacon** [comment]
Thanks for the issue. I was able to confirm this

**Comment by greezybacon** [comment]
@markus4000 could you maybe retest with the patch in #1845?

**Comment by markus4000** [comment]
perfect. it works. Thanks
