### ISSUE TITLE
v1.9.6: User "Organization" Issue after upgrading from v1.9.4

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#1834]
Upgraded from 1.9.4 to 1.9.6

All the users who were not assigned to any organization started to contain a random 3 digit number as an organization in version 1.9.6.

See attachment 
![screen_shot_2015-03-14_at_9_39_57_pm](https://cloud.githubusercontent.com/assets/4073792/6654331/cd1025aa-ca92-11e4-909d-a342c52ea136.png)

The new organization has the following link: #users/0/org

**Comment by C4RLOCO** [comment]
Just noticed the Organization name is the same user id. See: /scp/users.php?id=493

**Comment by C4RLOCO** [comment]
Here is another screen shot from a different user who had no organization prior upgrading to 1.9.6. This is a blank popup that shows when clicking this random organization number 
![screen_shot_2015-03-14_at_10_53_02_pm](https://cloud.githubusercontent.com/assets/4073792/6654469/5d18475e-ca9d-11e4-9afe-b57813e15bfc.png)

**Comment by markus4000** [comment]
I have the same issue. I think its a bug.

**Comment by C4RLOCO** [comment]
@markus4000 I also noticed there was not a database upgrade per se. Meaning, after installing the new upgrade files, the system did not go under a database upgrade. I wonder if this is expected.

**Comment by C4RLOCO** [comment]
Confirming this bug by creating a brand new database. Once you create the first user the system shows the same results described above.

**Comment by greezybacon** [comment]
Thanks for the issue. This was a bad merge from an i18n change

**Comment by C4RLOCO** [comment]
No worries. Thank for  for addressing it so quickly!

**Comment by C4RLOCO** [comment]
@greezybacon it now add a "0" (zero) to users without an organization. However, when clicking the "0" link it opens correctly the dialog box to add an organization for the particular user.

You are going on the right direction but I'm afraid you are not quite there yet.

**Comment by C4RLOCO** [comment]
My bad.. I re-did the path and it now shows "Add Organization" correctly... I apologize for the previous message.. Thanks @greezybacon

**Comment by greezybacon** [comment]
@C4RLOCO no worries. Glad everything is working

**Comment by markus4000** [comment]
On my Installation it still doesn't work.
I habe the same problem.
Am 17.03.2015 02:23 schrieb "Jared Hancock" <notifications@github.com>:

**Comment by Chefkeks** [comment]
@greezybacon 
Are there any plans for a bug-fix / hot-fix release of 1.9.6?

**Comment by greezybacon** [comment]
@Chefkeks I think it's going to come to that

**Comment by ponasromas** [comment]
This problem resurfaced again in 1.15.1. Please provide a solution.

**Comment by JediKev** [comment]
@ponasromas 

I'm not really sure what you mean by this. In v1.15.1 if a User does not have an Org we do not show the label at all in the Ticket header (see Image 1 below). If a User does have an Org we show the label and the Org name (see Image 2).

### Image 1
<img width="948" alt="Screen Shot 2021-02-18 at 09 01 31" src="https://user-images.githubusercontent.com/11823401/108377458-ab39f700-71c9-11eb-808e-3235960dd926.png">

### Image 2
<img width="945" alt="Screen Shot 2021-02-18 at 09 02 09" src="https://user-images.githubusercontent.com/11823401/108377491-b2610500-71c9-11eb-9597-d148d15dcf88.png">

Cheers.

**Comment by JediKev** [comment]
@ponasromas 

In v1.15.1 if a User does not have an Org we show `Add Organization` link within the User Information Header (see image below).
<img width="485" alt="Screen Shot 2021-02-18 at 09 15 39" src="https://user-images.githubusercontent.com/11823401/108377960-2c918980-71ca-11eb-8404-24ac8a76be6d.png">

Cheers.
