### ISSUE TITLE
v1.9.6: Deleting User along with its Tickets

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#1837]
When deleting an user and checking the box to delete all its associated tickets, the system fails to also delete the data associated to that ticket in the table ost_ticket__cdata. See screenshots below:

![screen_shot_2015-03-15_at_7_40_05_pm](https://cloud.githubusercontent.com/assets/4073792/6658806/aa71dd4a-cb4b-11e4-82fb-3caa5e5ac712.png)
![screen_shot_2015-03-15_at_7_41_09_pm](https://cloud.githubusercontent.com/assets/4073792/6658810/b3bc61d6-cb4b-11e4-82c6-92e52bc19421.png)

**Comment by C4RLOCO** [comment]
Same thing goes when deleting a ticket directly from the Open view. I'm starting to think this might not be a bug but it could be an expected behavior. If so, isn't this taking database space that it is not longer needed? Why the need to keep this records after the ticket associated is deleted?

**Comment by greezybacon** [comment]
I agree this is a problem

**Comment by C4RLOCO** [comment]
Thanks @greezybacon for chiming in. FYI: This issue also happens in v1.9.4. I wonder if it happens on ANY  version though! Look like an important one to fix

**Comment by greezybacon** [comment]
@C4RLOCO I think the extra time is nominal. I do agree the system should do a better job of cleaning it up

**Comment by greezybacon** [comment]
@C4RLOCO can you check if the patch in #1840 addresses the issue?

**Comment by C4RLOCO** [comment]
Outstanding! patch addresses the issue! Thank you sir!
I tested both: a) Deleting the ticket from the Opened View and also deleting the User along with its tickets.

Results: cdata table removes the associated information.
