### ISSUE TITLE
v1.9.6 date search still doesn't work 

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket-1.8#1838]
I've made this search 
![search-196](https://cloud.githubusercontent.com/assets/6535381/6664569/48c6276e-cbd1-11e4-8b54-9afb369439e1.JPG)

and the result is all the ticket closed by me since 1 Jannuary 2015  
![search-196-results](https://cloud.githubusercontent.com/assets/6535381/6664587/7e1c06ae-cbd1-11e4-99bf-7d36c3d16198.JPG)

**Comment by cervedgroup** [comment]
same result if i only choose a time period without selecting "closed by me" , i got all the tickets created since  May 2014 (searching tickets created first 5 days of March 2015)...

**Comment by C4RLOCO** [comment]
same result here..

**Comment by cervedgroup** [comment]
the #1848 solved the issue. Thank you!!!
