### ISSUE TITLE
account.php wrong time showed to the user

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#1842]
As suggested in https://github.com/osTicket/osTicket-1.8/issues/831#issuecomment-81859765 i open this because time is not showed in the rigth way in the account registration page for the user.

Also if the user change from Paris ( or other timezone ) to different time zone , the time showed on the rigth is the same.

**ntozier**
In the time in the Account Registration screen is not the individual's correct time, my guess is its because the individual doesn't have an account yet to influence the offset. So it looks like it's defaulting to GMT.

/include/client/register.inc.php
line 64
**<?php echo Format::date($cfg->getDateTimeFormat(),Misc::gmtime(),$info['tz_offset'],$info['dst']); ?>)**

**Comment by PeopleInside** [comment]
when this will be fixed?

**Comment by greezybacon** [comment]
This is corrected in the `develop-next` branch and released in the 1.10-dpr.

**Comment by PeopleInside** [comment]
Thank you so i can close this topic
