### ISSUE TITLE
Uncaught TypeError: Cannot call method 'attr' of undefined in reports topics

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket-1.8#1853]
when i ty to see another page of reports by topics, i get on console:

```
Uncaught TypeError: Cannot call method 'attr' of undefined 
```

**Comment by mckaygerhard** [comment]
i get this with current lasted stable (i does note until now due never get enough data to see) and also get same error with developer-next brand

**Comment by greezybacon** [comment]
@mckaygerhard can you verify if the patch in #1856 addresses the issue?

**Comment by mckaygerhard** [comment]
woks only for refresh case, for error still does not

**Comment by mckaygerhard** [comment]
tested now in 1.9.5, the previous test was in 1.9.4, i still got the error and pagination does not work

but refresh proble are solved ;)

**Comment by greezybacon** [comment]
@mckaygerhard maybe you should just try download the code from https://github.com/greezybacon/osTicket-1.8/tree/issue/1853 directly. I don't get the error any more, and pagination works fine.

**Comment by greezybacon** [comment]
@mckaygerhard actually I noticed that Firefox was genuinely rendering the table incorrectly with the jQuery .show() and .hide() methods. I've rebased it so it works better in Firefox.

**Comment by mckaygerhard** [comment]
i exporte the git and made a difff, commit the diff and works the pagination **and does not have now the error...** the problem was the cache of my reverse-proxy server.. 

but that brand does nothing different rahter thant the diff i generated, what u changes to firefox does not render incorrectly the reports?

i'll close the issue due now works well, but what u do that does render correclty?
