### ISSUE TITLE
Thread draft from previous unsaved ticket

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1884]
Test case:
1. Press New Ticket
2. Write something to summary field
3. Wait for message Draft Saved
4. Close new ticket without save
5. Press New Ticket and you see saved draft from previous not saved new ticket.

**Comment by greezybacon** [comment]
How is this a bug? The system is saving your draft of a yet-unsubmitted ticket

**Comment by infectormp** [comment]
Maybe you right. If i press cancel draft gone.
