### ISSUE TITLE
User edit form opens under user popup window

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1885]
1.Open user directiry 
2.Put mouse cursor to user and get user popup window.
3.Choise Edit user 

User edit form opens under user popup window
![user_popup](https://cloud.githubusercontent.com/assets/9958813/6770208/5a838fc0-d0ca-11e4-8404-e7866faa85ba.png)

**Comment by infectormp** [comment]
and maybe missing icon

**Comment by greezybacon** [comment]
I can confirm the dialog and pop-out dance that's happening here

**Comment by greezybacon** [comment]
@infectormp can you see if the patch in #1919 addresses the z-index issue?
