### ISSUE TITLE
admin or user do not get notification on osTicketv-1.9.6

### ISSUE THREAD

**Issue by zulhiyatiuwi** [osTicket/osTicket-1.8#1887]
excuse me.. i have some trouble when i use osticketv-1.9.6. when i open new ticket, user doesn't receive email of ticket number. and admin or department do not get the notification of new ticket to too... but in osticket helpdesk website the ticket is appear. could you help me, please??

**Comment by infectormp** [comment]
can't confirm

**Comment by ntozier** [comment]
How do you have osTicket configured for email? 
ie what are your Email settings?

**Comment by greezybacon** [comment]
@zulhiyatiuwi Can you visit the Admin Panel -> Settings -> Autoresponder and Admin Panel -> Settings -> Alerts and Notices and verify that you have the respective alerts enabled?

**Comment by zulhiyatiuwi** [comment]
![alerts notices](https://cloud.githubusercontent.com/assets/11604784/6793711/2a46e258-d1fb-11e4-9b40-31682b2ee235.png)
![autoresponder](https://cloud.githubusercontent.com/assets/11604784/6793713/2e79b472-d1fb-11e4-857f-08eb5b873eb1.png)

**Comment by zulhiyatiuwi** [comment]
And this is my emails setting.
![emails](https://cloud.githubusercontent.com/assets/11604784/6793789/55b8e2e6-d1fc-11e4-9ff7-9f5b4cc077f1.png)

**Comment by ntozier** [comment]
The screen shot that you provided of Admin Panel -> Settings -> Autoresponder
indicates that you have not enabled the New Ticket autoresponder.

**Comment by zulhiyatiuwi** [comment]
i have enabled it... but user still do not receive notification. admin too. i do this setting to install the osticket. what i'm wrong when do the installation?
# apt-get install mysql-server mysql-client
# mysql_secure_installation
# apt-get install apache2 php5 libapache2-mod-php5 php5-mysql php5-curl php5-gd php5-idn php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl

# mysql -u root -p
Enter password:
 
mysql> CREATE USER 'osticket'@'localhost' IDENTIFIED BY 'p@ssw0rd';
Query OK, 0 rows affected (0.00 sec)
 
mysql> GRANT USAGE ON * . * TO 'osticket'@'localhost' IDENTIFIED BY 'p@ssw0rd' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
Query OK, 0 rows affected (0.00 sec)
 
mysql> CREATE DATABASE IF NOT EXISTS `osticket` ;
Query OK, 1 row affected (0.00 sec)
 
mysql> GRANT ALL PRIVILEGES ON `osticket` . * TO 'osticket'@'localhost';
Query OK, 0 rows affected (0.00 sec)
 
mysql> FLUSH PRIVILEGES;
Query OK, 0 rows affected (0.00 sec)

# cd /var/www/ 
# wget http://osticket.com/sites/default/files/download/osTicket-v1.9.6.zip
# unzip osTicket-v1.9.6.zip
# ln -s upload osticket
# chown -R www-data:www-data upload
# cd osticket
# cp include/ost-sampleconfig.php include/ost-config.php
# chmod 0666 include/ost-config.php

![011](https://cloud.githubusercontent.com/assets/11604784/6795274/84ca0e66-d210-11e4-8ef8-8e7abef3fa63.png)

**Comment by ntozier** [comment]
You have not provided your email settings.
Did you install an MTA?
I'd recommend setting up SMTP in your email settings.

**Comment by zulhiyatiuwi** [comment]
i do not install an mta. i'm sorry but could you recommend me a link to set up an SMTP? because i have searched and try all of setting that i found, but i fail.

**Comment by ebell451** [comment]
Did you try the Emails > Diagnostic via the Admin Control Panel to see if you can send email via the default setting? If you cannot send via the PHP mail function, then do as recommended and setup the SMTP settings for your email (https://support.google.com/a/answer/176600?hl=en).

**Comment by zulhiyatiuwi** [comment]
@ebell451 i do not receive email when i send mail form email > diagnostic.

**Comment by mckaygerhard** [comment]
seems that u dont are related to linux systems, tutor saids that u dont need MTA if u have an MTA in another host.. by example u can use and MTA of gmail using u'r own account to send the mails to the others throught os-ticket system·..

in u'r setting seems u have configured and own accont to those, but take in considerations that gmail its also a powered linux system, and as any linux all are disabled..

do u enable MTA premissions to send by another host on u'r gmail settings? can u send emails from u'r computer using gmail accounts! of course not! due u never do this from a linux .. using guindows always u already made but between gmail accouns..

so i recomended to revise gmail setting and grand acess to u'r host to login to MTA of gmail and can send email from another host that are not a gmail host.. and if u not have an ceritfied ip u cannot doit that..

so then in thi9s case *u always need and MTA* of course not in the same machine.. but always will need!

i can see the guindow so i recomended install debian also in the work machine so u can take more close to those common problems..

**Comment by greezybacon** [comment]
@zulhiyatiuwi Windoze cannot send mail with the php `mail()` function. You'll need to configure an SMTP email address

**Comment by ntozier** [comment]
It (Win) actually can... but only if you configure PHP properly.

You have to set
[mail function]
; For Win32 only.
; http://php.net/smtp
;hostname or ip address
SMTP = MAILSERVER
smtp_port = 25
;You may need to also set:
;address to send email from.
sendmail_from email@domain.tld

**Comment by greezybacon** [comment]
@ntozier Good point. Again, you have to configure an SMTP address. Just up to the admin as to where.

**Comment by zulhiyatiuwi** [comment]
I setting it via putty, my tutor give me an vir machine. -.-
![untitled](https://cloud.githubusercontent.com/assets/11604784/6816192/5b067d00-d2c2-11e4-80fc-e2d4f69dfdad.png)

**Comment by ntozier** [comment]
You're setting what via SSH?

**Comment by mckaygerhard** [comment]
i think he must read more about, seem he's a little disoriented, linux its not double-clicked os

hi @zulhiyatiuwi firs u must find the php packages installed correctly, php mail() function does not work as expected if u does not have property configured!

second:
* if u use a php mail function, its not necesary setup and account if u have a sendmail program, 
* in the otherwise, its when u must configure a external account (such as u done with gmail)

if u use a gmail account must test if u can use it! well try telnet to port 25 and see if return the domain of an smtp of on of the 6 MTA servers of the google..

think that setup the gmail account in the osticket its as like setup the gmail account in the thunderbird.

second, It is strongly recommended that you use linux as main os but if you plan to develop or administer something related, using guindow as main os always u will have some probles due you'll not be accustomed

but if you're just showing a blip, best use focused guindows software, because here in linux you should know what you do

**Comment by zulhiyatiuwi** [comment]
thank you for all help. i don't understand and know about this well. i'm still in doubt. so i will learn more about it first. and i will back to ask the question when i know the problem more details. ^.^. thank you.

**Comment by mckaygerhard** [comment]
better let of use the guindows os, that's its u real problem

**Comment by ebell451** [comment]
In an effort to better assist, can you provide the following information:

1. In osTicket > Admin Panel > Dashboard > Information
2. Create a file phpinfo.php containing the following"

<?php
phpinfo();
?>

--Ethan

**Comment by zulhiyatiuwi** [comment]
Now, admin and user receive alerts when open new ticket.. 
but what should i do so, email can connect with other mail like gmail or yahoo? my domain email is mail.unandtest.com. when i sent mail to gmail or yahoo. i get an email content with this subject "Undelivered Mail Returned to Sender". thank you. should i creat a new issue to ask this question?

**Comment by mckaygerhard** [comment]
the problem of the delivering its only u'r own mta.. sur e u have wrong setup.. so i guesss this issue must be closed

**Comment by zulhiyatiuwi** [comment]
ok.. thank you...

**Comment by greezybacon** [comment]
@zulhiyatiuwi usually you just configure an email address in Settings -> Emails -> Add new email, enter the login information and host, port, and protocol information. You should be able to get most of the information from the control panel of your hosting provider.

**Comment by herdi89** [comment]
hi... i'm using office365 as my email.
but when i try to diagnostic the email, i got the notification that the email was sent successfully.
But when i checked in my email, i didn't receive that email?

here is my setting below. can you help me? thank you.
![image](https://cloud.githubusercontent.com/assets/16377998/11923327/46e5486e-a7d4-11e5-99fc-7d1258061ea3.png)

**Comment by bush12** [comment]
hello member 
i have installed and configure osticketing (v1.9.8.1 (4752178) the user can create the new ticket but the notification are not sent , secondly when i register a new user in the system the user status remain in active and he/she can not login to the system.

**Comment by bush12** [comment]
PHP Settings
cgi.fix_pathinfo 	"1" is recommended if AJAX is not working
date.timezone 	Setting default timezone is highly recommended

**Comment by bush12** [comment]
help please
