### ISSUE TITLE
Configure min searchphrase length

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket-1.8#1888]
Hi,

is is possible to define the mind searchphrase length?
Right now i am realizing that i cant search for 3-letter strings in my 1.9.4 setup.
Is that related with a database-setting or a pure osticket setting?

Greetings

**Comment by mfelber** [comment]
Google is your friend ;-) http://www.netzmacher.ch/mysql/osticket-with-mysql-search-with-4-characters-or-less/

**Comment by yafp** [comment]
so i assumed right it is related with the min_length in mysql. Thanks for the pointer - it helped.

One point is still unclear for me - if its comes rebuilding the indexes for the search:
The link above is mentioning to do a repair for the related table - so far i did that for the os__search table - but which other tables might be important for the search-function of osticket?
Any idea?


Greetings

**Comment by mfelber** [comment]
Unfortunately I have no idea and I don't want to give you a wrong "advice". So maybe one of the "moderators" or more experienced users could give you a helpful answers to this question..

**Comment by greezybacon** [comment]
@yafp just drop the `ost__search` table. The system will recreate and repopulate it.

**Comment by yafp** [comment]
@greezybacon:
i copied the table os__search and then dropped it.
The table got repopulated by itself - good so far.

But my search itself seems broken/not-working now. 
Do i need to trigger something else? The new generated table is empty so far.

**Comment by yafp** [comment]
*closing the issue*
