### ISSUE TITLE
1.9.6 Post reply pop up dialog

### ISSUE THREAD

**Issue by jacobwoffenden** [osTicket/osTicket-1.8#1896]
When posting a reply to a ticket, I get the following

![screen shot 2015-03-24 at 12 13 19](https://cloud.githubusercontent.com/assets/9742606/6801443/934078b8-d21f-11e4-9d16-b5cc96c95326.png)

Apologies if this is a know issue, I couldn't find it.

**Comment by greezybacon** [comment]
@jacobwoffenden could you try the patch in #1898 to see if it addresses the issue?

**Comment by jacobwoffenden** [comment]
So far, it's not popped up _yet_

Since changing that one line in ticket.js it has now done the following
![screen shot 2015-03-25 at 16 49 41](https://cloud.githubusercontent.com/assets/9742606/6830038/4285a272-d30f-11e4-9a7f-44935e3e11cf.png)

**Comment by greezybacon** [comment]
Looks like you have a javascript error. Can you maybe find it in the error console?

**Comment by jacobwoffenden** [comment]
Hey, sorry I didn't reply - I've been on sick leave.

I am not aware of an error console in the application, is there any documentation highlighting it?

Thanks,

Jacob

**Comment by greezybacon** [comment]
We merged the suggestion into the `develop` branch. Can you just try updating the codebase to the latest available from GitHub and retry?
