### ISSUE TITLE
Make attachments as mandatory

### ISSUE THREAD

**Issue by juraganerka** [osTicket/osTicket-1.8#1899]
Does anyone has mod attachments become mandatory?

**Comment by greezybacon** [comment]
This is possible in the latest version. Add a new field to the ticket details form of type "file upload", set the field as required by users and configure it as necessary.

**Comment by juraganerka** [comment]
@greezybacon  so there is not mod in version 1.8 for attachment mandatory?

**Comment by greezybacon** [comment]
@juraganerka I can't help with "mods". I develop the mainline product
