### ISSUE TITLE
special chars not saved in db

### ISSUE THREAD

**Issue by maotm** [osTicket/osTicket-1.8#1906]
Hi, there are two romanian special chars which are not saved at all in the database.
Version 1.9.6, clean install ...
Special chars  ș ț if input from admin, are saved in database as   &# 537;  &# 539; 
but the same chars if input from client side are not converted, and saved as ” ș ț ” - all special chars viewed from admin will show garbage.
These  2 special chars: î or â  ( &# 238; &# 226; ) are not saved at all from admin , only from client, which can see any special chars will input, because are not converted to &# ... 
db set to utf-8 romanian-ci or general-ci makes no difference

**Comment by greezybacon** [comment]
@maotm can you provide screenshots of the process so I can attempt reproducing the behavior?

**Comment by maotm** [comment]
Hi, I have some pics in the forum:
http://osticket.com/forum/discussion/comment/93948 
Thx,

**Comment by maotm** [comment]
... I think you can copy paste these 2 chrs in a ticket:  î and â  and see what you can see from client and from admin, and check what get  saved in the db . Also try with these: ș ț ă .
thx

**Comment by ntozier** [comment]
@greezybacon this is the forum post I sent to you earlier today to take a look at btw.

**Comment by ntozier** [comment]
![capture](https://cloud.githubusercontent.com/assets/1315768/6835458/4db769f8-d311-11e4-8038-d1f8d43610a8.PNG)

this is what I see (admin panel)

**Comment by maotm** [comment]
my setup:
![conf](https://cloud.githubusercontent.com/assets/3588626/6836176/7f6aa69a-d348-11e4-8b63-679be47206b4.jpg)

**Comment by greezybacon** [comment]
Interesting: the display of your language pack is borked. Looks like you have some server-related encoding ussye

**Comment by maotm** [comment]
Indeed:
I did a new clean install on this server and i get the same error.
I did a clean install on another server, and it works fine. 
Any ideea where to check encoding error, on a Centos 6.6 (x64) ?
![conf-ok](https://cloud.githubusercontent.com/assets/3588626/6841797/63f17c54-d398-11e4-8896-d337c5b6a2e4.jpg)

**Comment by maotm** [comment]
.. but why it happens only from admin and not from client side ?

**Comment by maotm** [comment]
Hi found the solution:
add these lines to php.ini and restart httpd :
default_charset = "utf-8"
mbstring.internal_encoding=utf-8
mbstring.http_output=UTF-8
mbstring.encoding_translation=On
mbstring.func_overload=6

found on 
http://stackoverflow.com/questions/13104615/utf-8-character-set-centos-php

**Comment by greezybacon** [comment]
I'll reopen the issue and add these settings to the "Information" page. Thanks for the investigation

**Comment by greezybacon** [comment]
@maotm it looks like the character encoding is not properly sent to the browser from the staff panel. Is there a way you could revert your PHP ini changes and try the patch in #1918 to see if it addresses the issue?

**Comment by maotm** [comment]
Hi,
Yes, it works now. 
Thank you.

**Comment by greezybacon** [comment]
@maotm can you confirm whether your settings change or the patch fixed the issue?

**Comment by maotm** [comment]
Hi ,
I've reverted the php.ini changes, and apply the patch.
So the patch fixed the bug. Thx.

There is a small bug in include/client/login.inc.php in line ~8:
if ( $content) {
    list($title, $body) = $ost->replaceTemplateVariables(  ... 
should be 
if ( !$content) {   // !$content 
    list($title, $body) = $ost->replaceTemplateVariables( ...
otherwise the text :  $body = __('To better serve you, we encourage our clients 
never gets translated.

**Comment by greezybacon** [comment]
@maotm I think you're confused. The `$content` in this context is pulled from the database and is editable / translatable in Admin Panel -> Settings -> Access -> Client Sign-In Page

**Comment by maotm** [comment]
:-) maybe I am confused, but with " if ( $content) " instead of  "if (! $content) " the text "To better serve you, we encourage our clients to register for an account and verify the email address we have on record."  is not translated into another language.

**Comment by greezybacon** [comment]
@maotm you can translate it if you visit the page I cited in the admin panel. That text is provided as a fallback in the event the database is screwed up.

**Comment by maotm** [comment]
OK. Now I found it. Thank you.

**Comment by dluyten** [comment]
I have the same problem, applied the patch, changed the php.ini,... problem is still there

**Comment by greezybacon** [comment]
@dluyten could your provide a bit more information? Where are you seeing the problem? Which patch did you install? Which problem exactly still exists? What did you change in php.ini?
