### ISSUE TITLE
About Performance and server sizing

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket-1.8#1910]
Hi,in this config 
ost version 1.9.6 - heidisql 8.0.0.4396 - IIS 7 on windows server 2008R2 - php 5.5.11
the server (VM on esx) have 2 processors / 4 GB ram
we have 7 departments (with 1 email each) and around 20-25 agents working during the day, closed ticket in last 12 months around 17k - db size is 2.1 Gb (1.9GB is ost_filechunk table)

So , in latest weeks (with 1.9.2 before and now with 1.9.6 ) we are experencing some performance issue in the scp interface, (very slow list opening and tickets editing / reply ecc..). 
This slow performance tooks around 10-15 minutes and occur 2-3 times at day in different hours and seems not related to numbers of tickets opened; maybe related to agents activity (how can we check that)?
Used Ram was below 50%

Seems that when we fetch the emails the (php-cgi.exe and/or mysql.exe) processor goes to 90-100% for 10-20 secs and then go back under 30-40%. 
Also we have around 10 php-cgi.exe istances is normal ?

Any suggestion to speed up the ost ? 
splitting the db to another host from the iis ? add 2 virtual processor ? php/db version upgrade ? 
any other suggestions are welcome ?

Thank you !

**Comment by ntozier** [comment]
Re: heidisql 8.0.0.4396
My understanding is that this is a 3rd party MySQL/MariaDB/MSSQL client, and not a database server. [Am I wrong?]  Please provide Database Server software and version.

**Comment by cervedgroup** [comment]
yes, you right, the version of DB is MariaDB 5.5.32 (x64)

**Comment by greezybacon** [comment]
@cervedgroup there's a table that needs an index and causes slow performance opening a ticket view. Could you maybe try the patch in #1900? This is targeted at the problem for v1.9.6.1

**Comment by cervedgroup** [comment]
with the patch, tickets listing seems loading from 2 to 3 times faster!
thank you!!!
