### ISSUE TITLE
Ticket filter is not working

### ISSUE THREAD

**Issue by tosbaha** [osTicket/osTicket-1.8#1915]
I created new form "My Form" then created new list named "My List" added items(name of staff), then added new property Labeled as  "Staff ID" and used staffid as variable. Afterwards, I set different staff id for each item in "My List" such as 100, 101, 102 etc. Then in "My Form" attached "My List" as custom list. Then I created a new filter name and used below rules

My Form/My List contains 100
My Form/My List/Staff ID contains 100

None of the rules worked no matter how many times I have tried. Am I doing something wrong, or those properties of list item can't be used in filters?

Filter only works if I do something like
My Form/My List contains "name of staff"

**Comment by greezybacon** [comment]
What is the value of the list item? I understand you have a staff_id property, but what is the name of the list item you have typed in the list manager?

**Comment by tosbaha** [comment]
Value of the list item is name of the staff. Let's say John and John have staffid which is 101. I attached some pictures to clarify what I am trying to do
![Filter](http://i.imgur.com/bX3zrAu.png)
![List Items](http://i.imgur.com/cyq1G3r.png)
![List Property](http://i.imgur.com/HszcJpC.png)
![List Example](http://i.imgur.com/3tV7caE.png)
[Form](http://i.imgur.com/aekJMCB.png)

**Comment by greezybacon** [comment]
@tosbaha use the staff name in the filter rule

**Comment by tosbaha** [comment]
If staffid can't be used why we are able to choose it. It is very misleading. As I said I can use staff name but using staff name can cause error but if staffid can be used then staff names can be changed but tickets will be still routed. I hope you add this feature or if not possible please remove item properties from ticket filters

**Comment by greezybacon** [comment]
@tosbaha two things. For the first rule, you're matching "My Form / Staff", which is a list. For a list, you'll need to match on the list item value, the staff name in this case. For the second rule, "My Form / Staff / Staff ID", you should match exactly on the value of the field, so "Equal" "101" in that case. Ensure you don't have any trailing whitespace, which was a problem recently fixed in the `develop` branch.

There was also a bug which fixed this issue in #1741, which was released in v1.9.6

**Comment by tosbaha** [comment]
@greezybacon I put those two rules to show that both of the rules didn't work. I am aware that for "My Form / Staff" to work it needs name of the staff "John" for example. You say that, in order to match it it should be written Equal. It is way better!. Should I use "101" or just 101 ? I am using 1.9.5 so, should I update to 1.9.6 as well ? Thanks.

**Comment by greezybacon** [comment]
@tosbaha you should upgrade to fix the match on the StaffID field. You should not use the quotes when entering the data in the filter.

**Comment by tosbaha** [comment]
Thanks @greezybacon upgrading to 1.9.6 fixed the issue.
