### ISSUE TITLE
Update / edit ticket details does not populate Issue Description with existing data v1.9.6

### ISSUE THREAD

**Issue by markbainflynet** [osTicket/osTicket-1.8#1925]
Hello guys,

I am seeing an issue where if a user or agent edits a ticket's details (via the edit button while viewing a ticket), the Issue Description is empty even though the ticket does have data in it. As this field is mandatory, you need to re-add data to it. osTicket needs to pre-populate the issue description with the existing ticket data.

Something that may help diagnose the issue: osTicket does pre-populate issue description with the last data you entered when editing a previous ticket! For example, if I need to edit a ticket, I copy the original issue description into the clipboard so I can paste it into the incorrectly empty field. When I edit a subsequent ticket, whatever I pasted into the previous issue description will be there. This happens across browser closures etc. Perhaps is it pulling it from the a server side cache?

My set up is:
osTicket Version: v1.9.6 (pulled from from git tag)
Web Server Software: Microsoft-IIS/8.0
MySQL Version: 5.5.42
PHP Version: 5.5.22

All other items as shown on Dashboard -> Information are marked as loaded / functioning.

Thanks a lot!
Mark.

**Comment by ntozier** [comment]
I'm really not sure what you mean... as there is no "Issue Description" field that is editable via Edit Ticket. Can you please post a screen showing what you are talking about?

**Comment by protich** [comment]
The issue was addressed prior official v1.9.6 release. I suggest "upgrading" to the official download or wait for a new v1.9.7 release shipping today.

@ntozier - the issue was legit as described, no screenshot required.

**Comment by markbainflynet** [comment]
Hi guys,

Great news that it is fixed. That was kinda annoying ;-)

I am surprised to hear that the commit tagged as v1.9.6 isn't the same as the official v1.9.6 release. Is this normal, or was it just a slip up for 1.9.6? Is there another commit that does represent official v1.9.6?

We clone and branch locally to edit config files and manage some minor tweaks (nothing worth pushing back into the main stream I promise). We also then use it to publish to our web site. All very neat... until I heard that v1.9.6 tag isn't real ;-)

We never locally merge back up for the next release, so perhaps just copying the release over our local working copy will be ok - but a shame to lose all those great commits with comments!

Thanks,
Mark.

**Comment by protich** [comment]
@markbainflynet -- This was a goof on our part, we debated moving the tag but decided against it. The issue surfaced after the tag! I'll recommend waiting a couple of hours for v1.9.7 tag.

**Comment by markbainflynet** [comment]
Brilliant. Good to hear. And yes, I'll wait for tag v1.9.7. I'll test my issue with it, and hopefully come back here to confirm fixed and close the issue.

Thanks!
Mark.

**Comment by markbainflynet** [comment]
I can confirm that upgrading from GitHub tag v1.9.6 to tag v1.9.7 fixed this issue.

Thanks lot guys,
Mark.
