### ISSUE TITLE
Client View "Username" "Email"

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#1930]
In clientview, the user is asked for:
Email or Username
But a Client never has a "username" they only work with the emailaddress. I think thats confusing for the client. i'd recommend to write "Email" instead of "Email or Username"

**Comment by ntozier** [comment]
It should probably depend on if the LDAP plugin is installed.
For example: We only use usernames here.

**Comment by greezybacon** [comment]
@markus4000 in the admin panel agents can define a username for clients. In multilingual phase IV, we hope to add a phrase override feature where you can change phrases like "Email or Username"
