### ISSUE TITLE
Filtering web and email based on custom lists

### ISSUE THREAD

**Issue by zacharylewis07** [osTicket/osTicket-1.8#1937]
I would like to start off by saying Great Work on osTicket.  My question is in regards to filtering on custom forms/lists within the "user data (contact information) under "Ticket Filters".  Here's my example:  I have a registered user (Teacher1) with a building (School Name) assigned to the user (Teacher1) from a dropdown "List" which the "Building/School" shows under the Users tab/contact information.  I can filter on the user's contact information (filtering: user data) through web submission but not through email.  I would like to know if it's possible to do both, filter on custom contact information through web (which works) and email (does not work) to have new tickets assigned to a Department (based on custom list: "Building" from a user's contact Information)?  I'm currently running version 1.9.7

Thanks in advance!

**Comment by greezybacon** [comment]
Teacher1 should be identified by her email address when she is sending email. Is that not working?

**Comment by zacharylewis07** [comment]
I believe so, but associated with the Teacher1's contact information is Teacher1's Building Location (School) which is not being read/filtered by.  If I filter based on Teacher1's email address or full name it works for email filtering, but does not work for things like phone number, custom list (Building/School). etc.

**Comment by greezybacon** [comment]
It works that way, or is supposed to. Perhaps you could submit so I could help further

**Comment by zacharylewis07** [comment]
Filter/Rule:  I'm testing a custom form and a custom list tied to the user data based on the end-user's data submitted in the "Contact Information" form.  Please note: The filter/rule should assign tickets to the Maintenance Department.
![image](https://cloud.githubusercontent.com/assets/11853376/7050846/b91d562a-dde9-11e4-8b7c-ff73d66b897d.png)

User Properties:
![image](https://cloud.githubusercontent.com/assets/11853376/7050722/fad64da2-dde8-11e4-8ab7-04cb49b97678.png)

Example1:  Web Ticket created by zlewis@mcas.k12.in.us

![image](https://cloud.githubusercontent.com/assets/11853376/7050786/55ef11ba-dde9-11e4-8de6-e58142c68239.png)


Ticket Status: Based on Filtering Rules, the ticket is assigned to the correct Department: Maintenance 
![image](https://cloud.githubusercontent.com/assets/11853376/7050907/1231acd4-ddea-11e4-90c7-445388e6de17.png)


Example2: Email Ticket creation by zlewis@mcas.k12.in.us

![image](https://cloud.githubusercontent.com/assets/11853376/7050989/a538b888-ddea-11e4-95c8-5f99b5908e47.png)


Ticket Status: Based on Filtering Rules, the ticket should get assigned to the Maintenance Dept. but goes to the default dept. Support
![image](https://cloud.githubusercontent.com/assets/11853376/7051042/fa2f4ed8-ddea-11e4-9159-2c95725e5539.png)

**Comment by greezybacon** [comment]
Do you have any other filters?

**Comment by greezybacon** [comment]
I see where the filter information for user's is not loaded before querying the filter system for tickets submitted via API and email. Would you mind trying the patch in #1943 to see if it addresses your issue?

**Comment by zacharylewis07** [comment]
No luck with the patch in #1943 class.tickets.php mod.

**Comment by greezybacon** [comment]
@zacharylewis07 I've updated the patch in #1943, could you try again? (I actually tested it this time)

**Comment by zacharylewis07** [comment]
You are the MAN!  That worked perfectly!!!!
Thanks again!!!
