### ISSUE TITLE
Character set issue after upgrading to v1.9.6 or 1.9.7

### ISSUE THREAD

**Issue by Aka4** [osTicket/osTicket-1.8#1946]
Something wrong with charset encoding, special chars not properly saved in db.
Problem is only with ticket body (ticket title with the same text is ok.) - text:

> zażółć gęślą jaźń TEST PL 1234

in ticket body looks as:

> za¿ó³æ gê¶l± ja¼ñ TEST PL 1234

The same in client and staff panels

Happens if we upgrade to 1.9.7 or 1.9.6. 
In 1.9.5.1 was OK.

Looks similar to #1906 issue.

Tried to set in php.ini lines:

> default_charset = "utf-8"
> mbstring.internal_encoding=utf-8
> mbstring.http_output=UTF-8
> mbstring.encoding_translation=On
> mbstring.func_overload=6

But unfortunately this doesn't help anything. The same effect with and without them.

Other users have the same problem:
http://osticket.com/forum/discussion/85233/character-set-issue-after-upgrading-to-v1-9-6

Below links to:
* [phpinfo page snapshot](http://temp2015.odl.pl/phpinfo.html)
* [email message which was imported to osticket](http://temp2015.odl.pl/email.msg)

I attach screenshots of:
* Ticket body from osTicket staff panel
* osTicket install info
* ticket record from mysql db from _ticket_thread table

![ticket_body](https://cloud.githubusercontent.com/assets/11789024/7086425/1f8aafd2-df81-11e4-823a-cf5bcbe8ea51.png)
![instal_info](https://cloud.githubusercontent.com/assets/11789024/7086424/1f8a4ba0-df81-11e4-9465-608b2760bf5b.png)
![db_ticket_thread_record](https://cloud.githubusercontent.com/assets/11789024/7086426/1f8c9b80-df81-11e4-9752-2356aaba4991.png)

**Also need to mention it's only problem with messages by email.
If we reply the same text from staff panel then reply is ok:**
![ticket_reply_from_staff_panel](https://cloud.githubusercontent.com/assets/11789024/7086785/2f717684-df85-11e4-881c-d6d927baf6f5.png)

This tests all with osticket 1.9.7 and polski (Polish) language pack.

**Comment by greezybacon** [comment]
@Aka4 can you submit an email that is being corrupted — the raw version with the headers

**Comment by Aka4** [comment]
@greezybacon I already attached this email:

Email message which was imported to osticket: http://temp2015.odl.pl/email.msg

**Comment by greezybacon** [comment]
@Aka4 can you attach a plain text version?

**Comment by Aka4** [comment]
@greezybacon Yes, it's here: http://temp2015.odl.pl/email.txt

**Comment by Aka4** [comment]
@greezybacon Yes, it's here: http://temp2015.odl.pl/email.text

**Comment by greezybacon** [comment]
@Aka4 I'm certainly no expert, but the body of the email looks UTF-8 encoded, although it is declared to be ISO-8859-2. What client was used to generate the email?

**Comment by greezybacon** [comment]
Actually, it doesn't look to be utf-8 encoded either. I can't figure out how it's encoded. It actually looks corrupted.

**Comment by Aka4** [comment]
@greezybacon It's encoded ISO-8859-2, you looked at text version, I think web browser sometimes can display it wrong way, so it could look to you as corrupted. 
Try this: http://temp2015.odl.pl/email.zip

Best way, would be if you could open original http://temp2015.odl.pl/email.msg in some email client - there should be option to view headers:
![email_headers_ms_outlook](https://cloud.githubusercontent.com/assets/11789024/7112576/59378bf0-e1cb-11e4-883d-a3d8494253de.png)

**Comment by Aka4** [comment]
@greezybacon I sent this email from one of Polish biggest free email account provider, by web client - here how you can access it:
email login page: http://profil.wp.pl/
user name: user3test@wp.pl
password: pass3test

And below I prepared video how you can send email from poczta.wp.pl and check it's headers:
![email_from_wp_pl](https://cloud.githubusercontent.com/assets/11789024/7113299/a6a72fba-e1d2-11e4-9930-b64f66350b20.gif)

And how this email looks in osticket after it was imported:
![email_from_wp_pl_in_osticket](https://cloud.githubusercontent.com/assets/11789024/7113340/14b35f4c-e1d3-11e4-880e-adc869195395.png)

**Comment by Aka4** [comment]
And here email sent from MS Outlook 2013:
http://temp2015.odl.pl/email_from_outlook.msg - original email
http://temp2015.odl.pl/email_from_outlook.zip - txt version

It looks even worse, both ticked body and title are wrong:
![email_from_outlook_in_osticker](https://cloud.githubusercontent.com/assets/11789024/7114603/43f1a852-e1df-11e4-8ea4-8d1866bf0326.png)

**Comment by Aka4** [comment]
But when I send email from Gmail it's ok., Gmail format message with UTF-8.
Problem is when message is formatted with ISO-8859-2 (emails from web client POCZTA.WP.PL and from MS OUTLOOK).

**Comment by nerull7** [comment]
I've got the same problem. Message is encoded in ISO-8859-2. Problem is in class Charset in function normalize. It changes encoding ISO-8859-2 to ISO-8859-1 which cause glitches.

I've created patch for that bug: https://github.com/osTicket/osTicket-1.8/pull/1953

**Comment by Aka4** [comment]
@nerull7 One typo, first added line, last char, you have semicolon, should be colon.
Beside that it's great, thank you, patch worked :)
