### ISSUE TITLE
Attachments on the filesystem

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1968]
I install Attachments on the filesystem plugin v 0.3 but when ticket stored to osTicket files not saved in folder. Folder still empty.

Apache error log empty.

**Comment by mfelber** [comment]
I'm using the same plugin version and have no problems with it. After installing it, did you activated it and have you changed the responsible setting in the ticket settings section? https://github.com/osTicket/osTicket-1.8/issues/1243#issuecomment-70649375 And if you have done that all, is the folder really empty (sometimes the user account who is looking in this folder has no rights to read the content)?

**Comment by infectormp** [comment]
ah i miss Store Attachments in Settings\Tickets. This setting better plase to plugin settings.
