### ISSUE TITLE
Knowledge Base Edit Removes Previously Inserted Image

### ISSUE THREAD

**Issue by slider162** [osTicket/osTicket-1.8#197]
- Create FAQ
- Insert Image
- Save FAQ
- Edit Same FAQ
- Save FAQ
- Image in no longer available.

I should be able to edit a FAQ/KB article without losing the previously inserted image.

*osTicket (1.8-git)

**Comment by steadhouse** [comment]
We previously had this issue prior to 1.9.4 - but it seems to have been fixed. I believe this can be marked as resolved (unless you're still experiencing the issue)

**Comment by greezybacon** [comment]
Closing the issue as I believe it should be resolved. Please reopen if the problem persists.
