### ISSUE TITLE
Files saved in filestore before post reply

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1971]
In client interface i add files to ticket and before i press Post reply files created in filestore.

**Comment by greezybacon** [comment]
How is this a problem? The files are cleaned up after a day if they are not attached to a ticket

**Comment by infectormp** [comment]
Yes, now i know it. But typically files uploaded to server when you post message. Current realisation looks strange for me.

**Comment by greezybacon** [comment]
@infectormp this is intended to allow for a better experience uploading several large files. The files are uploaded while the user can continue to compose their message. The files can be previewed and deleted before submitting, and also, submission is prevented until the files are finished uploading. It also provides file validation before submission, so files of the incorrect type or size are rejected before submission. 

If you like the old method, you should just downgrade to v1.8
