### ISSUE TITLE
SMTP settings

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1973]
For test purpose in Emails setting i set Sending Email via SMTP to disable. Then i create new ticket as agent and imagine my surprise when i received notification about new ticket. I go to Settings \ Emails in see Default MTA = PHP mailer. Then i go back and set Sending Email via SMTP to enable. Now  Default MTA = SMTP.

**Comment by ntozier** [comment]
I'm not sure why your surprised by this.
If you wanted to disable sending emails you would disable all Autoresponder and Alerts and Notices.

**Comment by infectormp** [comment]
then for what need ability to disable SMTP?

**Comment by ntozier** [comment]
To stop sending email via SMTP.
Such as if you wanted to transition from one account to another.
Or if you wanted to test PHPmail.

**Comment by infectormp** [comment]
If i want test PHPmail i go to email setting and set PHPmailer instead of SMTP. But if i don't want send email for any Alerts and Notices i must have ability to disable SMTP.

**Comment by infectormp** [comment]
Now if i disable SMTP PHPmail enabled automatic.

**Comment by protich** [comment]
@infectormp - You're mistaken. To disable alerts and notices go to Admin Panel > Settings > Alerts & Notices.

**Comment by infectormp** [comment]
@protich - To disable all alerts and notices i need uncheck 6 radio button. This is not useful.

Let see to osTicket notification settiung more closer.

osTicket have 4 level where you can disable or enable mail notification:
1 level - POP3\SMTP - here you can disable all inbound and outbound mail (System level)
2 level - Email Fetching - here you can disable Fetching from mail box (Global level)
3 level - Autoresponder Settings - here you can disable notice for client (Event level)
4 level - Alerts & Notices here you can disable specific alerts and notice for agent (Event level)

1 level work incorrect:
if i disable Fetching Email via IMAP or POP Default MTA still SMTP
if i disable Sending Email via SMTP Default MTA automatic switched to PHPmail

2 level: Disable Email Fetching = Disable POP3\IMAP. 

in my opinion Level 3 and 4 need merge to one section because both in Event level. Event level will be more easy managed

**Comment by infectormp** [comment]
@protich - your recomendation don't work if i have 2 mailbox and i need disable specific Alerts & Notices for different mailbox
