### ISSUE TITLE
Ticket Owner notification not respect ticket created by agent

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#1974]
In Autoresponder Setting i disable Ticket Owner notification, then create ticket by agent and get email at user side about new ticket.

If i submit ticket over email or user interface i not get notification.

**Comment by protich** [comment]
You'll need to disable "New Ticket by Agent" alert in Admin Panel > Settings > Autoresponder.

**Comment by infectormp** [comment]
You right, my mistake.
