### ISSUE TITLE
Client Portal - Cant seach via ticket ID

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket-1.8#1980]
Users can search with keywords in the Ticket, however when the query term is numeric, the $queryterm isnt available/retrieved, so the query never filters.

see below.

if($search) {
    $qs += array('a' => $_REQUEST['a'], 'q' => $_REQUEST['q']);
    if(is_numeric($_REQUEST['q'])) {
	missing --> $queryterm=db_real_escape($_REQUEST['q'],false);
        $qwhere.=" AND ticket.`number` LIKE '$queryterm%'";
    } else {//Deep search!
        $queryterm=db_real_escape($_REQUEST['q'],false); //escape the term ONLY...no quotes.
        $qwhere.=' AND ( '
                ." cdata.subject LIKE '%$queryterm%'"
                ." OR thread.body LIKE '%$queryterm%'"
                .' ) ';
        $deep_search=true;
        //Joins needed for search
        $qfrom.=' LEFT JOIN '.TICKET_THREAD_TABLE.' thread ON ('
               .'ticket.ticket_id=thread.ticket_id AND thread.thread_type IN ("M","R"))';
    }
}

**Comment by markus4000** [comment]
in v1.9.8 still a bug.

**Comment by markus4000** [comment]
File include/client/ticket.inc.php line 74

**Comment by harrisyn** [comment]
Modified the query to include the Queryterm in mine

**Comment by greezybacon** [comment]
@harrisyn isn't this stil an unresolved issue?
