### ISSUE TITLE
ost 1.9.7 - jquery causing 302 redirect (and solution)

### ISSUE THREAD

**Issue by mkaatman** [osTicket/osTicket-1.8#2002]
I had an odd situation after an upgrade where there was a call to /support/scp/ajax.php/support/scp/ from jquery-1.8.3. Ultimately this was causing a 302 redirect to our custom 404 page. (The 302 was probably due to our apache config.) Only it was in an infinite loop making the call over and over.

Simply upgrading jquery seemed to fix the issue completely. I'm still testing for other consequences.

````
<!--<script type="text/javascript" src="<?php echo ROOT_PATH; ?>js/jquery-1.8.3.min.js?4be5782"></script>-->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
````

Files affected were /support/include/staff/header.inc.php, /support/include/staff/login.header.php

**Comment by mkaatman** [comment]
jQuery 1.11.2 worked because javascript errors are being thrown. Oops. I'll look into fixing them. One of them is the use of .live which was deprecated in 1.7 and removed some release after.

**Comment by mkaatman** [comment]
Migrate plugin in conjunction with 1.11.2, seems to fix both issues.
````<script src="/js/lib/jquery/jquery-migrate-1.2.1.min.js"></script>````

**Comment by mkaatman** [comment]
Alright this issue can be closed as an id10t error. Our apache config had:
````RedirectMatch \/config\/(.*)$ /404error.php````

Which doesn't work so well when osticket is calling:
````/support/scp/ajax.php/config/scp````

**Comment by greezybacon** [comment]
@mkaatman sounds good. Please reopen if the issue persists
