### ISSUE TITLE
osTicket making Apache crash

### ISSUE THREAD

**Issue by jfha73** [osTicket/osTicket-1.8#2008]
I have osTicket installed on a server with multiple vhosts configured, all vhosts work just fine, except for osTicket, it makes Apache crash with this eror:

Faulting application name: httpd.exe, version: 2.4.12.0, time stamp: 0x54c8e2ca
Faulting module name: php_mbstring.dll, version: 5.6.8.0, time stamp: 0x552ee59b
Exception code: 0xc0000005
Fault offset: 0x0000000000003e7b
Faulting process id: 0x15b8
Faulting application start time: 0x01d07ecabe2e5163
Faulting application path: D:\Apache24\bin\httpd.exe
Faulting module path: D:\PHP\ext\php_mbstring.dll
Report Id: 229e1ab7-eabe-11e4-afe1-00155d003b04

I opened a bug with PHP and they said this:

I don't think there's something to do about this right now, maybe trying to upgrade to PCRE 8.37 . But I guess it's a good thing anyway anyway to file a ticket for osTicket

You can get more info at:

https://bugs.php.net/bug.php?id=69528

Thanks.

**Comment by greezybacon** [comment]
@jfha73 you could also try disabling the `mbstring` extension for PHP

**Comment by jfha73** [comment]
No can do, I have a Drupal site on the same server and Drupal needs mbstring.

**Comment by jfha73** [comment]
Also, I just noticed that I posted this issue in osTicket 1.8 when it should have been 1.9.7, can you move it?

Thanks.

**Comment by infectormp** [comment]
<Directory "/var/www/xxx">
<IfModule mod_php5.c>
php_admin_value mbstring.func_overload 0
</IfModule>
</Directory>

or something like this

**Comment by jfha73** [comment]
I changed that to

    <IfModule php5_module>

Because this is on Windows and it still crashed.

**Comment by infectormp** [comment]
can you provide phpinfo output?

**Comment by jfha73** [comment]
This is what shows for mbstring in phpinfo.
![osticket_mbstring](https://cloud.githubusercontent.com/assets/534716/7478285/ac90b930-f327-11e4-8b2a-d5bd3745531c.jpg)

**Comment by jfha73** [comment]
I also noticed that mbstring.func_overload is set to 0 by default, so there is no change with setting it to 0 in that directory.

**Comment by infectormp** [comment]
what value of pcre.recursion_limit you have?

**Comment by jfha73** [comment]
100000

**Comment by infectormp** [comment]
are you try increase the stack size for your Apache binary as recomend for you @ bugs.php.net?

**Comment by jfha73** [comment]
I doubled it, it worked fine for a few clicks, but after that it crashed again.

**Comment by jfha73** [comment]
FYI:

As a test I doubled the stack size to 256M and added a 0 to the recursion limit and still happening.

**Comment by infectormp** [comment]
use linux :) work perfectly

**Comment by jfha73** [comment]
I wish, I love Linux, but my boss doesn't.

**Comment by Chefkeks** [comment]
@jfha73
I know it's kinda sad but that statement just made my day :D

**Comment by jfha73** [comment]
Hey guys,

Is anybody working on this?

I noticed a newer version of OsTicket, downloaded it, uploaded it to the server and it still crashes my apache, which tells me no changes have been done to make it work.

Not just for me, but for all those who might have the same configuration that I have and would like to use your product.

Thanks.

**Comment by greezybacon** [comment]
@jfha73 how can I help? Apache is crashing because of a flaw or incompatibility of `mbstring` which is outside the development of a PHP application...

**Comment by jfha73** [comment]
I have another PHP application that uses mbstring and it doesn't crash with this other one, it only does with osTicket and even PHP ran a test and osTicket had problems on their end too.

I'm just trying to make it work for us, but if this is not solved, we can't use it.

**Comment by greezybacon** [comment]
@jfha73 have you tried hosting with IIS? I recommend using it on Windows over the `<opinion>`*convoluted*`</opinion>` WAMP stack. You can download PHP for IIS using the Windows platform installer and there's a PHP manager for IIS which makes editing the config possible inside the IIS administrator.

**Comment by jfha73** [comment]
No, I decided not to use OSTicket.
