### ISSUE TITLE
Feature request: Make the title and text on index.php editable from admin side

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#2010]
A new idea is make the text in index.php editable from admin side.

![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/7472266/ff3b8ada-f330-11e4-8e36-c6bbc0b9669d.png)

Also because in the Italian language for example this is not translated.. and maybe user want custom message.. so can also put service message like temporary problem in bold with HTML editor integrated.

**Comment by ntozier** [comment]
Admin panel -> Manage -> Page -> Landing?

**Comment by PeopleInside** [comment]
Ops correct :D
Aw sorry :S :D
