### ISSUE TITLE
everytime create new form field in custom form always error

### ISSUE THREAD

**Issue by juraganerka** [osTicket/osTicket-1.8#2011]
Can anyone help me?every time create new form field i just got an errors.
this not happen before,and i don't change any file.It's like fresh installment .
last month i create new form field and everything is fine.
![image](https://cloud.githubusercontent.com/assets/11436336/7486190/ab83ab98-f3cb-11e4-9ef8-eae0e65f3b4d.png)

**Comment by mfelber** [comment]
This looks for me like a question for the normal forum of osticket: http://osticket.com/forum/. Nevertheless: The reason why this is not successful you can see in your screenshot. Each variable name must be unique, you try to use multiple times the name "test" and therefore you get these validation errors. Use for every field a different variable name.

**Comment by juraganerka** [comment]
thanks for your suggestion.
now, why field from new form cannot insert into database.
it shows null.

**Comment by mfelber** [comment]
I think the forum is a better place to ask those questions first. You should also divide different topics to different forum threads so it is easier to follow. A Screenshot would be a good idea to understand your issue. In this case I don't really understand what you mean. You try to create a field called "why" via the gui and you get a red error message like above with the content "cannot insert into database"?
