### ISSUE TITLE
Value from custom form contact information cannot insert to database table

### ISSUE THREAD

**Issue by juraganerka** [osTicket/osTicket-1.8#2013]
i create a new form field to contact information.but when i insert a value to that field,it's not insert value to database.i try to create a new field to ticket information,nothing errors and value from that field can insert to database.

**Comment by greezybacon** [comment]
Can you supply a more detailed description of what you did? I'm getting lost at "insert into the database"

**Comment by juraganerka** [comment]
okay..
1.i create a new custom form field in contact information.i made it as required field.
2.user create ticket as usual and fill in form contact information included that i made before.
3.usually everything field from contact information form create as user information.
4.but strangely new custom form field value not insert to form_entry_values table in osticket database.
5.of course that value not showing in user contact information.

**Comment by juraganerka** [comment]
okay..
1.i create new custom form in contact information
2.user create ticket as usual and fill contact information form.
3.when waiting for creating ticket there is no error from system.
4.usually everything that we fill in contact information will show in user information,but strangely value new field that i made before not show.
5.i check in form_entry_value table from database,value from custom field doesn't exist.

**Comment by greezybacon** [comment]
@juraganerka were you able to address the issue? Is it still a problem?
