### ISSUE TITLE
On open.php with ANdroid mobile is impossibile to write a message into Issue Details with Firefox

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#2016]
With the mobile Firefox on Android is not possible to write text into Issue Details.
Maybe is a Firefox BUG?

https://webcompat.com/issues/1059

**Comment by ntozier** [comment]
I've never had a problem with this with other browsers on Android.  
Sounds like a problem with the browser to me.  I'll install it and give it a test.

**Comment by ntozier** [comment]
I am unable to confirm this issue. (see screen shot below)

![screenshot_2015-05-07-09-43-46](https://cloud.githubusercontent.com/assets/1315768/7516509/ea8109e4-f49d-11e4-9eba-416c93a6132d.png)

**Comment by PeopleInside** [comment]
Thank you for let me know,
please try to open that link with Firefox in Android mobile
https://demos6.softaculous.com/osTicket/open.php

and try to write.

or also here:
https://www.peopleinside.it/liveticket/open.php

are now able to reproduce?

**Comment by ntozier** [comment]
I uninstalled FF after testing.

**Comment by PeopleInside** [comment]
Is a Firefox bug I think si I can close the issue.
