### ISSUE TITLE
table refers not clear on

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket-1.8#2026]
i post here due in forum the response are too vage

i found some tables, the most notable  Table ost_email_account always empty, its for what?

there's more in table "ost_user" there's a field "default_email_id" and the "id", and then in "ost_user_email" theres a field "user_id" .. 

the user_id its related to id of ost_user or default_email_id of ost_user?

i changed the id of user, and the user_id of email and leave and arbirtary data in the default_email_id and seem that last field are not used? or for what its used?

i want to write a plguin integration with roundcube but the documentation about how system work are /dev/null ! and i need easy to implement documentation or references to manipulate the database!

**Comment by greezybacon** [comment]
The data model allows a user to have multiple email addresses, but the user interface does not. %user_email_address points to %user to allow the multiple relationship. A user has a default email address (out of the many associated). Therefore the %user also points to one of the entries in the %user_email_address table

**Comment by mckaygerhard** [comment]
err i loss? if the ui interface does not support, and seems those fields are for a long time there..
currently are usefully, i mean if one user has two emails, the backend does send to both a message of notification..

another question (tis kind of questions only has proper reponse here, n at forum due skill need)
how can i insert a new user? (user, not agent), i try but seem the tables relationship are redundant!, in which order? 

i try to avoid to use the ldap integration.. due in my company the fault tolerant are a man requisite.. every system must still work after a fault of another...

**Comment by ntozier** [comment]
Q: err i loss?
A: Not sure what you mean.

Q: how can i insert a new user?
A: I presume you mean via mysql query or your own script?
You make a record in ost_user
note the id.
You then make a record in ost_user_account. 
use the id you noted as the user_id.
You then mane a record in the ost_user_email table.
use the id you noted as the user_id.
note the id here we need to use it, and go back to the ost_user table.
update the default_email_id with the id you just noted.

Q: i try to avoid to use the ldap integration.. due in my company the fault tolerant are a man requisite.. every system must still work after a fault of another...
A: You do realize that if you used LDAP you would have dual fail over right?  It would try LDAP and if LDAP failed would then use local auth?

**Comment by mckaygerhard** [comment]
yes, i noted now into osticket theres a feature that users can use any backend for authentications... 

and yes again via SQL due u noted i talking about the DB tables..

so then i combined both the internal and the ldap, but for creation we have a own database integrated with a payroll and POS systems, that does not support LDAP..

so now i'll test the recomendations u make me to create users via SQL and post feedback here...

**Comment by mckaygerhard** [comment]
now i have some problems, after several investigations, i cannot see why theres a column in staff table named "show_assigned_tickets" and "default_signature_type"

for what are used that columns?, the default_signature_type columns seems are refers to that the sifnature must be depaertament, group or user .. but i never see in my sistem that values on that column changes per users.. only per global instalation!!

**Comment by mckaygerhard** [comment]
I made a query for that.. but the documentation are still missing, there no wiki for that, there's no developer wiki or info for made plugins or artifacts for osticket by thirtparty developers:

https://groups.google.com/d/msg/venenuxmassenkoh/qe88Y7h-3Nc/iXOH7_rKgS8J

Of course, in spanish only.. due missing interes in made documentation ..

For those interesting i'll made more documentation around osticket but in spanish...

**Comment by mckaygerhard** [comment]
I update the info: now fixed the querys and documented more:

https://groups.google.com/d/msg/venenuxsarisari/qe88Y7h-3Nc/P7R5Nr6mslsJ

**Comment by mckaygerhard** [comment]
how to remove normal users: https://groups.google.com/d/msg/venenuxmassenkoh/R1QLRpi1mIc/lHJYfQdQfQgJ and documented.

**Comment by ntozier** [comment]
link leads to a private group.

**Comment by mckaygerhard** [comment]
yeah.. theres no still wiki or documentatio about the api or the tables.. i really angry about htat. so i made the job.. but os-team are "too busy" in more more "features" ...

**Comment by ntozier** [comment]
Notice to all: The link in this thread is to a private group that has been setup for and by forum user who is not associated with the osTicket development team.
