### ISSUE TITLE
Feature request: Responsive Theme

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#2030]
Mobile device some times are more than PC use in this modern time so.. consider to implement a responsive design.

The best will be let admin choose if stay on current theme who is good or new HTML 5 responsive look.
In the settings once implemented will be two themes, one the current and other one new responsive theme.

Actually there are some not official work but not free.

**Comment by ntozier** [comment]
duplicate request.
https://github.com/osTicket/osTicket-1.8/issues/6
https://github.com/osTicket/osTicket-1.8/issues/490
