### ISSUE TITLE
fatal error creating departments

### ISSUE THREAD

**Issue by ralph3991** [osTicket/osTicket-1.8#2044]
## Error 1

Fatal error: Call to a member function getId() on a non-object in /var/www/osticket/include/staff/departments.inc.php on line 73

## Error 2

Fatal error: Call to a member function getEmail() on a non-object in /var/www/osticket/include/class.staff.php on line 721

**Comment by ntozier** [comment]
Version of osTicket?
What Environment? (Windows?  Linux? Apache?  IIS?)
Version of PHP?
What steps can be taken to replicate this issue?

**Comment by ralph3991** [comment]
I cloned develop repo yesterday.

Linux CentOS 7 

PHP 5

Just installed and tried to create departments

**Comment by Chefkeks** [comment]
Please download the latest version from osTicket.com/download and test it again. Cloning the repo is surely possible, but not recommended for productive environments.

**Comment by infectormp** [comment]
i create deps on clear 1.9.7 and 1.9.7 with all new commits and no have any problem

**Comment by ralph3991** [comment]
I installed stable 1.9.7 and it works. I guess the issue is in the development version

**Comment by greezybacon** [comment]
I made a fresh install from the `develop` branch and am able to create departments. @ralph3991 is there anything else you did to cause the crash?

**Comment by ralph3991** [comment]
I only cloned and installed the `develop` branch, following the installation instructions. After that, I went to create departments then received the errors. I did not bother reinstalling develop branch and just went to 1.9.7 and the issue was fixed.
