### ISSUE TITLE
namespaces...

### ISSUE THREAD

**Issue by berezuev** [osTicket/osTicket-1.8#2048]
Is there plan to add a namespaces to classes? 

I can't implement osticket to the existing project, because of classname conflicts...
"**PHP Fatal error:  Cannot redeclare class a in...**"

Thanks

**Comment by berezuev** [comment]
http://www.php-fig.org/psr/psr-4/

**Comment by greezybacon** [comment]
This is planned for the osTicket 2.0 project

**Comment by berezuev** [comment]
Nice. May be you know, when approximately you'll release it? Thx

**Comment by greezybacon** [comment]
Probably second quarter 2016

**Comment by berezuev** [comment]
ok.. thanks...
