### ISSUE TITLE
File Uploads / Attachmens

### ISSUE THREAD

**Issue by de4niih** [osTicket/osTicket-1.8#2054]
Actually my issue was: 
IOException: Unable to read resource content

I tried a lot to get rid of it, because it made nearly all attachments not readable.
Maybe I did something wrong during the update from 194 to 197.

Anyways. I've now deleted all tables in file, ticket_attachment, and file_chunk.
This removed all attachments from the tickets, but fixed my issue.

**Comment by de4niih** [comment]
I have no idea why and how. But I downloaded the osTicket version 1.8.git and uploaded it to my current installation. After refreshing the site and trying to attach new images, it worked now as desired. Without any errors in osTicked or error.log.

There is on thing left.
Lets say I have a image named screenshot01.png and I upload it as attachment and click on open / reply.

Later then, I'm renaming this file localy on my PC, lets say to screen01.png and upload it again to a ticket, osTicket renames it to screenshot01.png again.

**Comment by greezybacon** [comment]
> ticket_attachment

What version of osTicket are you using?

**Comment by de4niih** [comment]
@greezybacon 
At this Time its 1.9.7
![screenshot-2015-05-13 21-17-11](https://cloud.githubusercontent.com/assets/11258944/7618932/b9216886-f9b5-11e4-9523-4f0390775a74.png)
![screenshot-2015-05-13 21-17-49](https://cloud.githubusercontent.com/assets/11258944/7618931/b9205aae-f9b5-11e4-86b2-42647195d2e7.png)

**Comment by greezybacon** [comment]
> I tried a lot to get rid of it, because it made nearly all attachments not readable.

The error means that that the attachment content is not readable. Are you using the filesystem plugin? Did you change the permissions on the folder where the attachment files are located?

**Comment by de4niih** [comment]
Previously I was on osTicket v. 1.9.4 with the filesystem plugin and everythingt was working very well for me. Inkl. the fileattachments.

The I've updated to 1.9.7 and everytime I've added an attachment, (Images, PDF,) and clicked on reply / open it gave me a white page with the message File not found, using the back button in the Browser showed me that an attachment is available, but clicking on it forwarded me also to the white page with file not found.

I haven’t changed the file permissions, I just went through the CSS and added my own customisations and uploaded the new osticket version to the server. And from this point adding an attachment wasn’t working. Also available attachments in closed tickets had the same behaviour.

So I check out the SQL DB and deleted all the entries in the above tables. This removed all attachments from closed tickets, but now I`m able to add attachments again to messages.

**Comment by de4niih** [comment]
I also noticed, and this is still the case, that when files will be renamed and re-uploaded to the a ticket, they get the old name.

Lets say I have a file called Test001.pdf an I upload it to a ticket.
Later that day, I rename Test001.pdf to, lets say, ImportantAccountInfo.pdf and upload it to the ticket, it'll be renamed to Test001.pdf again by osTicket.

I think this is due to the signature a file gets when its being uploaded the first time. Im not sure if this is useful, because I sometimes like to rename files depending on the client or person who receives it.

Sorry for all the typos. English is not my native language.

**Comment by greezybacon** [comment]
@de4niih I agree the file reduplication can be confusing. We are hoping to allow varying names for the same content in v1.10

**Comment by de4niih** [comment]
That would be awesome.

**Comment by greezybacon** [comment]
@de4niih this is implemented in #2079
