### ISSUE TITLE
Where is form for making canned response? Knowledge base doesn't work either

### ISSUE THREAD

**Issue by ralph3991** [osTicket/osTicket-1.8#2055]
How do I create canned responses? Also the knowledge base doesn't provide any information about "canned responses".

**Comment by de4niih** [comment]
@ralph3991 
there you go from the Agents Panel => 
![new-blank](https://cloud.githubusercontent.com/assets/11258944/7619355/71a369f2-f9b8-11e4-9b60-0e6b75f259a2.png)

**Comment by ralph3991** [comment]
I Don't have that 

![screenshot from 2015-05-13 15-47-44](https://cloud.githubusercontent.com/assets/8491687/7619539/70c0f080-f987-11e4-8e5d-c63ab1a139c6.png)

**Comment by ntozier** [comment]
Then your account does not have the privileges to do it.
Go to Admin panel -> Agents -> Groups -> Your accounts Group.

**Comment by ralph3991** [comment]
It's not there I will post a screenshot

**Comment by ralph3991** [comment]
Thank you @ntozier
