### ISSUE TITLE
Profile update error. Try correcting the errors below and try again!

### ISSUE THREAD

**Issue by skubla** [osTicket/osTicket-1.8#2059]
System Settings and Preferences - osTicket (v1.9.8)

Profile update error. Try correcting the errors below and try again!
Valid email is required
![2015-05-14_062207](https://cloud.githubusercontent.com/assets/8791966/7626063/a5af4e5c-fa01-11e4-85a1-76c0bafad9e0.jpg)

Where is the problem ?

**Comment by skubla** [comment]
System Settings and Preferences - osTicket (v1.9.8)

**Comment by infectormp** [comment]
I think this related to new feature of 1.9.8 - Email domain validation includes DNS record verification

**Comment by infectormp** [comment]
as temp solution you can downgrade to 1.9.7

**Comment by skubla** [comment]
This is the problem "Email domain validation includes DNS record verification (#2042)"

**Comment by greezybacon** [comment]
@skubla it looks like `vszp.sk` is a valid email domain. Do you not have DNS set up on your osTicket http server?

**Comment by greezybacon** [comment]
Can anyone try this code to see if it addresses the issue?
```patch
diff --git a/include/class.validator.php b/include/class.validator.php
index fcb3501..f812aae 100644
--- a/include/class.validator.php
+++ b/include/class.validator.php
@@ -156,8 +156,12 @@ class Validator {
                 return false;
         }

-        if ($verify && !checkdnsrr($m->host, 'MX'))
-            return false;
+        // According to RFC2821, the domain (A record) can be treated as an
+        // MX if no MX records exist for the domain. Also, include a
+        // full-stop trailing char so that the default domain of the server
+        // is not added automatically
+        if ($verify and !count(dns_get_record($m->host.'.', DNS_MX)))
+            return 0 < count(dns_get_record($m->host.'.', DNS_A|DNS_AAAA));

         return true;
     }
```

**Comment by mfelber** [comment]
Hmm, I tried to reproduce this issue with the actual version from 1.9.8 at osticket.com/download but this problem doesn't occurs. I have used the same email address. Does it require some special conditions?

**Comment by greezybacon** [comment]
@skubla can you confirm any of these?:
* You use Active Directory
* You have an Exchange server
* `vszp.sk` is an internet routable email domain, hosted internally
* Your AD DNS servers (internal) have neither MX records nor A nor AAAA records for `vszp.sk`

**Comment by infectormp** [comment]
I try add info@svzp.sk at my instalation and get "Enter a valid email address". With new code from greezybacon i get same error.
I check svzp.sk, this domain not have mx,ns,a or aaaa records.

In this situation would be best solution make email domain validation as option in osTicket.

**Comment by greezybacon** [comment]
@infectormp it's vszp.sk

**Comment by infectormp** [comment]
damn, then i just make a little test for new future :D

**Comment by greezybacon** [comment]
@infectormp I agree with you, though. I changed the `develop` branch to include an option to disable the feature. We'll make a hotfix release next week

**Comment by Chefkeks** [comment]
@greezybacon +1 for hotfix release

**Comment by skubla** [comment]
It'll be fine. I look forward to upgrade ... "We'll make a hotfix release next week".
ThnX @infectormp

**Comment by skubla** [comment]
Add option (osTicket Core, v1.9.8.1) to disable email address verification solves this problem.
=== Enhancements
  * Add option to disable email address verification
ThnX
