### ISSUE TITLE
Q: Ticket API

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2062]
We write script to migrate tickets from spiceworks to osticket via API and want set agent and internal note on ticket import is this possible make via osticket API?

**Comment by infectormp** [comment]
nevermind

**Comment by greezybacon** [comment]
> nevermind

? Sorry if my delayed response was frustrating. The short answer is no, it's not currently possible

**Comment by infectormp** [comment]
@greezybacon thank you, we found another solution. We run sql update after import data.

**Comment by philbertphotos** [comment]
@infectormp can you share the sql updata... I am also working on a way to import the data.

**Comment by infectormp** [comment]
@philbertphotos sorry this update is not saved.
