### ISSUE TITLE
dpr: Default Time Zone Auto Detect

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2064]
How this work? In my installation Time Zone detected incorrectly.
In php.ini i use correct timezone

**Comment by infectormp** [comment]
Detected Asia / Baghdad must be Europe / Moscow

**Comment by ntozier** [comment]
I'm not real sure that I understand what your question actually is...
You didn't include version of osTicket.
You didn't relay what you expected to see vs what you do see.

**Comment by infectormp** [comment]
@ntozier version included in topic "dpr:"

**Comment by ntozier** [comment]
You didn't relay what you expected to see vs what you do see.

**Comment by greezybacon** [comment]
The software uses [jstz](http://pellepim.bitbucket.org/jstz/) to provide timezone selection. You can report a bug on their site. However, according this [this site](http://www.zeitverschiebung.net/en/difference/timezone/europe--moscow/timezone/asia--baghdad), they seem compatible

**Comment by infectormp** [comment]
Ok, i read about jstz and this situation described in limitation section. No question more.
