### ISSUE TITLE
dpr: sql errors

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2066]
v1.10-dpr-6-g3e4b685

Go to Agent Panel -> Dashboard

[SELECT T1.name,
                COUNT(*)-COUNT(NULLIF(A1.state, "created")) AS Opened,
                COUNT(*)-COUNT(NULLIF(A1.state, "assigned")) AS Assigned,
                COUNT(*)-COUNT(NULLIF(A1.state, "overdue")) AS Overdue,
                COUNT(*)-COUNT(NULLIF(A1.state, "closed")) AS Closed,
                COUNT(*)-COUNT(NULLIF(A1.state, "reopened")) AS Reopened
            FROM ost_department T1
                LEFT JOIN ost_ticket_event A1
                    ON (A1.id=T1.id
                         AND NOT annulled
                         AND (A1.timestamp BETWEEN FROM_UNIXTIME(1429082663) AND FROM_UNIXTIME(1431674663)))
                LEFT JOIN ost_staff S1 ON (S1.staff_id=A1.staff_id)
            WHERE T1.id IN (1,2,3)
            GROUP BY T1.id
            ORDER BY T1.name]

Unknown column 'A1.id' in 'on clause'<br /> <br />

[SELECT T1.name,
                FORMAT(AVG(DATEDIFF(T2.closed, T2.created)),1) AS ServiceTime
            FROM ost_department T1
                LEFT JOIN ost_ticket T2 ON (T2.id=T1.id)
                LEFT JOIN ost_staff S1 ON (S1.staff_id=T2.staff_id)
            WHERE T1.id IN (1,2,3) AND T2.closed BETWEEN FROM_UNIXTIME(1429082663) AND FROM_UNIXTIME(1431674663)
            GROUP BY T1.id
            ORDER BY T1.name]

Unknown column 'T2.id' in 'on clause'<br /> <br />

[SELECT T1.name,
                FORMAT(AVG(DATEDIFF(B2.created, B1.created)),1) AS ResponseTime
            FROM ost_department T1
                LEFT JOIN ost_ticket T2 ON (T2.id=T1.id)
                LEFT JOIN ost_thread B0 ON (B0.object_id=T2.ticket_id
                    AND B0.object_type="T")
                LEFT JOIN ost_thread_entry B2 ON (B2.thread_id = B0.id
                    AND B2.`type`="R")
                LEFT JOIN ost_thread_entry B1 ON (B2.pid = B1.id)
                LEFT JOIN ost_staff S1 ON (S1.staff_id=B2.staff_id)
            WHERE T1.id IN (1,2,3) AND B1.created BETWEEN FROM_UNIXTIME(1429082663) AND FROM_UNIXTIME(1431674663)
            GROUP BY T1.id
            ORDER BY T1.name]

Unknown column 'T2.id' in 'on clause'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054', '[SELECT T1.name...')<br />
#1 (root)/include/ajax.reports.php(129): db_query('SELECT T1.name,...')<br />
#2 (root)/include/ajax.reports.php(155): OverviewReportAjaxAPI->getData()<br />
#3 [internal function]: OverviewReportAjaxAPI->getTabularData()<br />
#4 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#5 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('table', Array)<br />
#6 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('table', Array)<br />
#7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/report/overvie...', NULL)<br />
#8 (root)/scp/ajax.php(232): Dispatcher->resolve('/report/overvie...')<br />
#9 {main}

**Comment by mfelber** [comment]
@infectormp Do you mean the "System Logs" under ->Admin Panel->Dashboard? I had seen the same errors there yesterday with the github version (not sure if it was already the fixed version). Now I'm using the actual Download from osticket.com/download. In this version I don't get this database errors yet. Maybe this version is better. Also it is more transparent in non github versions which build you are using (->Admin Panel->Dashboard-> Information). In my case for example: osTicket Version v1.10-dpr-6-g3e4b685 (3e4b685).

**Comment by infectormp** [comment]
@mfelber n i mean Go to Agent Panel -> Dashboard and get this errors

**Comment by mfelber** [comment]
@infectormp Now I'm getting the same errors in my version. I have navigated through the system, made some changes and no db errors weren't shown there firstly. But now these errors are displayed in the system logs. So the delay has "tricked" me. By the way, I was a little bit confused why you find the "System Log" errors in the Agent Panel, maybe this screenshot helps to understand why:

![db errors](https://cloud.githubusercontent.com/assets/5539456/7649573/75aa14e2-faee-11e4-8e57-7c53f5edb4ab.jpg)

**Comment by infectormp** [comment]
@mfelber i get this error when Go to Agent Panel -> Dashboard. In Adimn Panel -> Dashboard -> System Logs you can see this errors.

**Comment by mfelber** [comment]
@infectormp Ok, now I understand you and I can confirm this triggers the db errors. Sorry for the confusion. Could be related to the outstanding stabilizing work step 9 for develop-next "Dashboard statistics crash": https://github.com/osTicket/osTicket-1.8/pull/2056

**Comment by infectormp** [comment]
In RC1 fixed
