### ISSUE TITLE
dpr: roles: All Access

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2067]
default instalation - role All Access nave not checked: Tickets:Edit Thread, Knowledgebase:Premade, Miscellaneous:Stats

**Comment by ntozier** [comment]
This is not a bug?  This is how a default install has had the admin group configured has been since those features were added.  

It was also discussed that "Tickets:Edit Thread" would be admin only by default.  Regular staff probably should not have the power to edit tickets.

**Comment by infectormp** [comment]
@ntozier - I know about this.

But in role description i read - Role with unlimited access. In role permissions i see not all permissions was set and for me this is limited access. If this is not a bug i close ticket.

**Comment by infectormp** [comment]
In RC1 fixed
