### ISSUE TITLE
v1.10-dpr-6-g3e4b685 (3e4b685) - System Settings and Preferences - advanced date and time format

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#2077]
When you switch to the advanced date and time format, you will see only placeholders in the different osticket areas:
![screenshot 1](https://cloud.githubusercontent.com/assets/5539456/7665782/e4e7eca6-fbc7-11e4-8a11-f949a2999f69.jpg)

![screenshot 2](https://cloud.githubusercontent.com/assets/5539456/7665783/e4e91f4a-fbc7-11e4-8d5b-3137a5ff4452.jpeg)

![screenshot 3](https://cloud.githubusercontent.com/assets/5539456/7665786/e54b72f8-fbc7-11e4-93ba-a485e3f29eab.jpeg)

![screenshot 4](https://cloud.githubusercontent.com/assets/5539456/7665787/e554b21e-fbc7-11e4-8c1a-3b27e3b14528.jpeg)

![screenshot 5](https://cloud.githubusercontent.com/assets/5539456/7665785/e54a5df0-fbc7-11e4-98e5-512b2ccd3a1b.jpeg)

![screenshot 6](https://cloud.githubusercontent.com/assets/5539456/7665784/e4eb91a8-fbc7-11e4-9399-1a366b0370f9.jpeg)

I haven't seen this in the outstanding list for stabilizing 1.10 #2056, so maybe it is interesting for you.

**Comment by greezybacon** [comment]
@mfelber can you see if this is fixed in the tip of the `issue/next-stabilize` branch or with the patch in a4e688d30da658cf55590e04bfd9fc7f78f5bf7a?

**Comment by mfelber** [comment]
@greezybacon Yes it is :-)
