### ISSUE TITLE
dpr: Back to previous page

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2080]
Open scp/emails open any email for edit press back button in browser. You will stay on same page.  

Browser console show error:
TypeError: redactor.destroy is not a function1 redactor-osticket.js:345:16

Reproduced not only at scp/emails page.

**Comment by greezybacon** [comment]
@infectormp thanks for the report. I have this written up in the #2056 outstanding as * PJAX back navigation doesn't seem to work well*
