### ISSUE TITLE
Ticket list is empty in 1.10

### ISSUE THREAD

**Issue by Ali-Se** [osTicket/osTicket-1.8#2082]
After updating to 1.10 the ticket list is display empty (or actually does not displayed at all as shown in the attached image.
![ticket-list](https://cloud.githubusercontent.com/assets/9544911/7678618/ac03f15a-fd66-11e4-9a56-d7d4b55727a5.png)

**Comment by ntozier** [comment]
Please see: https://github.com/osTicket/osTicket-1.8/issues/2078

**Comment by greezybacon** [comment]
@Ali-Se what version did you upgrade from?

**Comment by Ali-Se** [comment]
From 1.9.6

**Comment by Hannibal226** [comment]
I had exactly the same problem and thought I already asked in #2078, but seems like I didn't sent the post o.O

So I also tried the thing with adding the line what was mentioned in #2078, but couldn't figure it out. Also I'm not sure if this really is the same problem, as the guys there always talking about "while" installation. 
No real statement about an empty ticket list like here, or? 

So maybe same reason, but wanted to let u know that here's one more with this kind of bug after upgrade. 

CHEERS and thank for ur hard work!

**Comment by Ali-Se** [comment]
Actually there was some DB Errors mentioning some missing fields from some tables (all are 'id') and I add them all, and now there is no DB Errors, but the problem was not solved, and still getting the same output.

**Comment by mfelber** [comment]
I think that has something to do with the status lists.

I upgraded 1.9.5.1 with 1.10 for test purposes and the same issue occurred: ticket list is empty. 

Error log shows this:

[Tue May 19 14:42:29 2015] [error] [client 192.168.223.66] PHP Fatal error:  Uncaught exception 'ObjectNotUnique' with message 'One object was expected; however multiple objects in the database matched the query. In fact, there are 2 matching objects.' in /opt/bitnami/apache2/htdocs/osticket-1951/include/class.orm.php:943\nStack trace:\n#0 /opt/bitnami/apache2/htdocs/osticket-1951/include/class.orm.php(380): QuerySet->one()\n#1 /opt/bitnami/apache2/htdocs/osticket-1951/include/class.list.php(435): VerySimpleModel::lookup(Array)\n#2 /opt/bitnami/apache2/htdocs/osticket-1951/include/class.list.php(919): DynamicList::lookup(Array)\n#3 /opt/bitnami/apache2/htdocs/osticket-1951/include/staff/templates/status-options.tmpl.php(24): TicketStatusList::getStatuses(Array)\n#4 /opt/bitnami/apache2/htdocs/osticket-1951/include/class.list.php(1356): include('/opt/bitnami/ap...')\n#5 /opt/bitnami/apache2/htdocs/osticket-1951/include/staff/tickets.inc.php(351): TicketStatus::status_options()\n#6 /opt/bitnami/apache2/htdocs/osticket-1951/scp/tickets.php(549): require_once('/opt/bitnami/ap...')\n#7 {main}\n  thr in /opt/bitnami/apache2/htdocs/osticket-1951/include/class.orm.php on line 943, referer: http://192.168.223.63/osticket-1951/scp/index.php

The ticket status exists twice after upgrade, you can't delete them via gui:
![screenshot status](https://cloud.githubusercontent.com/assets/5539456/7703252/f63d9b88-fe36-11e4-9686-a51340a14b09.JPG)

 When you delete one of the status lists via database access the ticket list is showing the tickets.

**Comment by greezybacon** [comment]
@mfelber That makes sense. I've seen that in a upgrade to 1.10

**Comment by Ali-Se** [comment]
I deleted the extra record and list is now displayed correctly, thanks @mfelber

**Comment by greezybacon** [comment]
This was officially fixed in 833e4e4bfa582689af0d7b5575dc3e3875113ea7
