### ISSUE TITLE
Ticket import API: Encoding

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2084]
1.9.8

When we try import data from sqlite db to osticket via API in html format we get text in cyrillic look like that
![image](https://cloud.githubusercontent.com/assets/9958813/7682171/bd4829c8-fd7e-11e4-9539-ba2eccde3bda.png)

After our investigation we make some code modification in class.api.php
in class ApiJsonDataParse we replace this 
```$data = Format::parseRfc2397($value, 'utf-8');```

to this 
```$data = Format::parseRfc2397($value, 'utf-8', false);```

and get right result (readable cyrillic text)
![image](https://cloud.githubusercontent.com/assets/9958813/7682338/05b02854-fd80-11e4-8a02-c48be217f06f.png)

**Comment by greezybacon** [comment]
@infectormp could you post an example API request. It looks like you are not declaring a charset in the request

**Comment by infectormp** [comment]
API request
```'message'   =>     "data:text/html," .$row['description'].  $mess_comments, ```

we try add enoding but not have any good result

**Comment by infectormp** [comment]
@greezybacon now i try again and this work without code modification.
```'message'   =>     "data:text/html;charset=utf-8," .$row['description'].  $mess_comments,```
