### ISSUE TITLE
Advanced Search bug

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket-1.8#2088]
This behavior has been noted in both the 1.9.6 and 1.9.8 versions and can be replicated by
1: use the advanced search option,
2: select a start date and an end date.
3: Execute the search and then view the tickets
4: Results would narrow down the tickets to range of tickets found according to pagination.
5: Repeat the same steps with the same date range
6: clicking the returned ticket found count, to view them will result in all tickets being listed and not filtered down or affected by the search. 
The Token in the URL will remain the same as in the previous search but results wouldnt be as expected.

Performing a search with a different date range, will initially return the expected results but when used again will not.

I am not sure if this pertains to my environment but I have tested in both versions and found this to be the case, if anyone to try to replicate this and feedback, I'd be grateful.

**Comment by harrisyn** [comment]
Anyone tried this yet?

**Comment by greezybacon** [comment]
Advanced search is rewritten in develop-next to address these inconsistency issues
