### ISSUE TITLE
Request: Dashboard Search

### ISSUE THREAD

**Issue by harrisyn** [osTicket/osTicket-1.8#2089]
I do find it a bit inconvenient to filter the results of the dashboard using an initial date and then some human styled text end date i.e. "up to today". 

I think it would be easier if we had the option to select a calendar end date or an option between both types.

**Comment by kordianbruck** [comment]
@harrisyn you can select a start and end date, I don't get what the suggestion is?

**Comment by harrisyn** [comment]
No you can't, I am talking about the dashboard page and not advanced search. 
http://baudlabs.com/wp-content/uploads/osticket_dashboard.png

**Comment by kordianbruck** [comment]
Ahh, sorry. I assumed you meant the advanced search
