### ISSUE TITLE
dpr: PHP Fatal error: Call to a member function getId()

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2102]
PHP Fatal error:  Call to a member function getId() on
 null in /xxx/include/staff/faq-view.inc.php on line 10, referer: https://xxx/scp/faq.php?cid=1&a=add

**Comment by greezybacon** [comment]
A picture is worth a thousand words... Just sayin'

**Comment by infectormp** [comment]
Look like it was i delete example ticket from osTicket Support user.

Yes found it. Get same error when try create ticket with osTicket Support user.

**Comment by infectormp** [comment]
I can't reproduce it yet

**Comment by infectormp** [comment]
Get it. When add FAQ do not fill Question filed and you get this error.

**Comment by infectormp** [comment]
fixed
