### ISSUE TITLE
dpr: different console errors

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2103]
When open https://xxx/scp/login.php
* login.php:15 Uncaught ReferenceError: $ is not defined
* https://xxx/js/jquery-1.8.3.min.js  [404 Not Found]

When press [edit] in ticket 
* TypeError: $(...).sortable is not a function  tickets.php:237:0

When add note to organization
* Error: No such method "focus" for Redactor jquery-1.11.2.min.js:2:1808

**Comment by greezybacon** [comment]
Can you retry at the tip of the branch in #2056? I think these things have been addressed

**Comment by infectormp** [comment]
sure

**Comment by infectormp** [comment]
> TypeError: $(...).sortable is not a function tickets.php:237:0

fixed

**Comment by infectormp** [comment]
fixed
