### ISSUE TITLE
dpr: delete ticket: PHP Fatal error

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2105]
When try delete ticket from ticket view
```PHP Fatal error:  Call to a member function getName()
on boolean in /xxx/include/staff/ticket-view.inc.php on line 246, referer: https://xxx/scp/users.php?id=1```

**Comment by greezybacon** [comment]
Works fine for me. What am I missing?

**Comment by infectormp** [comment]
Look like it was when i delete example ticket from osTicket Support user.

Yes found it. Get same error when try create ticket with osTicket Support user.

**Comment by infectormp** [comment]
fixed in last branch
