### ISSUE TITLE
dpr: dialogs mis sized

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2109]
dialogs mis sized in FF developer edition 40.0a2
![image](https://cloud.githubusercontent.com/assets/9958813/7766363/20e72ea8-0071-11e5-9f48-fc9821555666.png)

**Comment by greezybacon** [comment]
Sorry to be a noob... What's wrong with this picture?

**Comment by ntozier** [comment]
Maybe he's saying that "Create New Organization: Details on user organization" should be on one line?

**Comment by infectormp** [comment]
here is normal gialog from chrome

![image](https://cloud.githubusercontent.com/assets/9958813/7777067/8d5431ec-00c8-11e5-9e75-e03709ea7764.png)

**Comment by infectormp** [comment]
hehe :) no buttons

**Comment by ntozier** [comment]
can't you use the scroll bar (1st image) to scroll down and see the buttons?

**Comment by infectormp** [comment]
@ntozier yes i can. But only in FF DE in chrome no scroll and no buttons

**Comment by greezybacon** [comment]
@infectormp I think that would be a Chrome bug. I'll do some more testing

**Comment by infectormp** [comment]
I use Chrome 43

**Comment by infectormp** [comment]
fixed in current branch but now no caption and tooltip look poorly
![image](https://cloud.githubusercontent.com/assets/9958813/7784440/24925660-016e-11e5-9f92-0e0efb3e280c.png)

**Comment by greezybacon** [comment]
I found this to be a problem. I'm still working on a solution

**Comment by infectormp** [comment]
This is mass problem?
![image](https://cloud.githubusercontent.com/assets/9958813/7785545/1e9e822c-019d-11e5-95a1-d5d7165ac345.png)

**Comment by greezybacon** [comment]
I think this is fixed now in #2056. There was a bug with the `.slideDown` usage in the dialog code

**Comment by infectormp** [comment]
fixed
