### ISSUE TITLE
dpr: Edit Ticket Thread

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2110]
I success edit message about ticket status changes ```Status changed from Open to Resolve by Agent```. This is not very good because this is system message.

I think problem is here - author of this message agent that changed status of ticket but this is not right, author of this message must be SYSTEM. Because SYSTEM say ```Status changed from Open to Resolve by Agent``` not agent.

**Comment by greezybacon** [comment]
This is addressed in #2058

**Comment by infectormp** [comment]
I see, thank you.
