### ISSUE TITLE
OsTicket 1.9.8.1 not sending any emails

### ISSUE THREAD

**Issue by aribenda** [osTicket/osTicket-1.8#2119]
Hi, 
I set up Osticket on a Linux server. 

Everything works fine on the web but I don't get any emails from the system. 
Not for alerts, assignments or anything else.

I did set up 3 SMTP emails with the correct server info, and they work fine when sending tests from the diagnostic tab on email settings

Any help will be greatly appreciated.

![screen shot 2015-05-28 at 4 00 27 pm](https://cloud.githubusercontent.com/assets/12649286/7869745/c570ffc2-0552-11e5-9c7d-137b1e25dab0.png)
![screen shot 2015-05-28 at 4 00 18 pm](https://cloud.githubusercontent.com/assets/12649286/7869746/c5837bac-0552-11e5-82e0-1e1ced37df52.png)

**Comment by infectormp** [comment]
did you check server logs?

**Comment by aribenda** [comment]
the ones in dashboard - system logs, you mean? 
There is nothing related showing there...

**Comment by infectormp** [comment]
what SMTP server do you use? postfix\senmail?

**Comment by infectormp** [comment]
i mean web server\mail server logs

**Comment by aribenda** [comment]
I use Microsoft SMTPSVC(7.5.7601.17514) on a different server. 
I have to see the logs over there, but diagnostic emails are sent fine from OSticket.

Will check it and get back with the info, thanks a lot for your help

**Comment by aribenda** [comment]
These are some of the logs, I see there is activity, but the emails don't get send out. 
But when trying it in the diagnostics tab it does send them.
Thanks for you help!


![screen shot 2015-05-29 at 1 44 55 pm](https://cloud.githubusercontent.com/assets/12649286/7888779/f4d2e8be-0608-11e5-8539-944b7c662e05.png)

**Comment by ntozier** [comment]
a smtp response code of 250 is "Okay" or "Requested mail action okay,
completed".
That means to me that the mail was accepted by the mail server.

**Comment by greezybacon** [comment]
Are the emails being flagged as SPAM perhaps by the server?

**Comment by aribenda** [comment]
no, not really. 
we ended up setting up another SMTP server on the same box so we don't have to deal with the Windows one. 
Thanks for you help!
