### ISSUE TITLE
Can't save multiple form fields at once

### ISSUE THREAD

**Issue by Remo** [osTicket/osTicket-1.8#2133]
This code fails in the `develop` branch, but works in `master`:

```php
$data = [
   'name' => 'Name',
   'email' => 'mail@domain.tld',
   'phone' => 123,
   'notes' => 'notes',
];
$user = User::fromVars($data, true);
```

Only the phone number will be saved, the notes will be ignored. Tried to go through the code, but things are pretty messy and hard to read. I might have another look later but maybe there's someone who's more experienced with osticket.

**Comment by ntozier** [comment]
This appears to be a duplicate issue of https://github.com/osTicket/osTicket-1.8/issues/2123

**Comment by Remo** [comment]
jup
