### ISSUE TITLE
Translation cache not updated

### ISSUE THREAD

**Issue by gtulga** [osTicket/osTicket-1.8#2136]
Hi,

I downloaded and extracted Mongolian language phar to v1.9.8.1. It works great. But I need change some words. Then I did following steps:

1. Downloaded po file from crowdin.
2. Edited po file on poedit app
3. Poedit exported messages.mo file
4. Copied messages.mo to server
5. Run "php include/class.translation.php messages.mo > messages.mo.php"
6. Copied messages.mo.php to include/i18n/mn_MN/LC_Messages/messages.mo.php
7. Refresh system, but nothing changed. Still original Mongolian texts.

I hope this file include translation of navigation menu. Right? or only messages part?

How to change navigation menu names?

Thanks,

**Comment by infectormp** [comment]
You need try restart http server.

**Comment by gtulga** [comment]
Thanks, it worked!

**Comment by warapongkusungnoen** [comment]
can i edit string in message.mo.php directly

**Comment by ntozier** [comment]
@warapongkusungnoen this is open source, you can edit anything that you want to edit.

PHP.net Phar documentation.
http://php.net/manual/en/book.phar.php
