### ISSUE TITLE
 PHP Strict Standards:  Non-static method osTicket::is_cli() should not be called statically in include/class.osticket.php on line 402

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#2163]
I continue to receve this error when cron do.

PHP Strict Standards: Non-static method osTicket::is_cli() should not be called statically in include/class.osticket.php

What is and what can i do for fix?

**Comment by ntozier** [comment]
This isn't an error?  
Its a Strict Standards notice.
You can suppress this by changing your logging level in your php.ini.

**Comment by PeopleInside** [comment]
If i set on PHP Display error off this should solve?

**Comment by ntozier** [comment]
No you would alter the error_reporting directive in your php.ini.
Since I don't know what it looks like now I cannot really tell you what to change it to exactly.
Generally you would add & ~E_STRICT to the end and remove any other reference to E_STRICT.
