### ISSUE TITLE
1.9.8 Search: how to search

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#2167]
Hello,
i was wondering if there are some tricks to find things.
in V1.8x it was possible to use %xxxx% and other SQL Tricks to find tickets very quick... but since 1.9.8 I'm not able to find things at all.... I know the star, but its not as good as the % was.

e.g. I have a ticket with subject: ACT flooder
I search for ACT, I serach for ACT*, I search for *ACT*
Hits: O

e.g2 I have a ticket with subject: citymuseum
I search for *museum, or museum: no hit

Tricks and hints are very very welcome!

**Comment by ntozier** [comment]
Please see:
http://osticket.com/forum/discussion/80538/advanced-search-not-working-wtih-4-characters-or-less

**Comment by markus4000** [comment]
Thanx. Solved.
