### ISSUE TITLE
1.10 DB Error

### ISSUE THREAD

**Issue by adegidio** [osTicket/osTicket-1.8#2194]
I am receiving these errors in System Logs:
[SELECT T1.name, FORMAT(AVG(DATEDIFF(B2.created, B1.created)), 1) AS ResponseTime FROM ost_department T1 LEFT JOIN ost_ticket T2 ON (T2.id=T1.id) LEFT JOIN ost_thread B0 ON (B0.object_id=T2.ticket_id AND B0.object_type="T") LEFT JOIN ost_thread_entry B2 ON (B2.thread_id = B0.id AND B2.`type`="R") LEFT JOIN ost_thread_entry B1 ON (B2.pid = B1.id) LEFT JOIN ost_staff S1 ON (S1.staff_id=B2.staff_id) WHERE T1.id IN (4) AND B1.created BETWEEN FROM_UNIXTIME(1432667187) AND FROM_UNIXTIME(1435345587) GROUP BY T1.id ORDER BY T1.name] Unknown column 'T2.id' in 'on clause'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054', '[SELECT T1.name...')
 #1 (root)/include/ajax.reports.php(129): db_query('SELECT T1.name, ...')
 #2 (root)/include/ajax.reports.php(155): OverviewReportAjaxAPI->getData()
 #3 [internal function]: OverviewReportAjaxAPI->getTabularData()
 #4 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
 #5 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('table', Array)
 #6 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('table', Array)
 #7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/report/overvie...', NULL)
 #8 (root)/scp/ajax.php(232): Dispatcher->resolve('/report/overvie...')
 #9 {main}

**Comment by protich** [comment]
This was addressed in PR #2179

**Comment by adegidio** [comment]
Thanks!!

**Comment by adegidio** [comment]
Hello, I've updated ajax.reports.php as reported in PR #2179 but now I am receving this error:
[SELECT 'open', count(task.id ) AS tasks FROM ost_task task WHERE task.flags & 1 != 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND task.flags & 1 != 0 ) OR task.dept_id IN(4) ) UNION SELECT 'overdue', count( task.id ) AS tasks FROM ost_task task WHERE task.flags & 1 != 0 AND task.flags & 2 != 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND task.flags & 1 != 0 ) OR task.dept_id IN(4) ) UNION SELECT 'assigned', count( task.id ) AS tasks FROM ost_task task WHERE task.flags & 1 != 0 AND task.staff_id = 2 AND ( (task.staff_id=2 AND task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND task.flags & 1 != 0 ) OR task.dept_id IN(4) ) UNION SELECT 'closed', count( task.id ) AS tasks FROM ost_task task WHERE task.flags & 1 = 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND task.flags & 1 != 0 ) OR task.dept_id IN(4) ) ] Unknown column 'flags.team_id' in 'where clause'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054', '[SELECT 'open', ...')
 #1 (root)/include/class.task.php(700): db_query('SELECT 'open', ...')
 #2 (root)/include/class.staff.php(495): Task::getStaffStats(Object(StaffSession))
 #3 (root)/scp/tasks.php(81): Staff->getTasksStats()
 #4 {main}

**Comment by ntozier** [comment]
'flags.te am_id'

Do you actually have a space in the code?
because I would think that should be team_id.  Not te am.id.

**Comment by adegidio** [comment]
Hello,

I'm sorry for the delay.

I dind't understand, what do you mean "with space in the code"? You mean if
I have access to the code in our server? If you ask that, yes, but I don't
understand what you suggest that I should modify.

I'm actually receiving this DB errors:

DB Error #1146:
[SELECT T1.name, COUNT(*)-COUNT(NULLIF(A1.state, "created")) AS Opened,
COUNT(*)-COUNT(NULLIF(A1.state, "assigned")) AS Assigned,
COUNT(*)-COUNT(NULLIF(A1.state, "overdue")) AS Overdue,
COUNT(*)-COUNT(NULLIF(A1.state, "closed")) AS Closed,
COUNT(*)-COUNT(NULLIF(A1.state, "reopened")) AS Reopened FROM
ost_department T1 LEFT JOIN THREAD_EVENT_TABLE A1 ON (A1.dept_id=T1.id AND
NOT annulled AND (A1.timestamp BETWEEN FROM_UNIXTIME(1432993574) AND
FROM_UNIXTIME(1435671974))) LEFT JOIN ost_staff S1 ON
(S1.staff_id=A1.staff_id) WHERE T1.id IN (4) GROUP BY T1.id ORDER BY
T1.name] *Table 'osticket.THREAD_EVENT_TABLE' doesn't exist*

---- Backtrace ----
#0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1146',
'[SELECT T1.name...')
#1 (root)/include/ajax.reports.php(117): db_query('SELECT T1.name, ...')
#2 (root)/include/ajax.reports.php(142): OverviewReportAjaxAPI->getData()
#3 [internal function]: OverviewReportAjaxAPI->getTabularData()
#4 (root)/include/class.dispatcher.php(145): call_user_func_array(Array,
Array)
#5 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('table',
Array)
#6 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('table',
Array)
#7 (root)/include/class.dispatcher.php(38):
UrlMatcher->dispatch('/report/overvie...', NULL)
#8 (root)/scp/ajax.php(232): Dispatcher->resolve('/report/overvie...')
#9 {main}

DB Error #1054:
[SELECT 'open', count(task.id ) AS tasks FROM ost_task task WHERE
task.flags & 1 != 0 AND ( (task.staff_id=2 AND task.flags & 1 != 0 ) OR (
flags.team_id IN(2) AND task.flags & 1 != 0 ) OR task.dept_id IN(4) ) UNION
SELECT 'overdue', count( task.id ) AS tasks FROM ost_task task WHERE
task.flags & 1 != 0 AND task.flags & 2 != 0 AND ( (task.staff_id=2 AND
task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND task.flags & 1 != 0 ) OR
task.dept_id IN(4) ) UNION SELECT 'assigned', count( task.id ) AS tasks
FROM ost_task task WHERE task.flags & 1 != 0 AND task.staff_id = 2 AND (
(task.staff_id=2 AND task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND
task.flags & 1 != 0 ) OR task.dept_id IN(4) ) UNION SELECT 'closed', count(
task.id ) AS tasks FROM ost_task task WHERE task.flags & 1 = 0 AND (
(task.staff_id=2 AND task.flags & 1 != 0 ) OR ( flags.team_id IN(2) AND
task.flags & 1 != 0 ) OR task.dept_id IN(4) ) ] *Unknown column
'flags.team_id*' in 'where clause'

---- Backtrace ----
#0 (root)/include/mysqli.php(183): osTicket->logDBError('DB Error #1054',
'[SELECT 'open', ...')
#1 (root)/include/class.task.php(700): db_query('SELECT 'open', ...')
#2 (root)/include/class.staff.php(495):
Task::getStaffStats(Object(StaffSession))
#3 (root)/scp/tasks.php(81): Staff->getTasksStats()
#4 {main}



2015-06-29 15:38 GMT-03:00 ntozier <notifications@github.com>:

**Comment by ntozier** [comment]
I meant this:

![capture](https://cloud.githubusercontent.com/assets/1315768/8432861/865c0a5c-1f10-11e5-9821-dbfc428f5a92.PNG)

Do you have a defined THREAD_EVENT_TABLE in your bootstrap.php?

**Comment by adegidio** [comment]
Look in my last mail, there is no "space" in "te am", it is correct
"team_id". I think there was an error when I pasted it.

Also I didn't modify anything in bootstrap.php.






2015-06-30 11:16 GMT-03:00 ntozier <notifications@github.com>:
