### ISSUE TITLE
Error on creating .MANIFEST file on first deploy

### ISSUE THREAD

**Issue by msmollin** [osTicket/osTicket-1.8#2196]
Cloned the repo and checkout out the v1.9.9 tag's code. Ran the deploy command which in ubuntu 14.04 LTS looks like 

`sudo php setup/cli/manage.php deploy --setup /var/www/osticket/`

Which resulted in an error

`PHP Warning:  file_put_contents(/var/www/osticket/include//.MANIFEST): failed to open stream: No such file or directory in ~/osTicket-1.8/setup/cli/modules/deploy.php on line 99`

Running `sudo mkdir -p /var/www/osticket/include/` fixed the issue.

**Comment by greezybacon** [comment]
So it looks like the deployment is *not* creating `/var/www/osticket/` because when I arrived at the same error, the deployment system had not deployed anything

**Comment by msmollin** [comment]
Agreed. I tried it again this morning on a different system and noticed the same - it seems like for whatever reason that's the first line that actually hits the bug, but really it seems to be affecting the entire deployment. It could be because Ubuntu sets up /var/www/ as owned by root, and running php as "sudo" might not be working correctly. I wound up just using the tar.gz archive you can get from github, but I can bring up an additional machine for more testing if needed.

**Comment by greezybacon** [comment]
@msmollin could you try the patch in #2199 to see if it addresses the issue?
