### ISSUE TITLE
1.10 export tickets with custom fields

### ISSUE THREAD

**Issue by zizackov** [osTicket/osTicket-1.8#2197]
when adding a custom field to the ticket details when you try to export the ticket list it's not working. when you delete the custom field it's working again.

**Comment by greezybacon** [comment]
@zizackov could you provide some screenshots and perhaps example exports so I could see what you're seeing?

**Comment by zizackov** [comment]
Hi
i tried to recreate this problem again, but it seems to be working now with no errors, it must have been something specific in my environment 
thank you and i am sorry.

**Comment by nicklayb** [comment]
I have the same problem, on two different system. Bascillay I have 2 fields ( a short answer, and a choice) but only the short answer outputs on the CSV. I can see the header of the choice but not the content

![image](https://cloud.githubusercontent.com/assets/15114240/22598607/075f0524-ea02-11e6-9c4d-a18a1be44b12.png)

![image](https://cloud.githubusercontent.com/assets/15114240/22598660/2a5c0946-ea02-11e6-8615-d7cc7ce8b1d6.png)

![image](https://cloud.githubusercontent.com/assets/15114240/22598626/11e9491e-ea02-11e6-94fb-abc2daa54621.png)


I've looked in the tickets and I can see that the fields are really filled

**Comment by boschnathan** [comment]
hi guys,

this is my first time with osticket.
I have the same issue: custom fields does not show in export.

here is what i did.

1. create custom form with fields then link it to the help topics.
2. create a ticket and fill out the custom fields.
3. ticket created and closed.
4. export the closed ticket but the fields are not included on the report.

Kindly help me with my issue.
osticket version 1.10

**Comment by boschnathan** [comment]
i think it is not related to issues #2383 because what i wanted is to add the custom fields to the exported csv file. note that the export function is working but it gives me the standard data only and it does not include the custom fields. 

I posted on this issue because i have seen on the above screenshot by nicklayb that on his excel his custom fields are included on the report. i want to know how he do that.

thank you guys.. i just need help with this.

**Comment by balojs** [comment]
#3705

**Comment by alwaysbadboy** [comment]
Dear All, 
I have a similar problem (v1.10), but a bit tricky.
When i only have one custom data, lets say DATA-A in ticket form, it works fine and can be exported to CSV.
I added in one more custom data, lets say DATA-B, and after that DATA-A can't to export to CSV. 
But the DATA-A which were created before DATA-B added into ticket form are still able to export to CSV.
I logged into the database, the both DATA-A and B are there. 
Any idea where is wrong ?
Thanks

**Comment by C-Nedelcu** [comment]
hello,

I have explained the problem in great detail on the forums before being directed here:
http://osticket.com/forum/discussion/90582/exporting-list-of-tickets-has-my-custom-field-but-all-values-are-blank

as far as I know this issue is not solved yet
