### ISSUE TITLE
Tickets imported from email have system email set as "sender"

### ISSUE THREAD

**Issue by paugre** [osTicket/osTicket-1.8#2202]
Hi!
So, I'm having a problem since my last upgrade. Incoming tickets that are created via email (e.g imported via IMAP) are in osTicket listed as sent from the email address they are imported from (support@mydomain.com) instead of the original sender. Is this a configuration problem or could it be a bug introduced with the newer version? I would appreciate any help as my support system is currently not usable.

Paul

**Comment by ntozier** [comment]
What version of osTicket are you running?
Are you forwarding the emails to the support address?
Do you have any filters?

**Comment by paugre** [comment]
It's the latest version from git (v1.9.9-4-g69f801b) but I've tracked the issue down to somewhere else in my costumer support system (my web front end seems to report the wrong customer address). So I would say it is not related to osTicket after all.
