### ISSUE TITLE
Bounce mail detection improvement - delivery address restricted

### ISSUE THREAD

**Issue by ArthurBorsboom** [osTicket/osTicket-1.8#2213]
Some customers add internal mailing groups in the CC field to inform their colleagues when creating a support ticket. Each response to the ticket by the ticket agent results in a bounce mail which is added to the ticket. It becomes a mess.

An anonymized example of the bounced mail:
http://pastebin.com/E0GbbMMA

What is the best way to prevent this to happen?

**Comment by ntozier** [comment]
In no particular order:

Handle this at your email server (by stripping CCs on emails to that mail box)
Add a ticket filter that blocks those lists.
Inform customers not to do that.
make customers use the ui to open tickets.
uncheck: Admin panel -> Settings -> Tickets -> Accept Email Collaborators
No idea if this would do it but Add a ticket filter target channel:email with: Use Reply-To Email.

**Comment by ArthurBorsboom** [comment]
1. Handle this at your email server (by stripping CCs on emails to that mail box)

Good suggestion, but not an option, since it is an external hosted mail solution

2. Add a ticket filter that blocks those lists. No idea if this would do it but Add a ticket filter target channel:email with: Use Reply-To Email.

Sounds like a good solution. I have blocked mails from the postmaster@domain.com
I will monitor if this prevents the bounce mails to be added to the ticket.

3. Inform customers not to do that.

Tried it, but they don't want to.

4. make customers use the ui to open tickets.

Tried it, they prefer email.

5. uncheck: Admin panel -> Settings -> Tickets -> Accept Email Collaborators

Good suggestion, however I do like the collaborator functionality.

Thanks for thinking along. I will report back within 1 or 2 weeks.

**Comment by greezybacon** [comment]
We also support email address blacklisting via Admin -> Email -> Banlist, which may be simpler to manage than the filters.

**Comment by ArthurBorsboom** [comment]
Nice one,

With this workaround I at least prevent the bounced mail to be added as a new post to the ticket.

Maybe it is an option to have a blacklist for collaborators?

**Comment by ntozier** [comment]
Why would you want a separate banlist?  [ie what use case do you envision needing a second one ban list]

**Comment by ArthurBorsboom** [comment]
I want osTicket to prevent adding the problematic mail address to the
participants list in the first place.

This way osTicket will not send an email message to a mail address, which
is certain to return a bounce mail.
And then osTicket does not have to block this bounced mail.

So, it saves osTicket the load of sending, receiving and blocking.

On 6 July 2015 at 14:59, ntozier <notifications@github.com> wrote:

> Why would you want a separate banlist? [ie what use case do you envision
> needing a second one ban list]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/2213#issuecomment-118848008>
> .
>



-- 
Arthur Borsboom
Lieven de Keystraat 77
3067 KG, Rotterdam
The Netherlands
Mob: +31629089953
Email: arthurborsboom@gmail.com
Skype: Arthur Borsboom, The Hague, The Netherlands

[image: View Arthur's LinkedIn profile]
<http://uk.linkedin.com/in/arthurborsboom>

**Comment by greezybacon** [comment]
I think when we read bounce emails in osticket, we should mark the corresponding failed recipient email addresses as bounced / invalid and no longer send email to them

**Comment by ArthurBorsboom** [comment]
That sounds like a good solution!

On 8 July 2015 at 05:29, Jared Hancock <notifications@github.com> wrote:

> I think when we read bounce emails in osticket, we should mark the
> corresponding failed recipient email addresses as bounced / invalid and no
> longer send email to them
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/2213#issuecomment-119411060>
> .
>



-- 
Arthur Borsboom
Lieven de Keystraat 77
3067 KG, Rotterdam
The Netherlands
Mob: +31629089953
Email: arthurborsboom@gmail.com
Skype: Arthur Borsboom, The Hague, The Netherlands

[image: View Arthur's LinkedIn profile]
<http://uk.linkedin.com/in/arthurborsboom>

**Comment by ArthurBorsboom** [comment]
Offered solution works well.
