### ISSUE TITLE
1.9.9: Search by ticket number

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2214]
When i search ticket by number ```497955-AIS``` in result set i get more then 1 ticket.

![image](https://cloud.githubusercontent.com/assets/9958813/8487419/a99e3b24-2114-11e5-8a10-750e15743671.png)

**Comment by infectormp** [comment]
If i search ticket only by number without -AIS search return only 1 result, as expected.

**Comment by greezybacon** [comment]
Currently, we only do search on ticket number if the search term is purely numeric

**Comment by infectormp** [comment]
strange, i create ticket via API with number 273814-SW and if i search ticket by number 273814-SW i get 1 ticket in result but if i use number 497955-AIS i get random result

**Comment by infectormp** [comment]
look like i understand. I read about MATCH … AGAINST contrustion.

**Comment by infectormp** [comment]
If use 497955AIS as number (without dash) search will return 1 row. So best solution for custom number use number without dash or similar symbols.
