### ISSUE TITLE
Feature request: regex support in Reply Separator Tag

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2216]
Would be nice add ability use regex expression in Reply Separator Tag

**Comment by greezybacon** [comment]
Nope. The reply tag is actually placed in the text of outbound emails. So it can't be a regex. However, we need to change the detection system to use regex and support varying whitespace in the token when processing incoming email

**Comment by infectormp** [comment]
Let me explain why i ask about this feature. 2 days ago we migrate from spiceworks to osticket and in spiceworks we can use regex in Reply Separator Tag this allow strip not only previous message from response but user signature and mail header too. Using regex can remove 10-15 line unneeded text from user reply.

**Comment by Chefkeks** [comment]
@greezybacon
In my opinion it would be nice to have two separate settings - one for the reply separator tag which got added to outgoing emails and there other one - maybe a list (with regex capabilities) - to cut unnecessary lines from incoming email replies.

**Comment by infectormp** [comment]
here is example, if use regexp osticket can strip this block from reply, about 20 lines

![image](https://cloud.githubusercontent.com/assets/9958813/8504226/20435d06-21d6-11e5-9730-11b42a732de1.png)

**Comment by infectormp** [comment]
Reading long thread will be more comfortable
