### ISSUE TITLE
Recipient ticket link gets changed when inserted into database

### ISSUE THREAD

**Issue by Boduje** [osTicket/osTicket-1.8#2219]
Using: osTicket (v1.9.9-1-gbe2f138)

A lot of people are having problems with the %{recipient.ticket_link}.  I think I have found the problem, at least on my end.

When I edit a mail template using the <> and enclose the %{recipient.ticket_link} within an href tag, the brackets are converted to hexadecimal equivalent upon inserting the template into the database table.  Doing so breaks the template, causing the link to not work.

After manually editing the template in the table using phpMyAdmin and putting the brackets back in, the link works in the e-mail.

What needs to be changed to prevent the conversion on INSERT?

**Comment by C4RLOCO** [comment]
This issue is being adressed on a different post: https://github.com/osTicket/osTicket-1.8/issues/2201

**Comment by Boduje** [comment]
Thanks, C4RLOCO!  I must have glanced over it in the issues list.

Mods, please delete this thread.
