### ISSUE TITLE
1.9.9: Images in message count like attachment

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2222]
I have ticket from user where i see only 1 image in message body (user sign) and no other attachment but in ticket list i see attachment pic. Image in ticket count like ticket attachment.

**Comment by ntozier** [comment]
Yes, embedded images are counted as attachments.... because they are attachments.

**Comment by infectormp** [comment]
I not this so. Embedded images cannot be deleted as regular attachment. I think they must not count as attachment

**Comment by ntozier** [comment]
So that is really not how email works.
It's either attached [embedded], or its linked.

**Comment by infectormp** [comment]
If i open email with embedded images in outlook i not see eny attachments. But why in osticket i see embedded images like attachments?

**Comment by infectormp** [comment]
I have no complaints if ostiсket consider all embedded images as attachments, but do not count them as an attachment in ticket list. This confuses.

**Comment by mckaygerhard** [comment]
all embebed files are attachments if u read email documents rfc's

outlook its a mocosoft product and always wants redefined all.. 

for a image must be embebed, must be includen in the email object message.. so its attachment ... so this ticket its invalid..

**Comment by infectormp** [comment]
i like rfc, but i think embebed emages not need count like attachment, this confuses staff when he open ticket and not see attachments.

**Comment by mckaygerhard** [comment]
@infectormp but its supposes staff are trained.. and are not end-users.. so maybe that u said its valid for end users, but for staff.. please.

that u said are same ***as does mocosoft... trying to "re-define" only just to please , cause more problems now today that end-users are thinking administrators, damaging the system and minimizing the work of real programmers***

**Comment by greezybacon** [comment]
This is definitely fixed in v1.10. I'm sorry I keep saying that, but that's what I've been focusing development on for the past months

**Comment by infectormp** [comment]
@greezybacon thank you.
