### ISSUE TITLE
SQL Errors 1.10

### ISSUE THREAD

**Issue by AlexYoung28** [osTicket/osTicket-1.8#2247]
Hi,

Just done the latest commit update and it's coming up 

( ! ) Warning: Missing argument 2 for QuerySet::toSql(), called in C:\Web Server\wamp\www\osticket2\include\class.orm.php(1236) : eval()'d code on line 12 and defined in C:\Web Server\wamp\www\osticket2\include\class.orm.php on line 1081
Call Stack
#	Time	Memory	Function	Location
1	0.0015	467352	{main}( )	..\tickets.php:0
2	0.1874	17826696	require_once( 'C:\Web Server\wamp\www\osticket2\include\staff\tickets.inc.php' )	..\tickets.php:539
3	0.2303	18889288	ResultSet->valid( )	..\tickets.php:442
4	0.2303	18889456	HashArrayIterator->fillTo( )	..\class.orm.php:1301
5	0.2303	18889552	ResultSet->prime( )	..\class.orm.php:1509
6	0.2303	18889552	QuerySet->getQuery( )	..\class.orm.php:1276
7	0.2304	18892664	MySqlCompiler->compileSelect( )	..\class.orm.php:1208
8	0.2304	18893912	MySqlCompiler->getWhereHavingClause( )	..\class.orm.php:2327
9	0.2304	18893912	SqlCompiler->compileConstraints( )	..\class.orm.php:2289
10	0.2304	18894328	SqlCompiler->compileQ( )	..\class.orm.php:2017
11	0.2304	18894680	call_user_func:{C:\Web Server\wamp\www\osticket2\include\class.orm.php:2000} ( )	..\class.orm.php:2000
12	0.2305	18894720	MySqlCompiler->__in( )	..\class.orm.php:2000
13	0.2306	18909096	SqlCompiler->pushJoin( )	..\class.orm.php:2161
14	0.2306	18909784	MySqlCompiler->compileJoin( )	..\class.orm.php:1939
15	0.2307	18912032	QueryView000000003085e27f00000000ab11e0c0::getSqlAddParams( )	..\class.orm.php:2232
16	0.2307	18912096	QuerySet->toSql( )	..\class.orm.php(1236) : eval()'d code:12

I've reversed the changes and it goes back working and upgrade and same issue occurs.

I'm running on latest WAMP Server.

**Comment by AlexYoung28** [comment]
sorry this is when i'm looking at the queue.

**Comment by greezybacon** [comment]
I fixed this today. Sorry for the confusion
