### ISSUE TITLE
1.10 Task change status to closed doesn't change status

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket-1.8#2253]
When changing the status at the 

bottom of the task it will not update:

![image](https://cloud.githubusercontent.com/assets/12860950/8679862/e95a9d90-2a22-11e5-9ad9-f2679fb179c4.png)

After post:

![image](https://cloud.githubusercontent.com/assets/12860950/8679874/0294c600-2a23-11e5-8a65-384ebe4eade2.png)

You can still check the task and close it via the "Change Status"

![image](https://cloud.githubusercontent.com/assets/12860950/8679899/39a41628-2a23-11e5-80fa-235b769168c0.png)

**Comment by infectormp** [comment]
Alredy posted here https://github.com/osTicket/osTicket-1.8/pull/2056#issuecomment-108551641

**Comment by kest874** [comment]
This is fixed.
