### ISSUE TITLE
Feature Request: Ticket view refresh after deleting or changing status

### ISSUE THREAD

**Issue by colonelpopcorn** [osTicket/osTicket-1.8#2257]
When I submit status changes, I want those changes to be reflected immediately upon reload so that I can immediately see where things stack up compared to other tickets.

An example: we've added a ranking system that allows us to prioritize tickets automatically based on certain criteria. However, whenever we change the status (one of our criteria) on the tickets page we have to reload the page to see those changes reflected in our sorting. This new feature would facilitate the ability to change many different properties of multiple tickets all without having to click on each individual ticket.

**Comment by ntozier** [comment]
I think that you will want to submit a screen shot of what you are seeing, and what you want to see.  Because I'm not aware of any delays in tickets being updated like your message seems to infer.

**Comment by colonelpopcorn** [comment]
![osticketgithub](https://cloud.githubusercontent.com/assets/13068221/8728113/55d5b876-2bb1-11e5-9da1-58969d1c02bb.png)

This is what I mean, whenever a change is submitted I want to be able to have that reflected immediately upon chaging the status. I think my particular problem is that I want the list of tickets to be refreshed every time a change is made with the change status button.

**Comment by ntozier** [comment]
It works the way that you are describing on the open queue (I didn't test the others).
What version of osTicket are you running?

**Comment by colonelpopcorn** [comment]
We are running our own special brew and the problems we are running into are due to our ranking system not being properly integrated with the rest of the client-side scripting. In the future, I'll revert to original code when opening issues. This issue can be closed.
