### ISSUE TITLE
Broken <div>

### ISSUE THREAD

**Issue by DirectGamerHD** [osTicket/osTicket-1.8#2263]
I have a fresh, out of the box installation of osTicket that i'm configuring for a client. 

 I noticed that none of my variables for the client's name (as in ticket creator) aren't working. After looking around, I noticed that this was happening: http://i.gyazo.com/1b8427001e3078955604295bfc111a04.png

Is there a way I could fix this?

**Comment by ntozier** [comment]
1.9.9-1 was released to fix this.  But it does not retroactively go back and fix the data in your database.
If its a fresh new install I would wipe it out and reinstall with the new version.

**Comment by DirectGamerHD** [comment]
Hm, weird. If I did preform a fresh install and kept a backup of the existing data base, could I theoretically just repair data base and keep everything? I'd really hate to loose all my progress on the configuration / customization.

**Comment by ntozier** [comment]
You could back up your database, and then manually remove the div tags via a 3rd party editor pretty easily I would think.
