### ISSUE TITLE
no ticket number search as user

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2264]
Hey people

when a user's search nutz ticket, you can set it up that he is also looking ticket numbers? that seems currently not to go, but ticket only on the subject or content

**Comment by infectormp** [comment]
@oneilak Waht cersion are you use? 

search by ticket number work without any problem.

**Comment by oneilak** [comment]
hi ,

finding an agent is running smoothly, it's just not when the user login in order to track their tickets

Serverinformationen
osTicket-Version 	v1.9.9-1-gbe2f138 (be2f138)
Server-Software 	Microsoft-IIS/8.5
MySQL-Version 	5.7.7
PHP-Version 	5.4.24

**Comment by infectormp** [comment]
at user side this not supported yet

**Comment by oneilak** [comment]
In principle it would be great if that goes, if user have many tickets it is easier if you can look for the ticket number for them.


maybe this is something for the next update?

**Comment by infectormp** [comment]
The is no declaration for $queryterm when search by ticket number.

This will fix a problem

![image](https://cloud.githubusercontent.com/assets/9958813/8776329/e95a4cf2-2ef8-11e5-83ad-174f04f54fc4.png)

**Comment by greezybacon** [comment]
Good catch @infectormp

**Comment by harrisyn** [comment]
Funny I have reported this multiple times. It never got fixed in the
rollout.
Always had that fix in my version.

**Comment by greezybacon** [comment]
@harrisyn, my bad. Did you post a patch to address the issue and I missed
it?


Am Mittwoch, 22. Juli 2015 schrieb harrisyn :

> Funny I have reported this multiple times. It never got fixed in the
> rollout.
> Always had that fix in my version.
> On Jul 22, 2015 3:49 AM, "Jared Hancock" <notifications@github.com

**Comment by oneilak** [comment]
it is implemented in a future release?

**Comment by infectormp** [comment]
You can implement this in your instalation.

**Comment by harrisyn** [comment]
@greezybacon refer 
#1980

**Comment by oneilak** [comment]
Hello there,

I have installed it and it works, but if a updatet comes this file is overwritten probably yes and I would have to implement it again ?!

therefore it would be good if it is implemented in principle

**Comment by infectormp** [comment]
i think @greezybacon implement this fix to next version

**Comment by ntozier** [comment]
That would be my understanding.

**Comment by greezybacon** [comment]
Can anyone confirm the fix in #2294 addresses the issue?
