### ISSUE TITLE
URL links from default templates not rewriting to correct url

### ISSUE THREAD

**Issue by aaronbracken** [osTicket/osTicket-1.8#2266]
Running osticket - v1.9.9-1-gbe2f138  on ubuntu 

Using the default templates when i create a new support ticket, the generated email links show the url code and not the actual url. See Picture (all links are like this.)
![osticket](https://cloud.githubusercontent.com/assets/7767804/8782939/f956f0f6-2ed5-11e5-97f9-6f13fa9237e9.gif)

Note: Going to the website and requesting a login or to view ticket info by entering your email and ticket number, the generated email's links DO work just fine.

**Comment by ntozier** [comment]
Please see:
https://github.com/osTicket/osTicket-1.8/issues/2180
https://github.com/osTicket/osTicket-1.8/issues/2201
https://github.com/osTicket/osTicket-1.8/issues/2219

**Comment by aaronbracken** [comment]
Thanks for the fix! 
https://github.com/osTicket/osTicket-1.8/pull/2223 is the fix.
