### ISSUE TITLE
v1.10-rc.1 (33f18c5) cannot create a Organisation

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#2275]
Cannot add a new Organisation.
(i made a new installation, not an upgrade)

**Comment by infectormp** [comment]
any errors?

**Comment by markus4000** [comment]
No. It appears "loading" and then nothing happens.

**Comment by markus4000** [comment]
Today I tried it again.  Magic. It worked. Perhaps i forgot to clean the cache after upgrading the system.

**Comment by mfelber** [comment]
When I try to install 1.10rc1 from http://osticket.com/download I get this error: PHP Fatal error:  Call to a member function getPrimaryLanguage() on a non-object in /opt/bitnami/apache2/htdocs/osticket-rc/include/class.i18n.php on line 367\n'
