### ISSUE TITLE
1.10 rc1 : client login does not work

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#2276]
first Login works (with "create account" and then direkt link from email) 
but then after logout, a Login isn't possible:
"Valid CSRF Token Required"

**Comment by ewhptiv** [comment]
Same problem over here, upgraded from 1.9.11 to 1.10 RC1. Connection to the admin panel is working fine but not the connection to the user interface with the same error message being thrown out.

**Comment by greezybacon** [comment]
Can anyone confirm the fix in #2295?

**Comment by MauriceMohlek** [comment]
This fix is not working for me :-/
I setup a clean install with 1.10-rc1
Cant get it to work...

**Comment by greezybacon** [comment]
You said you did a clean install. Did you apply the patch I cited?

Am Samstag, 25. Juli 2015 schrieb Maurice Mohlek :

**Comment by MauriceMohlek** [comment]
stupid me -.- i forgot to upload the files .. omg

**Comment by ewhptiv** [comment]
Yes, the patch did work for me. Thanks!

**Comment by SolidK0RE** [comment]
Patch is working for me. (v1.10 RC1)

**Comment by ntozier** [comment]
Patch is working for me.

**Comment by greezybacon** [comment]
Fixed with #2295
