### ISSUE TITLE
1.10 RC1 Issues - Bad Timezone

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2277]
* Ticket Page 
   * `Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in C:\inetpub\osTicket\DPR\include\class.misc.php:72 Stack trace: #0 C:\inetpub\osTicket\DPR\include\class.misc.php(72): DateTimeZone->__construct('') #1 C:\inetpub\osTicket\DPR\include\class.format.php(484): Misc::db2gmtime('2015-07-23 08:0...') #2 C:\inetpub\osTicket\DPR\include\class.format.php(572): Format::__formatDate('2015-07-23 08:0...', '', true, 3, 3, '%x %X', 'America/New_Yor...', false) #3 C:\inetpub\osTicket\DPR\include\staff\tickets.inc.php(486): Format::datetime('2015-07-23 08:0...') #4 C:\inetpub\osTicket\DPR\scp\tickets.php(539): require_once('C:\\inetpub\\osTi...') #5 {main} thrown in C:\inetpub\osTicket\DPR\include\class.misc.php on line 72`
   * No information is listed under Subject, From, Priority, Assigned To 
   * Ticket count is 2 but is only showing 1
   * 
![image](https://cloud.githubusercontent.com/assets/5774055/8850220/37c11548-3114-11e5-9933-d0e630a42fce.png)

   * 
![image](https://cloud.githubusercontent.com/assets/5774055/8850206/1cc7f6f8-3114-11e5-8f7f-2b93f3faefab.png)

* Task Page
   * Can see create new task window but when I click create task the page will refresh and no new task is listed (admin is unable to see everything)
* System Settings
   * Unable to save, no buttons at bottom of page 
![image](https://cloud.githubusercontent.com/assets/5774055/8850230/629f0cc0-3114-11e5-89b3-78936488b862.png)

**Comment by ntozier** [comment]
Out of vague curiosity what is your PHP version, Time zone set in PHP, and timezone set in your Profile?
I see that the system default is America / New_York and am asking because of: 'Unknown or bad timezone ()'.

**Comment by jdelhome3578** [comment]
* PHP 5.5.23 on Windows
* date.timezone="America/New_York"
* set to system default

**Comment by jdelhome3578** [comment]
![image](https://cloud.githubusercontent.com/assets/5774055/8855977/0c2dedda-3136-11e5-8f6c-73b8ca8118e0.png)

**Comment by clarm060** [comment]
I having the smae issue i am also on 5.5.23 on windows
![ticket system](https://cloud.githubusercontent.com/assets/13317639/8860913/edfb06ee-3154-11e5-9441-4ad7e8a5204c.png)

**Comment by clarm060** [comment]
The funny thing is there is no PHP error just no content at all, so it may not be the same but i am unable to update the timezone as well

**Comment by jdelhome3578** [comment]
Change bootstrap.php to see errors
`        #Don't display errors
        ini_set('display_errors', '1'); // Set by installer
        ini_set('display_startup_errors', '1'); // Set by installer`

**Comment by clarm060** [comment]
Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in D:\Dev Sites\support-dev\include\class.misc.php:72 Stack trace: #0 D:\Dev Sites\support-dev\include\class.misc.php(72): DateTimeZone->__construct('') #1 D:\Dev Sites\support-dev\include\class.format.php(484): Misc::db2gmtime('2015-07-23 15:5...') #2 D:\Dev Sites\support-dev\include\class.format.php(563): Format::__formatDate('2015-07-23 15:5...', '', true, 3, -1, '%x', 'America/New_Yor...', false) #3 D:\Dev Sites\support-dev\include\staff\users.inc.php(193): Format::date('2015-07-23 15:5...') #4 D:\Dev Sites\support-dev\scp\users.php(177): require('D:\Dev Sites\su...') #5 {main} thrown in D:\Dev Sites\support-dev\include\class.misc.php on line 72

Same error

**Comment by jdelhome3578** [comment]
I think the problem is in `getDbTimezone()`

**Comment by greezybacon** [comment]
Looks like the database is reporting a timezone of `Eastern Daylight Time` and PHP does not like that as the timezone name, but `Config::getDbTimezone()` is not picking a valid replacement

**Comment by ntozier** [comment]
@greezybacon Just to add some weight to this I just upgraded my 1.10 from dpr to rc1 and I am getting this error also.

[23-Jul-2015 21:14:24 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in C:\Inetpub\wwwroot\support.110\include\class.misc.php:72

Here are my osT and PHP settings pertaining to this.
Admin panel -> Settings -> Default Time Zone: America / New_York
Profile -> Preferences -> Time Zone: America / New_York
php.ini: date.timezone=America/New_York

**Comment by infectormp** [comment]
I not have this issue
php.ini date.timezone = Europe/Moscow

**Comment by infectormp** [comment]
All people with this error use windows. I use linux. Look like it's a windows problem.

**Comment by infectormp** [comment]
Guys, can you check current time zone of MySQL?

MariaDB [(none)]> SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+

**Comment by infectormp** [comment]
Here is my system TZ settings
cat /etc/timezone
Europe/Moscow

**Comment by oneilak** [comment]
hey

I've recorded on my test system, the update for fun.
However, there are problems with the display.

I was upgraded from v 1.9.8

![2](https://cloud.githubusercontent.com/assets/13413719/8870867/8888d244-31f1-11e5-90e5-75e1fe201786.png)
![3](https://cloud.githubusercontent.com/assets/13413719/8870868/8889a584-31f1-11e5-8a9b-f0ef8649c721.png)
![4](https://cloud.githubusercontent.com/assets/13413719/8870866/88861fe0-31f1-11e5-80d7-8f197114ea7b.png)
![1](https://cloud.githubusercontent.com/assets/13413719/8870865/88833c4e-31f1-11e5-8d1e-ad92a99f502f.png)

**Comment by greezybacon** [comment]
We are actually querying `global.system_time_zone` from mysql. Can any report the output of
```sql
SELECT @@global.system_time_zone;
```

**Comment by jdelhome3578** [comment]
`Eastern Daylight Time`

**Comment by greezybacon** [comment]
Can anyone test the patch in #2297?

**Comment by jdelhome3578** [comment]
Patch in #2297 confirmed fix!!

**Comment by greezybacon** [comment]
Fixed by #2297
