### ISSUE TITLE
All Content missing from pages 

### ISSUE THREAD

**Issue by clarm060** [osTicket/osTicket-1.8#2279]
![support-issue](https://cloud.githubusercontent.com/assets/13317639/8858340/e7c30c50-3144-11e5-8854-06ff3ed98b87.png)

I have upgraded our DEV environment to 10 RC1 and now no content will display and LDAP seems to be disabled with no way to get to it to configure it. Also no Help topics, Agents, Roles, Departments will show up spite them being in the database.

This was an upgrade from 9.9.9

**Comment by clarm060** [comment]
[SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)]

Table 'support_denter_dev.ost_translation' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 D:\Dev Sites\support-dev\include\mysqli.php(318): osTicket->logDBError('DB Error #1146', '[SELECT A1.* FR...')<br />
#1 D:\Dev Sites\support-dev\include\class.orm.php(2659): db_prepare('SELECT A1.* FRO...')<br />
#2 D:\Dev Sites\support-dev\include\class.orm.php(2653): MySqlExecutor->execute()<br />
#3 D:\Dev Sites\support-dev\include\class.orm.php(2729): MySqlExecutor->_prepare()<br />
#4 D:\Dev Sites\support-dev\include\class.orm.php(1499): MySqlExecutor->getArray()<br />
#5 D:\Dev Sites\support-dev\include\class.orm.php(1322): ModelInstanceManager->fillTo(0)<br />
#6 D:\Dev Sites\support-dev\include\class.translation.php(899): ResultSet->valid()<br />
#7 D:\Dev Sites\support-dev\include\class.translation.php(920): CustomDataTranslation::getTranslation('en_US')<br />
#8 D:\Dev Sites\support-dev\include\class.dept.php(473): CustomDataTranslation::translate('7b6404e5bbc900c...')<br />
#9 D:\Dev Sites\support-dev\include\class.dept.php(491): Dept::{closure}(12, 'Area Admin Shar...')<br />
#10 D:\Dev Sites\support-dev\include\class.dept.php(510): Dept::getDepartments(Array)<br />
#11 D:\Dev Sites\support-dev\include\staff\settings-system.inc.php(53): Dept::getPublicDepartments()<br />
#12 D:\Dev Sites\support-dev\scp\settings.php(55): include_once('D:\Dev Sites\su...')<br />
#13 D:\Dev Sites\support-dev\scp\admin.php(3): require('D:\Dev Sites\su...')<br />
#14 {main}

is from the log related to it

**Comment by ntozier** [comment]
Table 'support_denter_dev.ost_translation' doesn't exist
You appear to be missing a table.
Specifically: ost_translation

**Comment by clarm060** [comment]
The interesting thing is i looked that our Production system which was a mirrored image of def pre-upgrade and it missing the table as well but doesn't seem to be affecting anything. Was this table a new addition to 10? If so if i just add it before upgrade should I be good?

**Comment by ntozier** [comment]
This should do it.  Just change %TABLE_PREFIX% to your table prefix.

DROP TABLE IF EXISTS `%TABLE_PREFIX%translation`;
CREATE TABLE `%TABLE_PREFIX%translation` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `object_hash` char(16) CHARACTER SET ascii DEFAULT NULL,
  `type` enum('phrase','article','override') DEFAULT NULL,
  `flags` int(10) unsigned NOT NULL DEFAULT '0',
  `revision` int(11) unsigned DEFAULT NULL,
  `agent_id` int(10) unsigned NOT NULL DEFAULT '0',
  `lang` varchar(16) NOT NULL DEFAULT '',
  `text` mediumtext NOT NULL,
  `source_text` text,
  `updated` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `type` (`type`,`lang`),
  KEY `object_hash` (`object_hash`)
) DEFAULT CHARSET=utf8;

**Comment by clarm060** [comment]
So that fixed my missing table, but the content still is jacked it only shows one row now. So decided to install it from scratch and same issue.
![ticket system](https://cloud.githubusercontent.com/assets/13317639/8860728/b35d970a-3153-11e5-8823-bcbf5d25aa57.png)

**Comment by clarm060** [comment]
I also made sure that all the correct PHP extensions are installed including the intl one

**Comment by clarm060** [comment]
any ideas?

**Comment by jdelhome3578** [comment]
Looks like my issue #2277

**Comment by clarm060** [comment]
Closing due to being the same issue,

**Comment by ntozier** [comment]
While I agree it could be the same, we would need the new PHP error to determine that.

**Comment by clarm060** [comment]
The funny thing is there is no PHP error just no content and nothing comes up in the log. 

Actually on my dev server this is what i have:

osTicket Version	v1.10-rc.1 (07c1d79) 
Web Server Software	Microsoft-IIS/8.0
MySQL Version	5.6.19
PHP Version	5.4.24

If you want i can re-open it to be safe :)

**Comment by clarm060** [comment]
i posted the error in the other chat as it was the same error

**Comment by greezybacon** [comment]
Looks like a failed upgrade. The upgrade should have created the table. I would try the upgrade again. Did you get any upgrade errors?

**Comment by clarm060** [comment]
This was a Fresh install after a failed upgrade. During the upgrade it was missing the search and Translation tables.

**Comment by jdelhome3578** [comment]
I would keep this open for the `[SELECT A1.* FROM ost_translation A1 WHERE (A1.lang = ? AND A1.type = ?)]` issue. This something different then the date issue.
