### ISSUE TITLE
user does not see the current department v1.9.11

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2285]
Hey everyone,

I think I've found a bug, if a user opened a ticket does not appear the right department, if the ticket is transferred to other departments. attached screens for better understanding.

by the way

it is possible (possibly in future versions) the entries in the user sees, and the editor is, who made him?

1. User Open Ticket at SD
![ticket_open_sd_viewuser](https://cloud.githubusercontent.com/assets/13413719/8870600/94531aaa-31ef-11e5-8d9c-7a0cac775bca.png)

2. Agent see the Ticket
![ticket_open_sd_viewagent](https://cloud.githubusercontent.com/assets/13413719/8870618/9f200aa6-31ef-11e5-8584-9e98751d4e28.png)

3. Agent transfer to Department "Server"
![ticket_transfer_server](https://cloud.githubusercontent.com/assets/13413719/8870630/af08241c-31ef-11e5-8e8d-2cfd4d854007.png)

4. Ticket Overview of the user with the wrong department
![ticket_transfer_server_userview](https://cloud.githubusercontent.com/assets/13413719/8870639/cafbf874-31ef-11e5-865d-9362ee9d7848.png)

5.Ticket opened in the user view with the wrong department
![ticket_transfer_server_userview1](https://cloud.githubusercontent.com/assets/13413719/8870656/eb43704e-31ef-11e5-87a5-5be0e6e14b46.png)

**Comment by protich** [comment]
Do you by any chance have "Server" department as private?

**Comment by oneilak** [comment]
ahhhh ok, what it has to when I say "private" put a division on an impact? if I put it in public it goes :-)

thank you

**Comment by protich** [comment]
Private basically means - internal department. Default department is shown to clients when a ticket is in a private department.
