### ISSUE TITLE
1.10 RC1 Issue Open new ticket

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#2287]
If I try to open a new ticket at frontend, there is after some seconds a popup I have to restore the page. I have to click ok 100 times to write again. 3 seconds later the same popup.

Log shows (5000 entries): 
Ungültiger CSRF-Token __CSRFToken__

Ungültiger CSRF-Token [8f6c258bd40d94df886ea19b8aa8edffc75f4d5e] bei http://www.service.192.168.1.35.xip.io/ajax.php/draft/2173
Log-Datum: Freitag, 24. Juli 2015 11:05 IP-Adresse: 92.xxx.xxx.xxx

**Comment by gmt-it** [comment]
Forgot to write:
This error occurs after upgrade of develop. Clean install works.

**Comment by ntozier** [comment]
"at frontend"
Do you mean the User (client) side?
Or do you mean Agent (staff) side?

I presume that you mean the User (client) side.  I receive a similar error, but it appears that it was reported here first: https://github.com/osTicket/osTicket-1.8/issues/2276

**Comment by gmt-it** [comment]
Frontend: In your words User side.
Backend: In your words Agent side.
Sorry @ntozier #2276 is about login, logout. This one is about that it is impossible to open a ticket at CLIENT SIDE because the Client has to click the SAVE DRAFT POPUP 1000 times. Error at log states about CSRF Token, thats it.

**Comment by gmt-it** [comment]
#2295 works for me.
