### ISSUE TITLE
1.10 RC1 Issues - Custom List Ticket Status

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2292]
Unable to create new Status. The ajax window comes up but after saving the new status does not display anywhere in the system. If I go back to create the same one the system says that is already exists.

![image](https://cloud.githubusercontent.com/assets/5774055/8873995/6fa525dc-31da-11e5-9d2c-1cac786cda7e.png)
![image](https://cloud.githubusercontent.com/assets/5774055/8874004/7e27e2f2-31da-11e5-8c5a-75d4adfd2847.png)

**Comment by kest874** [comment]
Note DB Error when you edit:

[UPDATE `ost_ticket_status` SET `value` = ?, `properties` = ? WHERE `ost_ticket_status`.`id` = ? LIMIT 1] Unknown column 'value' in 'field list'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(318): osTicket->logDBError('DB Error #1054', '[UPDATE `ost_ti...')
 #1 (root)/include/class.orm.php(2659): db_prepare('UPDATE `ost_tic...')
 #2 (root)/include/class.orm.php(526): MySqlExecutor->execute()
 #3 (root)/include/ajax.forms.php(183): VerySimpleModel->save()
 #4 [internal function]: DynamicFormsAjaxAPI->saveListItem('1', '3')
 #5 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)
 #6 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('1/item/3/update', Array)
 #7 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('1/item/3/update', Array)
 #8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/list/1/item/3/...', NULL)
 #9 (root)/scp/ajax.php(253): Dispatcher->resolve('/list/1/item/3/...')
 #10 {main}

**Comment by jdelhome3578** [comment]
I do have the same error:
DB Error #1054
[SELECT A1.* FROM `ost_ticket_status` A1 WHERE (A1.`value` LIKE ? OR A1.`extra` LIKE ? OR A1.`properties` LIKE ?) ORDER BY A1.`sort` ASC] Unknown column 'A1.value' in 'where clause'

 ---- Backtrace ----
 #0 C:\inetpub\osTicket\DPR\include\mysqli.php(318): osTicket->logDBError('DB Error #1054', '[SELECT A1.* FR...')
 #1 C:\inetpub\osTicket\DPR\include\class.orm.php(2659): db_prepare('SELECT A1.* FRO...')
 #2 C:\inetpub\osTicket\DPR\include\class.orm.php(2653): MySqlExecutor->execute()
 #3 C:\inetpub\osTicket\DPR\include\class.orm.php(2729): MySqlExecutor->_prepare()
 #4 C:\inetpub\osTicket\DPR\include\class.orm.php(1499): MySqlExecutor->getArray()
 #5 C:\inetpub\osTicket\DPR\include\class.orm.php(1322): ModelInstanceManager->fillTo(0)
 #6 C:\inetpub\osTicket\DPR\include\ajax.forms.php(232): ResultSet->valid()
 #7 [internal function]: DynamicFormsAjaxAPI->searchListItems('1')
 #8 C:\inetpub\osTicket\DPR\include\class.dispatcher.php(145): call_user_func_array(Array, Array)
 #9 C:\inetpub\osTicket\DPR\include\class.dispatcher.php(38): UrlMatcher->dispatch('1/items/search', Array)
 #10 C:\inetpub\osTicket\DPR\include\class.dispatcher.php(120): Dispatcher->resolve('1/items/search', Array)
 #11 C:\inetpub\osTicket\DPR\include\class.dispatcher.php(38): UrlMatcher->dispatch('/list/1/items/s...', NULL)
 #12 C:\inetpub\osTicket\DPR\scp\ajax.php(253): Dispatcher->resolve('/list/1/items/s...')
 #13 {main}

**Comment by jdelhome3578** [comment]
There are items saved in the `list_items` table but nothing is showing in the ui.

**Comment by greezybacon** [comment]
Can anyone try the patch in #2314?

**Comment by jdelhome3578** [comment]
Does not correct the issue, New Status still being saved in `list_items` instead of `ticket_status` table.

**Comment by jdelhome3578** [comment]
#2314 Now Confirmed Fix

**Comment by jdelhome3578** [comment]
@greezybacon regression in latest develop-tip.
