### ISSUE TITLE
osticket 1.9.11 all SMTP settings are returning as authentication failure [SMTP: Invalid response code received from server (code: 535, response: Incorrect authentication data)]

### ISSUE THREAD

**Issue by supportreq** [osTicket/osTicket-1.8#2301]
I am not sure if only I am facing this issue but with the 1.9.11 version of osticket, whenever I configure any smtp account [mandrill or even my own email server] it is coming as incorrect authentication data. I have an old installation with osticket 1.8 same settings are working perfectly fine.

telnet connection through ssh works perfectly fine

**Comment by jobymathai** [comment]
me also receiving plenty of email fetch errors in the new osticket release. Also while posting replies, it is very slow and sometimes not even getting successful page. I checked with the database settings and it seems to be fine. Please check whether there is any issues with the recent osticket update..

**Comment by supportreq** [comment]
There was an error in the server configuration which gave this issue. It is resolved now..

**Comment by greezybacon** [comment]
To help other users with the same issue, could you post your resolution?

**Comment by supportreq** [comment]
The cpanel server was configured that smtp was allowed only for root user and no other user. Hence whenever the email was being sent via PHP, smtp would redirect to the local server.

To verify and rectify the issue please follow : 
It looks as though you have enabled "Restrict outgoing SMTP to root, exim, and mailman (FKA SMTP Tweak)" under WHM > Server Configuration > Tweak Settings > Mail.  Enabling this feature will redirect outgoing SMTP connections to the local mail server. root, exim, and mailman are still allowed to make direct connections.
