### ISSUE TITLE
1.10RC 1 Error while creating a new installation with different table prefix

### ISSUE THREAD

**Issue by supportreq** [osTicket/osTicket-1.8#2302]
While installing 1.10RC1 with a different table prefix instead of ost_ the installation crashes..

[25-Jul-2015 07:11:20 UTC] PHP Fatal error:  Uncaught exception 'InconsistentModelException' with message 'Unable to prepare query: Table 'db.ost_translation' doesn't exist SELECT A1.* FROM `ost_translation` A1 WHERE (A1.`lang` = ? AND A1.`type` = ?)' in /home/user/public_html/upload/include/class.orm.php:2660
Stack trace:
#0 /home/user/public_html/upload/include/class.orm.php(2653): MySqlExecutor->execute()
#1 /home/user/public_html/upload/include/class.orm.php(2729): MySqlExecutor->_prepare()
#2 /home/user/public_html/upload/include/class.orm.php(1499): MySqlExecutor->getArray()
#3 /home/user/public_html/upload/include/class.orm.php(1322): ModelInstanceManager->fillTo(0)
#4 /home/user/public_html/upload/include/class.translation.php(899): ResultSet->valid()
#5 /home/user/public_html/upload/include/class.translation.php(920): CustomDataTranslation::getTranslation('en_US')
#6 /home/user/public_html/upload/include/class.list.php( in /home/user/public_html/upload/include/class.orm.php on line 2660

**Comment by jdelhome3578** [comment]
I noticed this issue with the DPR.

**Comment by greezybacon** [comment]
Can anyone verify the patch in #2324?

**Comment by mfelber** [comment]
Yes,  I can confirm that #2324 fixes the issue.
