### ISSUE TITLE
1.10 RC1 Issue Canned Responses only with Key - All Departments -

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#2304]
If you ansered a ticket only Canned Responses with Key - All Departments - are shown. Canned Responses from Departments are not shown.

**Comment by ntozier** [comment]
Can you provide a screen shot because I'm not real sure what you mean.

**Comment by gmt-it** [comment]
Canned Responses:
![canned_001](https://cloud.githubusercontent.com/assets/10116166/8910058/fc480fc0-3484-11e5-84f2-4728c3667911.png)

Ticket: Department Support DE
![canned_002](https://cloud.githubusercontent.com/assets/10116166/8910085/1fe59ede-3485-11e5-8288-96d921be7a27.png)

Only Canned Responses from - All Departments - are shown:
![canned_003](https://cloud.githubusercontent.com/assets/10116166/8910103/45174766-3485-11e5-989d-72e5bb8750a3.png)

**Comment by greezybacon** [comment]
Can you try the patch in #2315?

**Comment by gmt-it** [comment]
#2315 works for me!

**Comment by greezybacon** [comment]
Fixed by #2315
