### ISSUE TITLE
1.9.11 - DB Error #1104

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#2310]
Like the error in issue #1532 a similar thing occurs in some of my osticket installations after upgrading to 1.9.11. I think it depends on how much data is in the system. It doesn't seem to have a negative effect to the search like in #1532 but the error log grows continously..

The log shows this:

DB Error #1104
[SELECT ticket.ticket_id, coalesce(attach.count, 0) as attachments, coalesce(thread.count, 0) as thread_count, coalesce(collab.count, 0) as collaborators FROM ost_ticket ticket left join (select count(attach.attach_id) as count, ticket_id from ost_ticket_attachment attach group by attach.ticket_id) as attach on (attach.ticket_id = ticket.ticket_id) left join (select count(thread.id) as count, ticket_id from ost_ticket_thread thread group by thread.ticket_id) as thread on (thread.ticket_id = ticket.ticket_id) left join (select count(collab.id) as count, ticket_id from ost_ticket_collaborator collab group by collab.ticket_id) as collab on (collab.ticket_id = ticket.ticket_id) WHERE ticket.ticket_id IN (7487, 7490, 7483, 7489, 7372, 7488, 7486, 7485, 7484, 7254, 7437, 7436, 7433, 7432, 7427, 7424, 7423, 7281, 6826, 7327, 7326, 7175, 7242, 7259, 7257);] The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay

 ---- Ablaufverfolgung ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1104', '[SELECT ticket....')
 #1 (root)/include/staff/tickets.inc.php(304): db_query('SELECT ticket.t...')
 #2 (root)/scp/tickets.php(506): require_once('/is/htdocs/wp11...')
 #3 {main}

It seems to be occurring when somebody navigates to the ticket view.

I guess this change in the code has to do with it: https://github.com/osTicket/osTicket-1.8/commit/c4ace2d53af4b2a792c92c8e0523e40adc857366

So maybe 1.9.9 and 1.10-rc1 is affected too because the headline text says that v1.10-rc.1, v1.9.11 and v1.9.9 have this code. Till now I have seen it only in 1.9.11 but it seems to depending on the amount of data that is in the system. I have no installations with 1.9.9 and 1.10-rc with much data in it.

For those who aren't in the comfortable position to change the mysql settings (like me) I could prevent the occuring of this error when I add this code (only the bold text) in the /include/staff/ticket.inc.php (after line 303):

' WHERE ticket.ticket_id IN ('.implode(',', db_input(array_keys($results))).');';
   **// SET SQL_BIG_SELECTS=1;**
   **db_query('SET SQL_BIG_SELECTS=1;');**
$ids_res = db_query($counts_sql);

I'm not really an expert in these things so maybe I'm wrong but till now I couldn't see a negative effect with this modification..

My System environment:
osTicket-Version	v1.9.11 (c1b5a33) —  Up to date
Server-Software	Apache
MySQL-Version	5.5.42
PHP-Version	5.4.43-1~he.0

**Comment by greezybacon** [comment]
@mfelber could you send me an explain plan for the query from your database? I'm confused, because the query runs significantly faster and should examine fewer rows than the previous one. *Maybe we should switch to Postgres*

**Comment by infectormp** [comment]
@greezybacon please switch to oracle :) then i can optimise all osticket queries

**Comment by mfelber** [comment]
@greezybacon Maybe I can, but unfortunately I don't know how to do this and if am able to do this with the restricted access I have to this hosting. Could you help me a little bit how this can be achieved? It sounds like a special mysql function..

**Comment by greezybacon** [comment]
@mfelber it's simple:
```sql
EXPLAIN SELECT ticket.ticket_id, coalesce(attach.count, 0) as attachments, coalesce(thread.count, 0) as thread_count, coalesce(collab.count, 0) as collaborators FROM ost_ticket ticket left join (select count(attach.attach_id) as count, ticket_id from ost_ticket_attachment attach group by attach.ticket_id) as attach on (attach.ticket_id = ticket.ticket_id) left join (select count(thread.id) as count, ticket_id from ost_ticket_thread thread group by thread.ticket_id) as thread on (thread.ticket_id = ticket.ticket_id) left join (select count(collab.id) as count, ticket_id from ost_ticket_collaborator collab group by collab.ticket_id) as collab on (collab.ticket_id = ticket.ticket_id) WHERE ticket.ticket_id IN (7487, 7490, 7483, 7489, 7372, 7488, 7486, 7485, 7484, 7254, 7437, 7436, 7433, 7432, 7427, 7424, 7423, 7281, 6826, 7327, 7326, 7175, 7242, 7259, 7257);
```
Just add the word `explain` in front of the offending query

**Comment by mfelber** [comment]
@greezybacon When I use this query I get this result:

![result](https://cloud.githubusercontent.com/assets/5539456/8913840/d40721ba-349b-11e5-89c3-c03ab866e6da.JPG)

**Comment by greezybacon** [comment]
@mfelber in our production tests, the commit looks like a very bad idea. I will propose reverting it

**Comment by mfelber** [comment]
@greezybacon Ok. Should I close this issue? 

Another little off topic question: will the avatars stay in 1.10? I don't see a hint that they will be in 1.10.
I really like them. They make it easier to see which thread is from who..

**Comment by gmt-it** [comment]
@mfelber Off Topic: Can you tell me how to change the avatars? I am to stupid to find it.

**Comment by ntozier** [comment]
The avatars are in 1.10 (and I understand that they will be staying).

They can be changed in the ui.  They are from Gravatar.com.

**Comment by mfelber** [comment]
@gmt-it Ntozier is right. Till now you could only "change" the avatar via gravatar.com. When you setup an account there osticket seems to "detecting" it. I'm not so good in explaining. I mean when you use the same email address in osticket that is used for the gravatar.com account it displays the corresponding avatar. The avatar feature is in initial state. I'm sure later there will be more options (activate/deactivate, using other sources). But also in this early state it is a real nice feature. Make's the system even more "personal"...

**Comment by mckaygerhard** [comment]
> @greezybacon please switch to oracle :) then i can optimise all osticket queries

really i like this too, in another issue i cited same suggestion, due the 3 most scalar dbms are oracle, db2 and postgresql
