### ISSUE TITLE
1.10 RC1 Client cannot login

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#2313]
If a registered User try to login to see his tickets, only white page is shown.

**Comment by greezybacon** [comment]
Have you tried the patch in #2295?

**Comment by gmt-it** [comment]
Yes. #2295 helps by "Unable to save Draft" but not by User Login.

**Comment by greezybacon** [comment]
#2295 fixes the login problem for me. Could you submit something from your log files and a screenshot so I can replicate the issue?

**Comment by gmt-it** [comment]
Parse error: syntax error, unexpected T_LNUMBER in /var/www/vhosts/xxx.xx/nl.s-pay.me/secure.inc.php on line 22

**Comment by gmt-it** [comment]
Just made a clean install with Patch #2295. Register new user on client front end and try to login: White page!

**Comment by ntozier** [comment]
If you are getting a white page we will need the PHP error being generated please check your logs.

**Comment by gmt-it** [comment]
Forget it! I just find the error...got a typo at line 22.... #2295 works for login! Sorry!

**Comment by ntozier** [comment]
No worries.  Thanks for letting us know!
