### ISSUE TITLE
1.10 RC1 Issues - Advanced Search User \ Full Name

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2317]
`Fatal error: Uncaught exception 'OrmException' with message 'Model `User` does not have a relation called `name`' in C:\inetpub\osTicket\DPR\include\class.orm.php:1889 Stack trace: #0 C:\inetpub\osTicket\DPR\include\class.orm.php(1901): SqlCompiler->{closure}('name', 'User') #1 C:\inetpub\osTicket\DPR\include\class.orm.php(2025): SqlCompiler->getField('user__name__eq', 'TicketModel') #2 C:\inetpub\osTicket\DPR\include\class.orm.php(2008): SqlCompiler->compileQ(Object(Q), 'TicketModel', false) #3 C:\inetpub\osTicket\DPR\include\class.orm.php(2055): SqlCompiler->compileQ(Object(Q), 'TicketModel') #4 C:\inetpub\osTicket\DPR\include\class.orm.php(2327): SqlCompiler->compileConstraints(Array, 'TicketModel') #5 C:\inetpub\osTicket\DPR\include\class.orm.php(2350): MySqlCompiler->getWhereHavingClause(Object(QuerySet)) #6 C:\inetpub\osTicket\DPR\include\class.orm.php(1097): MySqlCompiler->compileCount(Object(QuerySet)) #7 C:\inetpub\osTicket\DPR\scp\tickets.php(478): QuerySet->count() #8 {main} thrown in C:\inetpub\osTicket\DPR\include\class.orm.php on line 1889`

**Comment by greezybacon** [comment]
This is addressed in #2360

**Comment by jdelhome3578** [comment]
:+1: Thank You
