### ISSUE TITLE
RC 1.10 Display does not work after upgrade

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2321]
hey

I've started on my test system, the update for fun.
However, there are problems with the display.

I upgraded from v 1.9.11

![11](https://cloud.githubusercontent.com/assets/13413719/8930513/01b21622-352f-11e5-894d-96e1497549dc.png)
![22](https://cloud.githubusercontent.com/assets/13413719/8930512/01b19d14-352f-11e5-97b9-7713a2b8330b.png)
![33](https://cloud.githubusercontent.com/assets/13413719/8930514/01b45112-352f-11e5-88d9-e01bb223f987.png)

**Comment by ntozier** [comment]
You appear to have reported this 4 days ago [ in this thread: https://github.com/osTicket/osTicket-1.8/issues/2277 ] so I'm not sure why you are reporting it again.

Fix is here: https://github.com/osTicket/osTicket-1.8/pull/2297

**Comment by oneilak** [comment]
There are 2 reasons

1. The topic has been changed because there is another problem, I have no problem with the time but with the display.
2. not have reacted to this, so I wanted to make sure that was not it overlooked or you think that it is already done.

therefore a new topic

**Comment by ntozier** [comment]
No worries. :)
