### ISSUE TITLE
1.10 RC1 Issues - Unable to View Closed Tickets

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2328]
Unable to view Closed Tickets on Agent and Client side. Error is the same for both.
  - `Fatal error: Call to a member function getForm() on a non-object in C:\inetpub\osTicket\DPR\include\class.list.php on line 1334`

**Comment by ntozier** [comment]
unable to replicate

**Comment by jdelhome3578** [comment]
I am running modifications from #2314

**Comment by greezybacon** [comment]
Fixed by 5a80b53

**Comment by jdelhome3578** [comment]
:+1:
