### ISSUE TITLE
1.9.11 - wrong time in the ticket system

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2330]
Hello everybody,

I suddenly have the problem that hours after the time depends on the ticket system 1. when I change the time zone in the settings nothing, the server and the DC are happening far from the correct time ago.

someone has a tip on this?
Since the time is no longer correct, I always get an error message when a user attaches an appendix to a ticket.

I use the plugin to the files to add to a share, I suspect it has to do with the wrong time

 IOException: Unable to read resource content

(root)/Uploade/W/W8hEpT3bFxe0LnCNJUxnFyiWoGg0hWHk: Unable to read from file

**Comment by oneilak** [comment]
![2015_07_30_10_02_06_osticket_agenten_bereich](https://cloud.githubusercontent.com/assets/13413719/8978394/30186b46-36a2-11e5-9989-923d6c1544b8.png)

**Comment by oneilak** [comment]
the time somehow does not change despite the time zone change

![1](https://cloud.githubusercontent.com/assets/13413719/8978470/c1e8753e-36a2-11e5-8d93-6b52fa48b364.png)
![2](https://cloud.githubusercontent.com/assets/13413719/8978468/c187b4c4-36a2-11e5-9c5b-6d09138e9021.png)
![3](https://cloud.githubusercontent.com/assets/13413719/8978469/c1af8e36-36a2-11e5-8b02-e933fad28e19.png)

**Comment by ntozier** [comment]
This has been covered before and is because that is not the actual time.  Its a formatting example from the options that you picked to the left of the red boxes that you made to show you what the date time will look like.

**Comment by oneilak** [comment]
nevertheless agrees the time of ticket openings or comments not in tickets :-(

**Comment by ntozier** [comment]
I'm not sure that your trying to say.

Have you checked the following:
Admin panel -> Settings -> Default Time Zone: and Daylight Saving:

Admin panel -> Staff -> each user's timezone and daylight saving setting.

your PHP.ini for your set time zone.

Have you enabled intl PHP extension?

**Comment by oneilak** [comment]
found: P

there was a 2nd option there stood (for whatever reason) Asia time zone inside

![1111](https://cloud.githubusercontent.com/assets/13413719/8985123/f942ddca-36d5-11e5-94f4-da19b283f471.png)
