### ISSUE TITLE
no Status "Last Updated" 1.10 RC1

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2337]
is it a bug?

![2222](https://cloud.githubusercontent.com/assets/13413719/9002490/1ad73ee2-3765-11e5-8390-3e664e1b2ddf.png)

**Comment by ntozier** [comment]
Appears to work in my test installation.
Whats your date format in Admin panel -> Settings -> System?
Do you have intl PHP module loaded?
Please provide more information about your setup.

![capture](https://cloud.githubusercontent.com/assets/1315768/9008243/e4764a26-3766-11e5-883e-68f22c255efc.PNG)

**Comment by oneilak** [comment]
ah ok the intl module was disabled ... it works
