### ISSUE TITLE
1.10 RC1 Issues - System message for Collaborator added

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2339]
`Bob added Joe via ? as collaborators 3 days ago`

![image](https://cloud.githubusercontent.com/assets/5774055/9007483/c2392386-375f-11e5-8b9d-9904373b7d74.png)

**Comment by ntozier** [comment]
Steps to reproduce:
In the ui go to a ticket.
Add someone as a collaborator.
note: am running the LDAP plugin.
