### ISSUE TITLE
Ticket List Empty

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2342]
When creating a ticket on the agent side and marking it closed with a response the Ticket list comes up with no tickets.  1.9.11 not sure if it happens in 1.10

![image](https://cloud.githubusercontent.com/assets/5774055/9008715/260b8930-376a-11e5-888f-a45b420c78b8.png)

**Comment by ntozier** [comment]
my 1.10rc1 does not have the close option in the drop down.

**Comment by jdelhome3578** [comment]
I have mods from #2314

**Comment by greezybacon** [comment]
#2314 was merged into `develop-next` (v1.10 branch); however, you said the problem definitely exists in v1.9.  Plus, your screenshot shows some custom queues. Can you confirm the problem exists in either the vanilla `develop` or `develop-next` branch?

**Comment by jdelhome3578** [comment]
@ntozier is correct the `Ticket Status` drop down only contains open statuses in 1.10; 1.9 has all statuses, I use that a lot when I open a ticket but have already resolved it and want to mark it closed.

**Comment by jdelhome3578** [comment]
@greezybacon It does not Sorry about that. How are those custom queues coming?
