### ISSUE TITLE
1.10 RC1 Issues - Items in Custom List

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2345]
`Warning: Invalid argument supplied for foreach() in C:\inetpub\osTicket\DPR\include\staff\templates\list-items.tmpl.php on line 72`

`Warning: Invalid argument supplied for foreach() in C:\inetpub\osTicket\DPR\include\staff\templates\list-item-row.tmpl.php on line 34`

![image](https://cloud.githubusercontent.com/assets/5774055/9014906/5226adbe-3793-11e5-83a3-80ebf481e753.png)

**Comment by greezybacon** [comment]
I think this was fixed recently. Can you retest from the tip of `develop-next`?

**Comment by jdelhome3578** [comment]
:+1:
