### ISSUE TITLE
1.10 RC1 Issues - Deleting Department

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2346]
Deleting a department throws the following error in the system log:

**DB Error #1054**
`[UPDATE ost_filter SET dept_id=0 WHERE dept_id=6] Unknown column 'dept_id' in 'where clause'`

 ---- Backtrace ----
 #0 C:\inetpub\osTicket\DPR\include\mysqli.php(183): osTicket->logDBError('DB Error #1054', '[UPDATE ost_fil...')
 #1 C:\inetpub\osTicket\DPR\include\class.dept.php(370): db_query('UPDATE ost_filt...')
 #2 C:\inetpub\osTicket\DPR\scp\departments.php(101): Dept->delete()
 #3 {main}

**Comment by greezybacon** [comment]
That's a bug

**Comment by greezybacon** [comment]
This is fixed with the patch in #2359
