### ISSUE TITLE
v 1.10 RC1 ... error in code ?  include/class.osticket.php

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2347]
hey

is the code so right?
when yes close the issus
 include/class.osticket.php
![unbenannt](https://cloud.githubusercontent.com/assets/13413719/9015804/dd389a4c-37cb-11e5-8b29-7afb848702c6.PNG)

**Comment by greezybacon** [comment]
Yes. `require_once` is a language construct and PHP optcode. Parentheses aren't required
