### ISSUE TITLE
Help Topic List Sorting

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2350]
When sorting Alphabetically the system does not sort upper case and lower case together.

example: The system will sort A-Z then a-z
Suggestion: Sort A-Z and a-z together not separate.

**Comment by greezybacon** [comment]
Can you try the patch in #2357?

**Comment by jdelhome3578** [comment]
:+1:

**Comment by greezybacon** [comment]
> This is also an issue in 1.9

I disagree. Sorting happens in MySQL, which should be configured with a collation of `utf8_general_ci`, and should therefore be *c*ase *i*nsensitive.

**Comment by jdelhome3578** [comment]
![image](https://cloud.githubusercontent.com/assets/5774055/9061954/2453129a-3a8d-11e5-99c4-fa65b33cce80.png)

**Comment by greezybacon** [comment]
My mistake, they are sorted in PHP in v1.9.11

**Comment by greezybacon** [comment]
Would this fix it on v1.9.11?

```patch
diff --git a/include/class.topic.php b/include/class.topic.php
index a59d366..6dc368f 100644
--- a/include/class.topic.php
+++ b/include/class.topic.php
@@ -415,7 +415,7 @@ class Topic {
         if (!($names = static::getHelpTopics(false, true)))
             return;
 
-        uasort($names, function($a, $b) { return strcmp($a, $b); });
+        uasort($names, function($a, $b) { return strcasecmp($a, $b); });
 
         $update = array_keys($names);
         foreach ($update as $idx=>&$id) {
```

**Comment by greezybacon** [comment]
Note that after applying the patch, you'll need to edit one of the help topics and click save

**Comment by jdelhome3578** [comment]
@greezybacon Found the problem #2490
