### ISSUE TITLE
Develep-Next Warning after creating a new ticket at client interface

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#2352]
Got this warning after creating a new ticket at client interface:
Warning: array_merge(): Argument #2 is not an array in /var/www/vhosts/test.nl/nl.test.me/include/class.ticket.php on line 1219 Warning: Invalid argument supplied for foreach() in /var/www/vhosts/test.nl/nl.test.me/include/class.ticket.php on line 1236

**Comment by gmt-it** [comment]
Warning only occurs, if heltopic is not auto assigned to Agent or Team.

**Comment by greezybacon** [comment]
Could you try the patch in #2356?

**Comment by gmt-it** [comment]
@greezybacon : Works for me! :-)
