### ISSUE TITLE
V 1.10 RC1 ... Ticket can not assigned to any agent at opening

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2361]
It is intended, that i can no longer assign a ticket to a agent at the ticket opening?
![1](https://cloud.githubusercontent.com/assets/13413719/9036244/f42f2124-39df-11e5-9858-69313d6ea0b8.png)

**Comment by jdelhome3578** [comment]
Same question.

**Comment by jdelhome3578** [comment]
`Assign to` was an option in 1.9.11 but is missing in 1.10

![image](https://cloud.githubusercontent.com/assets/5774055/9087100/95dea09a-3b56-11e5-8cde-ee00a7f755eb.png)

**Comment by oneilak** [comment]
it works :-)

**Comment by jdelhome3578** [comment]
Fixed :+1:
