### ISSUE TITLE
1.10 RC1 Issues - Featured Questions URL

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2364]
`http://kb/faq.php?id=1` is missing osticket root

![image](https://cloud.githubusercontent.com/assets/5774055/9045090/eaa32240-39ee-11e5-9053-af6ca1d3c4ba.png)

**Comment by ntozier** [comment]
and where is that link located?

**Comment by jdelhome3578** [comment]
Client Front Page- sorry
