### ISSUE TITLE
1.10 rc1 Email piping error

### ISSUE THREAD

**Issue by simonbradbury** [osTicket/osTicket-1.8#2367]
Hi
We are getting a problem with emails piped in,

<support@lpe-group.com>: Command died with status 255:
   "/var/www/httpdocs/api/pipe.php".
   Command output: PHP Fatal error:  Can't inherit abstract function
   AuthenticatedUser::getId() (previously declared abstract in
   BaseAuthenticatedUser) in
   /var/www/httpdocs/include/class.auth.php
   on line 26

**Comment by greezybacon** [comment]
Is this CentOS PHP 5.3.3 with osTicket v1.10?

**Comment by simonbradbury** [comment]
Hi

Version 5.6.11

**Comment by simonbradbury** [comment]
<img width="1280" alt="screen shot 2015-08-04 at 15 38 33" src="https://cloud.githubusercontent.com/assets/13642917/9063384/f896ac02-3abe-11e5-9b0a-00414b4eb126.png">

**Comment by simonbradbury** [comment]
<img width="960" alt="screen shot 2015-08-04 at 15 38 33" src="https://cloud.githubusercontent.com/assets/13642917/9063420/2dfa9b42-3abf-11e5-91fc-47e03bdf6585.png">

**Comment by greezybacon** [comment]
Are you sure? Many hosting environments will run a different PHP for commandline

**Comment by greezybacon** [comment]
I think this is addressed in 627bb6fb248e986b53a7798e4a857813fffb84c4 to be released in rc2

**Comment by simonbradbury** [comment]
Great, thanks for the update !

Simon

**Comment by simonbradbury** [comment]
Can confirm that this is fixed with the amended files

Thanks
Simon

**Comment by greezybacon** [comment]
@simonbradbury thanks for the updates
