### ISSUE TITLE
1.10 - posting internal note in ticket doesn't work -> this action requires a lock

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#2371]
When I try to post an internal note in a ticket, osticket reponds "Unable to post the note. Correct the error(s) below and try again!" and "This action requires a lock. Please try again":

![internal note](https://cloud.githubusercontent.com/assets/5539456/9084910/7210313e-3b78-11e5-9637-9f2cb117f9f1.jpg)

Trying it again doesn't work, the same messages will be shown.

I'm using the actual develop-next files with the recent merges..

**Comment by mfelber** [comment]
When I set the "Collision Avoidance Duration" to "0" (disable the lockout feature) it is possible to post an internal note.

**Comment by jdelhome3578** [comment]
I would add your issue to #2343

**Comment by mfelber** [comment]
I had seen the other issue, but in #2343 was the problem in posting a reply (which works fine in my environment)...

**Comment by mfelber** [comment]
#2371 fixes the problem with posting an internal note :+1:
