### ISSUE TITLE
1.10 RC1 Issues - New Ticket Status Drop Down

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2372]
In 1.9.11 you could set a closed status on a new ticket, in 1.10 it appears that only open statuses are available in the drop down.

![image](https://cloud.githubusercontent.com/assets/5774055/9086901/757f6b8c-3b55-11e5-8340-1d75e70ab8d5.png)

**Comment by mfelber** [comment]
Interesting, in my 1.10 test installation with the actual files from develop-next there is only the status "Open" when I open a ticket. All the other status values are missing in the drop down list..

**Comment by jdelhome3578** [comment]
I was testing and added a status Reopened with state open. No status with state closed appear here.

**Comment by jdelhome3578** [comment]
:+1:
