### ISSUE TITLE
1.10 RC1 - New Ticket Alert to Dept Members

### ISSUE THREAD

**Issue by antondreyer** [osTicket/osTicket-1.8#2380]
Hi

I have set up four departments under the support dept - each with their own email address (eg. support/Branch1, support/Branch2 etc.). I have 3 agents that service combinations of these branches. I have found that when their primary dept is set to 'support' with extended access on combinations of the depts they are able to see the relevant tickets to their 'branches'.

When the scheduled email fetch however runs, only the manager of each dept gets alerted about the new ticket, not the members with extended access. 

'Alerts' are enabled for members under new ticket alert settings, access settings under dept and the "Disable for this Department" flags are cleared under dept also.

Any idea why this is not working?

**Comment by ntozier** [comment]
My guess would be because they are not a member of the parent department.
Or that since this is a new feature in 1.10 that it simply hasn't been implemented yet.

**Comment by greezybacon** [comment]
I believe this is fixed in c4611f8b0be73c2703fd63710df8b3e870eff6b0

**Comment by antondreyer** [comment]
Working perfectly now - thanks!
