### ISSUE TITLE
v1.9.9-1 DB error #1146 Table "cdata" continues to be dropped/rebuilt

### ISSUE THREAD

**Issue by holodoctor1** [osTicket/osTicket-1.8#2382]
Getting issue with my cdata table dropping and rebuilding throwing DB errors to my email.

I can confirm that cdata does exist.

See below:

[SELECT ticket.ticket_id,tlock.lock_id,ticket.`number`,ticket.dept_id,ticket.staff_id,ticket.team_id  ,user.name ,email.address as email, dept.dept_name, status.state  ,status.name as status,ticket.source,ticket.isoverdue,ticket.isanswered,ticket.created  ,IF(ticket.duedate IS NULL,IF(sla.id IS NULL, NULL, DATE_ADD(ticket.created, INTERVAL sla.grace_period HOUR)), ticket.duedate) as duedate ,CAST(GREATEST(IFNULL(ticket.lastmessage, 0), IFNULL(ticket.closed, 0), IFNULL(ticket.reopened, 0), ticket.created) as datetime) as effective_date  ,ticket.created as ticket_created, CONCAT_WS(" ", staff.firstname, staff.lastname) as staff, team.name as team  ,IF(staff.staff_id IS NULL,team.name,CONCAT_WS(" ", staff.lastname, staff.firstname)) as assigned  ,IF(ptopic.topic_pid IS NULL, topic.topic, CONCAT_WS(" / ", ptopic.topic, topic.topic)) as helptopic  ,cdata.priority as priority_id, cdata.subject, pri.priority_desc, pri.priority_color  FROM ost_ticket ticket  LEFT JOIN ost_ticket_status status
           ON (status.id = ticket.status_id)  LEFT JOIN ost_user user ON user.id = ticket.user_id LEFT JOIN ost_user_email email ON user.id = email.user_id LEFT JOIN ost_department dept ON ticket.dept_id=dept.dept_id  LEFT JOIN ost_ticket_lock tlock ON (ticket.ticket_id=tlock.ticket_id AND tlock.expire>NOW()
              AND tlock.staff_id!=7)  LEFT JOIN ost_staff staff ON (ticket.staff_id=staff.staff_id)  LEFT JOIN ost_team team ON (ticket.team_id=team.team_id)  LEFT JOIN ost_sla sla ON (ticket.sla_id=sla.id AND sla.isactive=1)  LEFT JOIN ost_help_topic topic ON (ticket.topic_id=topic.topic_id)  LEFT JOIN ost_help_topic ptopic ON (ptopic.topic_id=topic.topic_pid)  LEFT JOIN ost_ticket__cdata cdata ON (cdata.ticket_id = ticket.ticket_id)  LEFT JOIN ost_ticket_priority pri ON (pri.priority_id = cdata.priority)  WHERE (   ( ticket.staff_id=7 AND (status.state="open" OR status.state="closed"))  OR ticket.dept_id IN (73) OR (ticket.team_id IN (6) AND status.state="open")  ) AND status.state IN (
               'open' )  AND ticket.isanswered=0  ORDER BY assigned ASC, ticket.created DESC LIMIT 0,50]

Table 'ossupport.ost_ticket__cdata' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 F:\sites\osticket19\include\mysqli.php(177): osTicket->logDBError('DB Error #1146', '[SELECT ticket....')<br />
#1 F:\sites\osticket19\include\staff\tickets.inc.php(275): db_query('SELECT ticket.t...')<br />
#2 F:\sites\osticket19\scp\tickets.php(512): require_once('F:\sites\ostick...')<br />
#3 {main}

**Comment by mfelber** [comment]
This seems to be duplicate to https://github.com/osTicket/osTicket-1.8/issues/1545. You maybe should use the former thread and post information about your environment. That would raise the chances that somebody can help you...

**Comment by holodoctor1** [comment]
That does appear to be our issue.  Thank you for pointing out #1545
