### ISSUE TITLE
v1.10 RC1 SLA is not updating

### ISSUE THREAD

**Issue by rpbaquing** [osTicket/osTicket-1.8#2384]
SLA is not changing after editing the ticket details:

![image](https://cloud.githubusercontent.com/assets/12552461/9127941/4a2a6f68-3cf4-11e5-9e04-44092c4a1811.png)

but the  SLA did not change

![image](https://cloud.githubusercontent.com/assets/12552461/9127976/af16c0b6-3cf4-11e5-8655-629c15788fd3.png)

**Comment by ntozier** [comment]
Confirmed in my 1.10 rc1 install.

**Comment by jdelhome3578** [comment]
Confirmed in mine also

**Comment by greezybacon** [comment]
I can confirm this too

**Comment by greezybacon** [comment]
#2392 fixes the issue for me

**Comment by jdelhome3578** [comment]
Works :+1:

**Comment by rpbaquing** [comment]
@greezybacon thanks for this! :)
