### ISSUE TITLE
v1.10-rc1 - Guest Ticket (User) Not Working

### ISSUE THREAD

**Issue by bradfish** [osTicket/osTicket-1.8#2387]
Hello there,

I've spent my morning read support threads on GitHub as well as OSTicket's main page. From my understanding there have been several people who have reported issues with users making a ticket; however, most of them were able to resolve it. Below is the individual information about my OS ticket version.

osTicket Version	v1.10-rc.1 (33f18c5) —  Up to date
Web Server Software	Apache
MySQL Version	5.5.42
PHP Version	5.3.29

As far as patches, I have applied:
https://github.com/greezybacon/osTicket-1.8/commit/c1f36ea3e831e3c2ab2745776bf53d20ba0f014b

https://github.com/greezybacon/osTicket-1.8/commit/54b8a8ce4e0934e491cb53d6e22fd0a53322d8d0

Unfortunately, this did not work (although it did help with logging in on the user/client side). Currently, if my user types a long message they get the popup that happens in a never ending loop below. Popup reads: "Uable to save draft. Refresh current page to restore and continue your draft.". In addition, when you post the ticket it does not actually post the ticket.

**Comment by greezybacon** [comment]
@bradfish do you see any javascript errors in your console while working on the client portal? What fields do you have configured for your "Contact Information" and "Ticket Details" forms?

**Comment by bradfish** [comment]
There are no javascript errors being displayed in IE or in Google Chrome. 

I am using a textbox for "Room Location" within the contact fields and in the ticket details form I am using an "Affected User" drop down menu with multiple options. In case you would like to investigate further or see for yourself: http://osc.lk/tech/open.php I've enabled guest posting tickets. Don't worry, it won't actually post a ticket :P

**Comment by bradfish** [comment]
Hey developers,

I haven't heard from anyone on this matter so I decided to do more detailed troubleshooting to try and get a resolution.
I disabled all form fields but the default and still got an error
Tried posting a ticket as a guest (got error) and then as a registered user client (no error).
Furthermore, the trouble ticket is not posted as a guest and is posted as a registered user client.

Please help me resolve.

**Comment by ntozier** [comment]
v1.10rc2 has been released.  Please retest with that.

**Comment by greezybacon** [comment]
You mentioned a "never ending loop". When the popup message is displayed, the draft saving system is disabled, which should prevent the popup from showing again. You say there are no javascript errors though. I'm confused at how the popup could continue without js error. Are you using nginx?

**Comment by bradfish** [comment]
I am going to install 1.10rc2 when I get into my office tomorrow. 

There were no javascript errors evident in both browsers I tried. The message that would popup would be the standard error for Unable to Save Draft please reload page (paraphrasing). Immediately after clicking okay the next popup box would occur and so forth (hence, never ending loop). I physically went into the javascript file that calls upon this message and commented it out. When completing this and testing it with a guest user I found I could now make a lengthy ticket; however, the ticket would never actually post to a database. The only time it would post to a database is if the user was logged in.

I will update this thread tomorrow

**Comment by bradfish** [comment]
Great news. This issue is fixed with the new RC release. Well done guys :)!
