### ISSUE TITLE
1.10 RC1 Issue - Unable to Sort Ticket Queue

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2394]
URL after sort selection: `/scp/tickets.php?&%5Bobject%20Object%5D=undefined`

**Comment by greezybacon** [comment]
Perhaps the output of `git describe` would be more helpful than "1.10 RC1 Issue + 115 Commits"

**Comment by jdelhome3578** [comment]
Tested from the tip of develop-next
