### ISSUE TITLE
1.10 RC1 Issue - Login Page Object Moved

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2397]
![image](https://cloud.githubusercontent.com/assets/5774055/9201512/7dec6d7c-401b-11e5-9fff-0d345f7c0da7.png)

`Object Moved`
`This document may be found here`

Refreshing the page will login correctly.

LDAP Enabled
HTTP Pass Thru Enabled

**Comment by ntozier** [comment]
I cannot replicate that.
Can you provide the page source?
Are you doing any web server redirect type things?

**Comment by jdelhome3578** [comment]
All files are from the tip of develop-next. I have no redirection. I don't have this issue with 1.9.11

**Comment by jdelhome3578** [comment]
Issue goes away when `// Browsers shouldn't suggest saving that username/password
Http::response(422);` is commented out

**Comment by jdelhome3578** [comment]
Also if I disable Windows Auth on IIS issues goes away.

**Comment by jdelhome3578** [comment]
@greezybacon still an issue in 1.10 rc2

**Comment by jdelhome3578** [comment]
#2641 fixes this issue more directly.
