### ISSUE TITLE
Field custom validation

### ISSUE THREAD

**Issue by BassemN** [osTicket/osTicket-1.8#2408]
Hello,

Is there any way to use a custom PHP code to validate a certain fields?

Thanks

**Comment by greezybacon** [comment]
You could write a plugin to add your own field type

Am Mittwoch, 12. August 2015 schrieb BassemN :

**Comment by BassemN** [comment]
Thank you, Is there any detailed docs about how to create plugins?

**Comment by ntozier** [comment]
There is an unofficial plugin development guide.
http://osticket.com/forum/discussion/comment/86081/
