### ISSUE TITLE
v 1.9.11 wrong time in faq

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2410]
when i create a new faq article, present he a wrong date and time stamp

![2015-08-13 14_37_43-osticket __ agenten-bereich](https://cloud.githubusercontent.com/assets/13413719/9249931/8d2e2456-41c9-11e5-8774-ac364815a1c7.png)

**Comment by mfelber** [comment]
I also think there is something wrong (using also 1.9.11). 

But the screeenshot shows a weird time (there must be also something other wrong in this setup I guess) and is not so a good example for this behavior (but it is the affected view). 

You could see what we mean when you create faq's. You will notice that they always show the last updated time of the category (in this view) and not of the faq itself. The values in the database are correct for the faq's.

I think I found the reason in the faq-view.inc.php on line 36:
`div class="faded">&nbsp;<?php echo __('Last updated');?> <?php echo format::db_daydatetime($category->getUpdateDate()); ?></div>`

When I replace this line with this line:
`<div class="faded">&nbsp;<?php echo __('Last updated');?> <?php echo Format::db_daydatetime($faq->getUpdateDate()); ?></div>`

the faq's are showing their correct last updated value in this view and no more the value from the category.

**Comment by oneilak** [comment]
it works ;-)
