### ISSUE TITLE
1.9.11: DB Error when ban mail address

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket-1.8#2412]
DB Error #1062
[INSERT INTO ost_filter_rule SET created=NOW(), filter_id=1, updated=NOW() , what='email', how='equal', val='mail@fortunalipe.ru', isactive=1] Duplicate entry '1-email-equal-mail@fortunalipe.ru' for key 'filter'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(177): osTicket->logDBError('DB Error #1062', '[INSERT INTO os...')
 #1 (root)/include/class.filter.php(674): db_query('INSERT INTO ost...')
 #2 (root)/include/class.filter.php(647): FilterRule->save(0, Array, Array)
 #3 (root)/include/class.filter.php(197): FilterRule->create(Array, Array)
 #4 (root)/include/class.banlist.php(21): Filter->addRule('email', 'equal', 'mail@fortunalip...')
 #5 (root)/scp/tickets.php(303): Banlist::add('mail@fortunalip...', Object(PersonsName))
 #6 {main}

**Comment by greezybacon** [comment]
So you're trying to ban an banned email?

**Comment by infectormp** [comment]
Sorry for delay. No, email was not in ban list. Any way i can't reproduce it now.
