### ISSUE TITLE
Problem in installing OsTicket 1.10 RC.1

### ISSUE THREAD

**Issue by mohitbhatia1994** [osTicket/osTicket-1.8#2422]
After filling all the information in Installation form when I click on install now it gives me a blank white screen. Even if I don't fill anything and click on install now it redirect to a white blank screen. I also checked my database and there are no new tables created. I downloaded it from official OsTicket website.

**Comment by jdelhome3578** [comment]
Did you change the prefix from `ost_`?

**Comment by mohitbhatia1994** [comment]
Nope.

**Comment by jdelhome3578** [comment]
I would try from the tip of devlop-next.

**Comment by mohitbhatia1994** [comment]
Now I am getting this error ...

Fatal error: Can't inherit abstract function AuthenticatedUser::getId() (previously declared abstract in BaseAuthenticatedUser) in /htdocs/dev/mohit_sandbox/osTicket1.10_new/include/class.auth.php on line 26

**Comment by mohitbhatia1994** [comment]
when 1.10 stable version will be released?

**Comment by ntozier** [comment]
Q: when 1.10 stable version will be released?
A: The short answer is "When it's ready".  The devs do not generally answer questions like this.  I expect RC2 to be released soon.

**Comment by greezybacon** [comment]
@mohitbhatia1994 I believe the PHP < 5.3.8 bug you cite is covered in the `develop-next` branch as of yesterday. Would you be able to try again and report if you're able to install now?

**Comment by mohitbhatia1994** [comment]
Sure I will let you know. Thanks

**Comment by mohitbhatia1994** [comment]
Yes it did worked. why it isn't saying version 1.10 RC1 instead it is saying 1.8-git

**Comment by greezybacon** [comment]
@mohitbhatia1994 it seems like you checked out a git repo. On the README.md page in the repo we suggest using the `deploy` command line script to make a production deployment. You can also download a packaged zip file from either github.com/osTicket/osTicket-1.8/releases or osticket.com/download
