### ISSUE TITLE
Add Processing Tab

### ISSUE THREAD

**Issue by BassemN** [osTicket/osTicket-1.8#2425]
Hello,

Sometimes we need to inform user that we are working on the ticket. In this case I need to place this ticket under Processing tab not Answered tab as you can see on the below image. Is that doable?
![processing](https://cloud.githubusercontent.com/assets/3768012/9328637/a88fb018-45aa-11e5-9a23-3e2652400b83.jpeg)

Thanks

**Comment by ntozier** [comment]
Currently no.  But you can:
Create a custom status of Processing (a sun type of open).
Change the status of the ticket to Processing.
Use Advanced Search to find all tickets of status Processing.

In 1.10+ you will be able to save the search as a custom queue so to speak.

**Comment by BassemN** [comment]
Thank you @ntozier hope to see it built in OST

**Comment by tomzquad** [comment]
Is there any updates for this ?

**Comment by ntozier** [comment]
If there was it would be posted here.
