### ISSUE TITLE
Osticket - How to make default Ticket's Detail form  appear above custom form

### ISSUE THREAD

**Issue by munzirahmad** [osTicket/osTicket-1.8#2428]
I created custom forms, but the default form always appear below.
pls help how to move it above.

**Comment by jdelhome3578** [comment]
That customization is in 1.10

**Comment by greezybacon** [comment]
v1.10 introduces the ability to place the forms however you like

**Comment by munzirahmad** [comment]
great! looking forward for that.
Thanks for your respond.
