### ISSUE TITLE
1.9.11 - user search box doesn't appear in org view and search box only works for remote users

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#2429]
I noticed that the user search box is missing in the "org view" (click on an org and click on "add user"):

![userlookup1](https://cloud.githubusercontent.com/assets/5539456/9353340/e64188f6-4667-11e5-9362-e48a71459315.jpg)

In the user view the field isn't missing:

![userlookup2](https://cloud.githubusercontent.com/assets/5539456/9353360/ffa744fc-4667-11e5-86aa-af6ea366d740.jpg)

When I change the line 126 in the ajax.orgs.php from

```$info['lookup'] = false;```

to 

```$info['lookup'] = true;```

the search field will be displayed:

![userlookup3](https://cloud.githubusercontent.com/assets/5539456/9353556/86672ef2-4669-11e5-87f8-17ce8ee08540.jpg)

Other users seem not to have this problem. Why is this affecting only my installations?

It is depending which authentication is used? I only use local authentication. The users I have seen that are having this search box without a modification are using the ldap plugin.

I have also seen that a similar change was made by the devs in april (2014) (https://github.com/osTicket/osTicket-1.8/commit/d6555add9ba9c42fc0ba7de48c6a171fa1c1eb53) for the ajax.users.php, maybe the ajax.orgs.php was missed?

I also noticed that others users reported that this search box in the org view only looks for remote users:

http://osticket.com/forum/discussion/86251/organization-adding-user-no-match-on-lookup#latest

Changing line 128 in the ajax.orgs.php like in the commit from april doesn't work:

I changed from ```$info['lookup'] = 'remote';``` to ```$info['lookup'] = 'local';```

But when I also change line 127 (like in the ajax.users.php) from

if ```(AuthenticationBackend::getSearchDirectories())``` 

to 

```if (!AuthenticationBackend::getSearchDirectories())``` 

it works like the search box in the user view. This seems to be a typo (!).

I don't understand much about this so maybe the devs should look at it.

**Comment by greezybacon** [comment]
@mfelber I agree with you. This logic seems broken—even in v1.10

**Comment by greezybacon** [comment]
Could you try the patch in #2431?

**Comment by mfelber** [comment]
@greezybacon Yes, I have tried it: the patch is working fine :+1:
