### ISSUE TITLE
Best way to customize Osticket

### ISSUE THREAD

**Issue by mohitbhatia1994** [osTicket/osTicket-1.8#2432]
Hi 
We are using OsTicket 1.7.0 and we have customized it a lot and all the customization are in the original source code of Osticket. So, Now I want to upgrade the Version to 1.9.11 but It's little difficult becuase we customized the original source code of 1.7.0. So I don't want to make same mistake again. Is there any way I can customize Osticket without affecting the source code which will make it easier to upgrade. 

Thanks

**Comment by greezybacon** [comment]
What did you customize?
