### ISSUE TITLE
develop-next - latest - Custom Logo

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#2433]
Hi,

its not possible to delete an uploaded custom logo at /scp/settings.php?t=pages#logos. 

![config](https://cloud.githubusercontent.com/assets/10116166/9369529/27823268-46ca-11e5-812a-386584bd1e89.png)

**Comment by ntozier** [comment]
Why not?
It works in 1.10rc1 and I'm not aware of any changes between it and the tip of dev.
Make sure that you disable the logo your using, as you cannot delete the current if its in use.

**Comment by greezybacon** [comment]
Fixed in b528df5. Thanks
