### ISSUE TITLE
1.10-RC2: Helpdesk Name/Title --> Footer not updated

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket-1.8#2437]
Hi y'all,

just updated our 1.10-RC1 to RC2 and changed the helpdesk name/title. I thought the footer would update too, but seems like it's not updating:

![image](https://cloud.githubusercontent.com/assets/2871833/9378460/eac867ae-4721-11e5-886e-c39329c531c0.png)

This also affects the login screen and the end user portal.

In general we really like the direction in which osTicket 1.10 is moving, but still not totally happy yet with tasks (but will open issues/requests for that too) ;)

Cheers!
Michael

**Comment by greezybacon** [comment]
That's the company name in the footer. Go to settings -> company and change it there

**Comment by Chefkeks** [comment]
Oh what a shame I missed that...

Thanks :D ;)

**Comment by greezybacon** [comment]
No worries, dood
