### ISSUE TITLE
Problems with images

### ISSUE THREAD

**Issue by fernandotschumi** [osTicket/osTicket-1.8#2455]
I attached a picture on a ticket. When I try to download the image from the ticket, the file is invalid. Comparing the original file with the file returned from download, there is a blank line at the beginning of invalid file. If I delete this line the file opens normally. This only occurs with images, other types of files works fine.

**Comment by fernandotschumi** [comment]
I m using version v1.10-rc.2

**Comment by ntozier** [comment]
Please provide more information about your system and configuration.
webserver, PHP, MySQL, with versions, etc.
store in db or on filesystem?

**Comment by fernandotschumi** [comment]
osTicket 	v1.10-rc.2 (231f11e)
Webserver Apache/2.2.15 (CentOS)
MySQL 	5.5.45
PHP 	5.4.44
Store attachments "in the database"

**Comment by fernandotschumi** [comment]
The logo of osTicket is a png file and appears correctly. Other images also appear. The problem only occurs with attached files.

**Comment by greezybacon** [comment]
This usually happens where there is a newline / whitespace at the top of one of the PHP files in the project. Did you happen to edit one of the files and leave whitespace at the top?

**Comment by fernandotschumi** [comment]
It worked, but do not know why. I changed the folder name. Before it was: http://my_domain/support switched to http://my_domain/suporte_test.

Before upgrading to version 1.10 worked well the question of images. There is also the issue of updating the PHP before it was 5.3

**Comment by fernandotschumi** [comment]
I found a new line / white space on top of a php file in a  plugin that I did. Initially taking the space I had not worked. I believe there was some kind of cache for now is working ok independent of the folder name

Thank you
