### ISSUE TITLE
1.10 rc2 Issue - UI: Ticket Task Action Menu

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2456]
![image](https://cloud.githubusercontent.com/assets/5774055/9417028/18e5c1ea-4817-11e5-97a9-f445824a49ef.png)
![image](https://cloud.githubusercontent.com/assets/5774055/9417033/1e9b87d2-4817-11e5-8251-a9b3e2cfca64.png)

**Comment by nfebuary** [comment]
Try this fix: https://github.com/nfebuary/osTicket-1.8/commit/72cc511842664f93f2c91c1efb222a5fa78bd519 
![highlightfix](https://cloud.githubusercontent.com/assets/8247872/9441953/7d6f0774-4a3e-11e5-8f62-8c5770f3610f.png)

**Comment by nfebuary** [comment]
Can someone try the patch in #2461?

**Comment by nfebuary** [comment]
I moved the no-pjax class to <a> technically it's fine in the <li> but it does make more sense in the <a>.

**Comment by jdelhome3578** [comment]
Does the `no-pjax` have an affect on the code somewhere? Just trying to compare to the ticket actions.

**Comment by nfebuary** [comment]
I just tested, I wanted to make sure it didn't have an affect and no-pjax is not required.

**Comment by nfebuary** [comment]
New patch. #2461
