### ISSUE TITLE
v1.10-rc.2 : Knowledgebase : Attachement : More then 1 language : Impossible to select all languages

### ISSUE THREAD

**Issue by tomlaf** [osTicket/osTicket-1.8#2469]
As you can see in the picture below the issue is that the drop zone overlap on the language selection. The zone need to be re-size.
![image](https://cloud.githubusercontent.com/assets/8548490/9481792/58da0b02-4b5b-11e5-905f-e6271793d1e4.png)

**Comment by greezybacon** [comment]
Thanks for reporting this. Could you try the patch in #2484?

**Comment by tomlaf** [comment]
The move to the horizontal correct the issue.

Good day
