### ISSUE TITLE
v1.10-rc.2 : From : After deleting a form it still show up on the Add Custom Form menu

### ISSUE THREAD

**Issue by tomlaf** [osTicket/osTicket-1.8#2470]
For exemple the From gtest has been deleted, it no in the From section of the web site, but it still possible to add them to Help Topic.

![image](https://cloud.githubusercontent.com/assets/8548490/9481908/78deccd4-4b5c-11e5-9b7b-025cd7c11abb.png)
![image](https://cloud.githubusercontent.com/assets/8548490/9481942/dee8cc3c-4b5c-11e5-8e7e-1945569d578f.png)
![image](https://cloud.githubusercontent.com/assets/8548490/9481945/e6a407ca-4b5c-11e5-9e41-1f4ae825cb51.png)
Now in the new topic when submitting with a deleted form the system fail, but on manage From for a ticket it let you add the form, but then you can delete it, but the ticket show the form as part of it now.

**Comment by greezybacon** [comment]
Thanks for reporting this issue. Can you try the patch in #2483?

**Comment by tomlaf** [comment]
Yes it did.
