### ISSUE TITLE
How to reject new tickets coming from email

### ISSUE THREAD

**Issue by BassemN** [osTicket/osTicket-1.8#2481]
Hello,

How can I reject new tickets(not replies) coming from email and force all new tickets to be created from web only?

Thanks

**Comment by greezybacon** [comment]
Add a ticket filter, source="Emails", set the "Reject Ticket" action

**Comment by ntozier** [comment]
version of osTicket?
Admin panel -> Manage -> Ticket Filters -> Add New Filter
filter name: reject all
execution order: 1
tick Stop processing further on match!
Filter Status: active
target channel: emails
Filter Rules:
User / Email Address, Matches Regex, write a regex to match emails.

This article might assist you in writing a regex to match emails.  If you only support one domain you could possibly use a simpler regex.
http://www.regular-expressions.info/email.html

tick Reject Ticket.
canned response: author a canned response explaining why it was rejected, and select it here.

**Comment by BassemN** [comment]
Thank you @greezybacon & @ntozier  I'll try this.

osTicket (v1.9.12)

There is an option called  "Accept All Emails" found under "Email Settings" and on help text you wrote "Accept emails from unknown Users. Unchecking this setting will result in tickets getting rejected." 
Can this do the job?

Thanks,
Bassem

**Comment by BassemN** [comment]
I have another question please. Does Ticket Filters only run on new created tickets or all replies also?
Thanks

**Comment by greezybacon** [comment]
Filters are for new tickets only

**Comment by BassemN** [comment]
@greezybacon thank you.
There is an option called "Accept All Emails" found under "Email Settings" and on help text you wrote "Accept emails from unknown Users. Unchecking this setting will result in tickets getting rejected."  What is this option do?
