### ISSUE TITLE
v1.10.RC.2: Closed Tickets Sort Issue (Inaccurate Results) **CRITICAL**

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#2499]
See attached image.

<img width="969" alt="search" src="https://cloud.githubusercontent.com/assets/4073792/9569756/9224dde8-4f42-11e5-8c04-3bf636609dc2.png">

When sorting closed tickets by "Most Recently Closed", the results start on March 2015. There are at least 300+ tickets from March to August 2015.

**Comment by rowlandan25** [comment]
I have seen this happen as well.  It appears that the system is only sorting the tickets that appear on the page (whether it be 10, 25 or 50), not all of the tickets in the database.

**Comment by C4RLOCO** [comment]
Correct.
The total closed ticket count at the bottom of the table seems to be correct but the sorting is the problem.

---------------------------------

**Comment by C4RLOCO** [comment]
@greezybacon any thoughts?

**Comment by C4RLOCO** [comment]
Folks, we have not heard from you guys for a while.. 
@protich @greezybacon

**Comment by greezybacon** [comment]
Can anyone try the patch in e17a9124e7c59d6de7ae21a8e736740b837badec. It's in #2056 to be merged toward rc3

**Comment by C4RLOCO** [comment]
Hi @greezybacon,
I installed the patch e17a912 and confirm it fixes the Closed Tickets sort issue described in this thread.

I can't wait for RC3 :-)

Thank you very much Sir!
