### ISSUE TITLE
10-RC2 Ticket Filter Bug Fix

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket-1.8#2502]
Fixed a bug that created a javascript error "SyntaxError: expected expression, got ';'"
On line 345 
/include/staff/filter.inc.php
var next = <?php echo $maxi; ?>;
Added qoutes so there is a proper null-string if not the "Add Filter" button fails.
var next = "<?php echo $maxi; ?>";

**Comment by rowlandan25** [comment]
+1 Excellent job!

**Comment by t-oster** [comment]
+1

**Comment by greezybacon** [comment]
This is properly fixed in 37cd404fff47b24cb5a41c992560ae29f5940262 in #2056. The `$maxi` variable is a number and should not be treated as a string.
