### ISSUE TITLE
v1.10-RC.2: Collision Avoidance Issue

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#2504]
I set the collision avoidance duration to 2 minutes (Admin Control Panel > Settings ). However, when I click on any open ticket to add a reply (either public or internal) and as soon as  I start writing the reply the following message appears.

<img width="580" alt="screen shot 2015-08-31 at 8 43 19 am" src="https://cloud.githubusercontent.com/assets/4073792/9578941/68623d1e-4fbc-11e5-8832-f65be04998b8.png">

Clicking on the "Renew" button does not do anything and if I ignore the message and try to Post the reply, the following message appears over and over: "This action requires a lock. Please try again" which prevents any type of future replies as a whole.

**Comment by C4RLOCO** [comment]
By the way, does anyone knows how could I customize the Oscar avatar in the Lock expiring banner?

**Comment by kest874** [comment]
This has been an issue for us for awhile see here: https://github.com/osTicket/osTicket-1.8/issues/2399 

We have yet to find a solution.  You can however set it to 0 as a workaround.

**Comment by C4RLOCO** [comment]
Thanks @kest874 
However, aren't we running into the possibility of corrupting the database if two agents modify the ticket at the same time? or the consequences are not that bad if this scenario happens?

**Comment by jdelhome3578** [comment]
This is a duplicate of #2343

**Comment by greezybacon** [comment]
@C4RLOCO Can you try the patch in #2533?

**Comment by C4RLOCO** [comment]
@greezybacon patch worked as expected. Thank you very much! I assume this is also part of RC3, correct?

Thanks again for all your help!
