### ISSUE TITLE
v1.10-RC.2: Ticket Info Screen missing User phone Number

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#2506]
In the ticket system info view, the User phone number would be a great addition to have. see below.

<img width="949" alt="screen_shot_2015-08-31_at_10_17_25_am" src="https://cloud.githubusercontent.com/assets/4073792/9580831/bcaf622c-4fc9-11e5-8ac1-7c0234f5bf44.png">

**Comment by ntozier** [comment]
Also reported on the forums here:
http://www.osticket.com/forum/discussion/86347/display-phone-number-in-agent-panel-on-ticket-info-1-10-rc2#latest

I can also confirm this behavior.

**Comment by mfelber** [comment]
The code for this field isn't anymore in the ticket-view.inc.php in 1.10. In 1.9.x there was a according section for it. Maybe that section was forgotten during the adjustments for 1.10..

**Comment by greezybacon** [comment]
The phone number was dropped to make room for the user's Organization, which is shown when the user is a member of an organization

**Comment by simon-3t** [comment]
Hello,
I know it is old issue but I also need the phone number in "ticket_info".
If you need just add in include/staff/ticket-view.inc.php :
```
<tr>
                    <th><?php echo __('Phone'); ?>:</th>
                    <td>
                        <span id="user-<?php echo $ticket->getOwnerId(); ?>-phone"><?php echo $ticket->getPhoneNumber(); ?></span>
                    </td>
</tr>
```


after
```
             <tr>
                   <th><?php echo __('Email'); ?>:</th>
                   <td>
                      <span id="user-<?php echo $ticket->getOwnerId(); ?>-email"><?php echo $ticket->getEmail(); ?></span>
                    </td>
              </tr>
```

**Comment by ntozier** [comment]
You mean this?
https://github.com/osTicket/osTicket/pull/4392

**Comment by simon-3t** [comment]
Yes, I spent 1 hour to find the right file and line. I made research on github and google but your issue never showed up. 
I hope it will help other people to find answer with different keywords.

**Comment by DGCupit** [comment]
simon-3t, thanks very much for your simple and clear write-up. Just what I needed.

**Comment by Cm-8** [comment]
UPDATE:

Why not add a function by default that if the phone is present, is shown in the ticket details?
So you don't need to change the file at every osticket update.

Example at line 456 of ..include/staff/ticket-view.inc.php:
```
<!-- ADD PHONE IF PRESENT -->
  <?php if ($user->getPhone()>0) { ?>
    <tr>
      <th> <?php echo __('Phone'); ?>: </th>
      <td>
        <span id="user-<?php echo $ticket->getOwnerId(); ?>-phone"><b><?php echo Format::htmlchars($user->getPhone());?></b>
        </span>
      </td>
    </tr>
  <?php   } ?>
```

Thanks
