### ISSUE TITLE
v1.10: feat requ added collaborators from staff panel (and also autoadded per topic)

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket-1.8#2507]
in staff panel, on "open new ticket" by agente, added possibility to added collaborators from same form ..
And also added a option that for specific topic aded a default per topic collaborators!

And also of course notify to collaborators by email from beginning

**Comment by ntozier** [comment]
duplicate thread
see https://github.com/osTicket/osTicket-1.8/issues/771

**Comment by mckaygerhard** [comment]
ok thanks, so i let opened due my title are more specific and the other not (and so its more easy to me find my proper made issues due i take care of )

**Comment by ntozier** [comment]
Since this references the correct thread, please close this. 
Thanks.

**Comment by mckaygerhard** [comment]
ok i'll doi
