### ISSUE TITLE
Open ticket not returning result and redirecting

### ISSUE THREAD

**Issue by eyalgross** [osTicket/osTicket-1.8#2521]
Hi,

When I create a ticket via open.php I see in the backend that the ticket is created correctly however the "Please Wait! Please wait... it will take a second!" screen is never closed. If I hit refresh it goes away but this is obviously not a solution. *UPDATE* - The screen does go away but after a VERY long time (5 mins) which too is not really a solution.

I've had a bit of a nightmare setting this all up. I thought it was an ajax issue because I had the famous "1" is recommended if AJAX is not working" issue but I changed my server configuration to use php in FastCgi mode instead of an apache module and now this error is gone. I am still however getting the following 404 error in the dev console on the open.php page for the following url "../ajax.draft.phpticket.client.qr68fb55mrh6" so drafts are not being saved.

I am running osTicket on a Digital Ocean droplet with 512mb with the default LAMP stack installed.

I don't want this to be a block to using this otherwise nice piece of software. Any help appreciated.

Cheers.

**Comment by C4RLOCO** [comment]
What osticket version are you using?

**Comment by eyalgross** [comment]
The latest version

**Comment by greezybacon** [comment]
> ... 404 to ... `../ajax.draft.phpticket.client.qr68fb55mrh6`

That's really odd. Are you sure?

Which version is the latest one?
