### ISSUE TITLE
osticket Ver. v1.9.12

### ISSUE THREAD

**Issue by eljagg** [osTicket/osTicket-1.8#2532]
Hi, I am wondering if anyone of you knowledgeable persons could help or guide me here. I have installed osticket ver.v1.9.12  in my work environment, however when I try to add my colleagues email address it (osticket) is not accepting them. I realized that this is as a result of the email type/format eg.
anyone@mywork.com.jm. I get this "Valid email is required"
When I used a gmail type email eg anyone@gmail.com I do not have any issue. Please help.All of my colleagues emails are tied in with Active Directory.

**Comment by greezybacon** [comment]
Disable "Email Address Verification" in Admin Panel -> Settings -> Emails

**Comment by eljagg** [comment]
Thank you. it worked.
