### ISSUE TITLE
v1.10-RC.2: Lock status not shown on tickets

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#2536]
When a different agent has a ticket locked. The system does not show the locked ticket icon/status in the Open ticket list/view.

**Comment by t-oster** [comment]
I can confirm this issue.

**Comment by greezybacon** [comment]
Are you sure? In v1.10, you have to start typing in the response to actually acquire the lock. The tip of `develop-next` has a "Lock Semantics" setting in the Settings -> Tickets page, which, when set to "Lock on view" allows the lock system to work like it did in v1.9

**Comment by C4RLOCO** [comment]
Thanks @greezybacon 
After explaining the new behavior in v1.10 when starting to typing a response I can confirm that is not an issue. I was able to see the lock when I typed and simultaneously I opened a private browser session using a different agent account. The lock was there.
