### ISSUE TITLE
OsTicket 1.9.12 with Google Mail (IMAP and POP)

### ISSUE THREAD

**Issue by jccastros** [osTicket/osTicket-1.8#2562]
Domain Name: casalconsultores.com
Problem Description: 
We're using Google Mail for casalconsultores.com, and have setup the MX records correctly.  We're receiving email / sending email no problems from the web based client.  

Email is being received and sent no problem using Thunderbird with the following settings:

https://support.google.com/mail/bin/answer.py?hl=en&answer=13287

When we try to save the email settings in OS Ticket based on the guide above, SMTP works no problem, but IMAP and POP doesn't work.  The page tries to save the email settings and says "connecting" for about 1 minutes then shows a Internal Server Error.  IMAP and POP work fine with the same settings in Thunderbird. 

We've contacted Hostinger, and made sure ports 993, and 995 are open incoming / outgoing.  PHP has SSL support.  Others say they've had problems setting up gmail on Hostinger, but were able to get it working by moving servers.  

Has anyone got POP or IMAP working with gmail and OSTicket, or ran across similar problems?  Any advice or tips would be appreciated.

Thanks!
![errorosticket](https://cloud.githubusercontent.com/assets/14318427/9921514/93cde3de-5cde-11e5-9c3a-1041c19edfea.png)

**Comment by BassemN** [comment]
I have the same problem.

**Comment by harishbsrinivas** [comment]
We have the same  problem as well. Setup OTRS V 1.9.12 from scratch everything works except for email (using google hosted email)

**Comment by ntozier** [comment]
OTRS?  This is osTicket, not OTRS.

**Comment by gemini1976** [comment]
it's the same happening from my installation. osTicket 1.9.12 and when i'm configuring the emails
IMAP:
Username: admin@gmail.com
Password: ********
Hostname: imap.gmail.com
Port: 993
Mail Box Protocol: IMAP or IMAP+SSL

SMTP:
Hostname: smtp.gmail.com
Port Number: 587
Authentication Required: enable

I already enabled IMAP settings from my gmail account but it shows these error:
[CLOSED] IMAP connection broken (server response)
or
Can not authenticate to IMAP server:

Can someone guide me where I'm having a mistake?

**Comment by ntozier** [comment]
Please help us to help you by reading and following the posting guidelines located in this thread: http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance .  The more information you give us the better we will be able to assist you. Thank you.

**Comment by jccastros** [comment]
Hello,

My problem was solved by changing server . Hostinger said there was no problem . But the fact is that when testing osTicket on a dedicated server works perfectly . So I've been forced to hire one and hence the application host .

I hope that helps.

Greetings and thank you.
