### ISSUE TITLE
v.1.10-RC.2: Missing Buttons in Ticket View after re-assignment 

### ISSUE THREAD

**Issue by C4RLOCO** [osTicket/osTicket-1.8#2567]
After a ticket is re-assinged to a member of a different department, the following buttons are missing: Assign, Transfer, Edit. This also happens logged as Admin.

What affect us at this moment is that a ticket cannot be transferred to a different agent.

![screen_shot_2015-09-17_at_2_06_35_pm](https://cloud.githubusercontent.com/assets/4073792/9941867/017c5502-5d46-11e5-87cc-bd96bf01eb8b.png)

**Comment by jdelhome3578** [comment]
@greezybacon I have noticed that admin does not get access to all departments

**Comment by greezybacon** [comment]
@jdelhome3578 that has been the case since v1.7 I believe. All users must have explicit access to any department whose tickets should be visible

**Comment by C4RLOCO** [comment]
But, if you want to segment users by departments? How to achieve that? For example: I need one agent to only have visibility to his department but I need him to transfer tickets to a different department when required.

**Comment by greezybacon** [comment]
That's the idea of the new access control system in v1.10. You can define "Roles" and the roles define the permissions (like "Ticket / Transfer"). Then the department membership has a role assignment, so you can define what permissions are available for which department.

Is that the issue here? Are you missing the transfer permission for the newly-assigned department?

**Comment by C4RLOCO** [comment]
@greezybacon Correct. That is the issue here. The transfer permission is missing for the newly-assigned department.

**Comment by mikechristopher** [comment]
I was unable to replicate this in RC2 - an agent with access to that newly assigned department was able to transfer it back to a different department.  The agent without access to the department loses all permissions to be able to move it.

**Comment by C4RLOCO** [comment]
Right, the problem is that agent that loses all permissions to be able to move it. How can he move it to the correct department? Say it was mistakenly assigned to him and he wants to assigned back to the default department yet this staff does not need to have access/visibility to all tickets under the default department?

**Comment by jdelhome3578** [comment]
@C4RLOCO So you want an Undo Button? @greezybacon That could be helpful.

**Comment by C4RLOCO** [comment]
Well an Undo button would be helpful of course. But it would leave a particular scenario where the system workflow could stall. For example: what would happen if after some time is decided that the ticket would have to be transferred to a different department? Then the agent who has lost all the permissions to move it won't be able to reassign it to a different department to continue the workflow. Worst yet, not even the admin would be able to move it (see initial screenshot taken from the admin account).

I believe the agent should have the right to move it to any other internal or public department to guarantee a smooth workflow between tickets assignments (either between agents and departments)

**Comment by greezybacon** [comment]
So if you add the assign, transfer, and edit permissions, do the buttons show up again?

**Comment by jdelhome3578** [comment]
@C4RLOCO I agree with @greezybacon you need to setup and edit your permissions and roles to fill your needs. The system will do what you want but you have to set it up.

**Comment by C4RLOCO** [comment]
That is correct if I add the assign, transfer, and edit permissions,  the buttons are not showing up again. Point in case the screen shot taken from admin account at the top of this issue/post.

**Comment by jdelhome3578** [comment]
@C4RLOCO I do not have this issue. Please make sure the user has the permissions for each department.

**Comment by C4RLOCO** [comment]
I'm certain the permissions are set correctly. I will write a step-by-step process so you guys can replicate it. I'll work on it sometime today.

**Comment by C4RLOCO** [comment]
Soooo.
When working on the step-by-step guide I came across on something called "Extended Access" under 
"Primary Department and Role".. I realized the admin account did not have extended access to the new internal department created.

Thank you everybody for your input!

**Comment by protich** [comment]
It's worth pointing out that Admin Panel Access just gives the agent access to Admin Panel... __no special privilege is implied__. Ticket and tasks access is strictly based on assigned departments (primary and extended) and assignment (team & individual). What the agent can do (permissions) depends on the assigned role for the department(s) in question.

**Comment by C4RLOCO** [comment]
Thanks @protich 
This is a very good observation as I assumed an Admin account would have super-user rights/permission across the system.
