### ISSUE TITLE
Invalid email address cdos.ie

### ISSUE THREAD

**Issue by bcowman** [osTicket/osTicket-1.8#2573]
Hi,

v1.9.12 (19292ad)

I'm trying to update an agent account.  When I save I get an invalid email address.  I can use any email address except anything with the domain cdos.ie!

e,g, email@cdos.com works, email@cdos.ie doesn't.

**Comment by Chefkeks** [comment]
Make sure cdos.ie is a valid domain and has a valid A name, cname and/or MX record. Otherwise just disable email verification under admin panel > settings > email > email verification
