### ISSUE TITLE
Cursor losing focus when typing in the response box

### ISSUE THREAD

**Issue by gpls-dev** [osTicket/osTicket-1.8#2632]
This affects OSTicket 1.9.11 and happens on my Ubuntu 15.04 station running Firefox 41.0.  When entering a response, if I backspace after a space, my cursor disappears.  For example, I type, make a typo then hit the spacebar, if I hit the backspace key, my cursor is no longer visible and I'm no longer able to type.  I'm seeing this on all three of my Ubuntu workstations where I use OSTicket.  My colleagues using Firefox on Windows have not been able to reproduce this, for what it's worth.

**Comment by ntozier** [comment]
This is a problem with the WYSIWYG editor used to enter text and has been mentioned before, making this a duplicate issue report.  Please see these and close this:
https://github.com/osTicket/osTicket-1.8/issues/2373
https://github.com/osTicket/osTicket-1.8/issues/2322
https://github.com/osTicket/osTicket-1.8/issues/1683

**Comment by gpls-dev** [comment]
Okay - didn't see those other bugs.  Thanks for the quick response.
