### ISSUE TITLE
1.9.12 Problem with status when installing in different language

### ISSUE THREAD

**Issue by vrowdy** [osTicket/osTicket-1.8#2646]
See also #1852 , but since no developer has responded to that issue yet and my comment there would probably go unnoticed, I am opening up a new issue.

The problem is as follows: when installing osTicket in a different language, something goes wrong with ticket status database table creation. The statuses are there in the admin panel, but you cannot change a ticket to another status. The status menu is just empty. This goes for the Dutch language pack as well as some other languages. More detailled:

This problem is also occuring with the Dutch language pack.

During installation, I chose to install everything in Dutch. I do get the correct ticket statuses (in Dutch) in the right place in the Admin-panel.
However, I am unable to change any ticket to any other status than 'open'. Also, the 'default status for new tickets'-setting also only shows 'open'.

When I install osTicket in English, this problem doesn't occur. But as stated before, this requires a lot of translation afterwards because a lot of strings are setup in the database during installation.

I'm using osTicket 1.9.12. This seems to be a critical bug in the language-pack support. Perhaps something should be change in the translation file, but something should definately be change in osTicket installation as well, so that even when the translation file is missing some info, the installation still is performed correctly.
Currenty, it is impossible to use osTicket in Dutch.

I hope this issue can be resolved soon.

**Comment by vrowdy** [comment]
I managed to fix it by myself.
The problem is as follows:
In the database table ticket_status there is a field 'state'. That filed contains certain descriptions in English, for example 'closed'. These fields should never be translated - they are internal fields referenced by PHP code. They are the keys by which osTicket knows which state is actually closed, because the text shown to the user is translated.

Solution is resetting the values in the field 'state' back to their original English values.

So there a are two problems: the translators shouldn't have translated this field, but more importantly, during the creation of the database (during setup), osTicket should not use these translated values even if they are provided by the language pack.

Also, checks should be made to make sure this doesn't happen as well for other tables / values.

**Comment by mckaygerhard** [comment]
this problem are present since firts version of osticket 1.9 and well reported but still are not resolved aprat the numerous reclaims about

**Comment by ntozier** [comment]
Please do not cross post.
Please close this thread in favor of the existing issue report: https://github.com/osTicket/osTicket-1.8/issues/1852

**Comment by ntozier** [comment]
Thanks @vrowdy :)
