### ISSUE TITLE
1.9.12 replying a ticket from different staff

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket-1.8#2650]
If a ticket is assigned to "operator1" and "operator2" reply to the ticket , the email to the user has this in the body 

"Operator1 has updated the ticket with this response ..."

should i change the variable %{ticket.staff} used in the template with another variable ?

thank you

**Comment by protich** [comment]
You're using the wrong variable it should be ``%{staff}`` -- ``%{ticket.staff}`` refers to assigned agent, not the respondent.
