### ISSUE TITLE
v1.10-rc.2 (231f11e) Creating of Ticket Filters not working

### ISSUE THREAD

**Issue by pratikvav** [osTicket/osTicket-1.8#2653]
OsTicket version v1.10-rc.2 (231f11e)
When you try to create a ticket filter and click on Add Rule it just will not work. Seems something not right. Please check

**Comment by pratikvav** [comment]
OsTicket version v1.10-rc.2 (231f11e)

The error seems to be in JS query which is not loading for some reason kindly check the attached screenshot.
![screenshot1](https://cloud.githubusercontent.com/assets/15137365/10533840/7b111a9e-73ec-11e5-95cb-7fa2aa552beb.jpg)

**Comment by bhiscox** [comment]
Check out this: https://github.com/osTicket/osTicket-1.8/issues/2502

**Comment by pratikvav** [comment]
Thanks we edited the file and now it works.
