### ISSUE TITLE
Form Field Config Issues

### ISSUE THREAD

**Issue by rachelsupport** [osTicket/osTicket-1.8#2661]
The Config option on my form fields is not working. I have tried in multiple browsers with the same result. When I click on Config, a small blank, rectangular window opens wtih a gray overlay 
![screenshot](https://cloud.githubusercontent.com/assets/13238969/10589977/578d9dee-767c-11e5-8173-356536e72184.png)
and nothing else happens.

**Comment by greezybacon** [comment]
Are you using nginx? Could you check the Admin Panel -> Dashboard -> System Information to check your setup?

**Comment by rachelsupport** [comment]
Hi,

No I am not. Please see attached for my System Information.
![screenshot2](https://cloud.githubusercontent.com/assets/13238969/10608481/379add6c-770d-11e5-813a-e2d3473dfd92.png)

**Comment by greezybacon** [comment]
Perhaps you can try setting `cgi.fix_pathinfo` to 1 in your php.ini, as the page recommends

**Comment by rachelsupport** [comment]
Where can I find the php.ini?

**Comment by greezybacon** [comment]
Sorry there's no single answer to that question. I suppose you're using a hosting solution? In such a case it would be in the control panel for you website. If you're using IIS, it should be in Program Files, otherwise in `/etc`.

**Comment by rachelsupport** [comment]
I'm using GoDaddy...so it appears that I need to create a php5.ini file in my webroot.

**Comment by rachelsupport** [comment]
Created the php5.ini file and changed the cgi.fix_pathinfo to 1. It is working properly now.

**Comment by greezybacon** [comment]
Good deal. Thanks for reporting back
