### ISSUE TITLE
Attachment issues FAQ

### ISSUE THREAD

**Issue by telx85** [osTicket/osTicket-1.8#2668]
Its not critical, because I have a workaround, but when I make a new FAQ and attach a file it uploads fine and looks like it will work, but then clicking Add FAQ makes the FAQ but no attachment.

If I edit the FAQ and then upload the file and click Save Changes it works as expected.

Can anyone else replicate this issue?

Logs show nothing, but I am using shared hosting so I might not be getting all the logs.
I've turned on debugging for logging, also using Chrome Developer tools and all it says is:

'webkitURL' is deprecated. Please use 'URL' instead.
![osticket_details](https://cloud.githubusercontent.com/assets/2740134/10628488/93914390-77f8-11e5-810a-a139e12a8415.png)

**Comment by mfelber** [comment]
Seems to be duplicate https://github.com/osTicket/osTicket-1.8/issues/2606

**Comment by telx85** [comment]
Agreed, should I delete this?

**Comment by mfelber** [comment]
I think the usual procedure in this case is to close the issue.
