### ISSUE TITLE
Develop-next: Installation Error

### ISSUE THREAD

**Issue by c0nfused** [osTicket/osTicket-1.8#2670]
Running through the installation for the **develop-next** branch and received the following error. The database gets populated, but the configuration file does not get written. 
Does not go any further..

`Fatal error: Call to a member function getDbTimezone() on a non-object in /home/osticket-devnext/public_html/osTicket-1.8/include/class.misc.php on line 99`

Using PHP version 5.4.44 with MySQL version 5.0.95

**Comment by mfelber** [comment]
Seems to be a duplicate issue https://github.com/osTicket/osTicket-1.8/issues/2642#issuecomment-149577071
