### ISSUE TITLE
v1.10-rc.2-135-g1aaa313 - Add New Agent Does Not Autofill Name or Email Address. Only Phone Number. LDAP Enabled.

### ISSUE THREAD

**Issue by goobersmooch** [osTicket/osTicket-1.8#2672]
When I add a new agent from Admin Panel —> Agents —> Add New Agent, i type the username in the username field. It pulls the name from ldap, i click on the blue name and it auto fills the phone numbers, but not the name or email address fields.

I have the LDAP Authentication and Lookup plugin installed and configured properly.
Below are screenshots of what i am talking about. Is it supposed to only pull the phone numbers from LDAP? I really want it to auto fill the phone numbers AND the name and email address fields as well.

![ldapautofill](https://cloud.githubusercontent.com/assets/15216195/10667659/08fd40ac-789e-11e5-8686-0c99d37622c9.jpeg)
![ldapautofill2](https://cloud.githubusercontent.com/assets/15216195/10667660/08ffcae8-789e-11e5-8fdf-c38879f3872d.jpeg)

And here is my server info:

![screen shot 2015-10-22 at 9 24 10 am](https://cloud.githubusercontent.com/assets/15216195/10667788/d0ccacc6-789e-11e5-842a-acf474858043.png)

**Comment by kest874** [comment]
I can confirm this is an issue from the tip, even with https://github.com/osTicket/osTicket-1.8/pull/2600

**Comment by philbertphotos** [comment]
I fixed it check here  #2574

**Comment by goobersmooch** [comment]
I can confirm that #2574 fixes the issue.

**Comment by Chefkeks** [comment]
Out of curiosity and apart from #2574 has this been fixed officially, e.g. via new commit by @greezybacon or merged pull request from @philbertphotos ?

**Comment by goobersmooch** [comment]
@philbertphotos could you please create a pull request so we can get this fix merged into the develop-next branch? Thanks! :)
