### ISSUE TITLE
Cannot create a new task

### ISSUE THREAD

**Issue by colonelpopcorn** [osTicket/osTicket-1.8#2682]
I am having trouble creating a new task. I downloaded the latest developer preview from the osTicket website. I tweaked the code per patch #2533 and I've renamed ost-sampleconfig to ost-config. Now, when I go to try and create a task I can enter all the pertinent information but when I click create task it just reloads the page. It doesn't seem to be a proper refresh, but it doesn't create my ticket when I come back into it. I checked my DB and the tasks I've created so far seem to have put their titles in the database, but all the details seem to have been removed. Is this because the tasks and workflow feature is not yet finished? See the screenshots below.
![taskopen](https://cloud.githubusercontent.com/assets/13068221/10759316/1a2ee946-7c8d-11e5-8eed-10f1e0fece89.png)
![noopentasks](https://cloud.githubusercontent.com/assets/13068221/10759318/1a2fdc3e-7c8d-11e5-9c64-4ce9ad138a47.png)
![tasks](https://cloud.githubusercontent.com/assets/13068221/10759317/1a305466-7c8d-11e5-8e9b-32afb77f0f5f.png)

**Comment by kest874** [comment]
You you have any errors in the system log?  Tasks are working as they should in my test system.

**Comment by colonelpopcorn** [comment]
Are you talking about my server logs or the system logs in osTicket's admin panel?

![image](https://cloud.githubusercontent.com/assets/13068221/10769751/102dacda-7cbe-11e5-8a71-dbaafc51be24.png)

Nothing unusual here.

**Comment by ntozier** [comment]
version of osticket?
webserver software?  
PHP version?
webserver logs?
php logs?

**Comment by colonelpopcorn** [comment]
v1.10-rc.2 (231f11e)
Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11
5.6.11

XAMPP's Error.log
[Thu Oct 22 13:33:39.241373 2015] [core:notice] [pid 5516:tid 248] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Thu Oct 22 13:33:39.244376 2015] [mpm_winnt:notice] [pid 5516:tid 248] AH00418: Parent: Created child process 4500
[Thu Oct 22 13:33:40.022075 2015] [ssl:warn] [pid 4500:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Oct 22 13:33:40.235267 2015] [ssl:warn] [pid 4500:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Oct 22 13:33:40.282309 2015] [mpm_winnt:notice] [pid 4500:tid 260] AH00354: Child: Starting 150 worker threads.
[Fri Oct 23 13:10:46.932860 2015] [ssl:warn] [pid 13528:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Oct 23 13:10:47.031850 2015] [core:warn] [pid 13528:tid 248] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Oct 23 13:10:47.166836 2015] [ssl:warn] [pid 13528:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Oct 23 13:10:47.636789 2015] [mpm_winnt:notice] [pid 13528:tid 248] AH00455: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11 configured -- resuming normal operations
[Fri Oct 23 13:10:47.636789 2015] [mpm_winnt:notice] [pid 13528:tid 248] AH00456: Apache Lounge VC11 Server built: Jul 12 2015 10:56:48
[Fri Oct 23 13:10:47.636789 2015] [core:notice] [pid 13528:tid 248] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Fri Oct 23 13:10:47.639789 2015] [mpm_winnt:notice] [pid 13528:tid 248] AH00418: Parent: Created child process 9076
[Fri Oct 23 13:10:48.351718 2015] [ssl:warn] [pid 9076:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Oct 23 13:10:48.553697 2015] [ssl:warn] [pid 9076:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Fri Oct 23 13:10:48.598693 2015] [mpm_winnt:notice] [pid 9076:tid 260] AH00354: Child: Starting 150 worker threads.
[Mon Oct 26 16:11:47.097874 2015] [ssl:warn] [pid 15108:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:11:47.228887 2015] [core:warn] [pid 15108:tid 248] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Oct 26 16:11:47.390903 2015] [ssl:warn] [pid 15108:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:11:47.899954 2015] [mpm_winnt:notice] [pid 15108:tid 248] AH00455: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11 configured -- resuming normal operations
[Mon Oct 26 16:11:47.899954 2015] [mpm_winnt:notice] [pid 15108:tid 248] AH00456: Apache Lounge VC11 Server built: Jul 12 2015 10:56:48
[Mon Oct 26 16:11:47.899954 2015] [core:notice] [pid 15108:tid 248] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Oct 26 16:11:47.902954 2015] [mpm_winnt:notice] [pid 15108:tid 248] AH00418: Parent: Created child process 14140
[Mon Oct 26 16:11:48.618026 2015] [ssl:warn] [pid 14140:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:11:48.827047 2015] [ssl:warn] [pid 14140:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:11:48.876052 2015] [mpm_winnt:notice] [pid 14140:tid 260] AH00354: Child: Starting 150 worker threads.
[Mon Oct 26 16:29:07.629114 2015] [mpm_winnt:notice] [pid 15108:tid 248] AH00428: Parent: child process 14140 exited with status 1073807364 -- Restarting.
[Mon Oct 26 16:55:22.955551 2015] [ssl:warn] [pid 8540:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:55:23.040556 2015] [core:warn] [pid 8540:tid 248] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Oct 26 16:55:23.193565 2015] [ssl:warn] [pid 8540:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:55:23.315572 2015] [mpm_winnt:notice] [pid 8540:tid 248] AH00455: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11 configured -- resuming normal operations
[Mon Oct 26 16:55:23.315572 2015] [mpm_winnt:notice] [pid 8540:tid 248] AH00456: Apache Lounge VC11 Server built: Jul 12 2015 10:56:48
[Mon Oct 26 16:55:23.315572 2015] [core:notice] [pid 8540:tid 248] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Mon Oct 26 16:55:23.318572 2015] [mpm_winnt:notice] [pid 8540:tid 248] AH00418: Parent: Created child process 8732
[Mon Oct 26 16:55:24.168620 2015] [ssl:warn] [pid 8732:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:55:24.389633 2015] [ssl:warn] [pid 8732:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Oct 26 16:55:24.440636 2015] [mpm_winnt:notice] [pid 8732:tid 260] AH00354: Child: Starting 150 worker threads.
[Tue Oct 27 08:11:24.567881 2015] [ssl:warn] [pid 2364:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 27 08:11:24.633782 2015] [core:warn] [pid 2364:tid 248] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Oct 27 08:11:24.784556 2015] [ssl:warn] [pid 2364:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 27 08:11:25.284804 2015] [mpm_winnt:notice] [pid 2364:tid 248] AH00455: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11 configured -- resuming normal operations
[Tue Oct 27 08:11:25.285803 2015] [mpm_winnt:notice] [pid 2364:tid 248] AH00456: Apache Lounge VC11 Server built: Jul 12 2015 10:56:48
[Tue Oct 27 08:11:25.285803 2015] [core:notice] [pid 2364:tid 248] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Oct 27 08:11:25.287800 2015] [mpm_winnt:notice] [pid 2364:tid 248] AH00418: Parent: Created child process 3812
[Tue Oct 27 08:11:26.074618 2015] [ssl:warn] [pid 3812:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 27 08:11:26.299280 2015] [ssl:warn] [pid 3812:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Oct 27 08:11:26.358192 2015] [mpm_winnt:notice] [pid 3812:tid 260] AH00354: Child: Starting 150 worker threads.
[Wed Oct 28 08:13:00.168378 2015] [ssl:warn] [pid 7516:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Oct 28 08:13:00.228366 2015] [core:warn] [pid 7516:tid 248] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Wed Oct 28 08:13:00.354341 2015] [ssl:warn] [pid 7516:tid 248] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Oct 28 08:13:00.784255 2015] [mpm_winnt:notice] [pid 7516:tid 248] AH00455: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.11 configured -- resuming normal operations
[Wed Oct 28 08:13:00.784255 2015] [mpm_winnt:notice] [pid 7516:tid 248] AH00456: Apache Lounge VC11 Server built: Jul 12 2015 10:56:48
[Wed Oct 28 08:13:00.784255 2015] [core:notice] [pid 7516:tid 248] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Wed Oct 28 08:13:00.787254 2015] [mpm_winnt:notice] [pid 7516:tid 248] AH00418: Parent: Created child process 1084
[Wed Oct 28 08:13:01.469118 2015] [ssl:warn] [pid 1084:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Oct 28 08:13:01.651081 2015] [ssl:warn] [pid 1084:tid 260] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Oct 28 08:13:01.690074 2015] [mpm_winnt:notice] [pid 1084:tid 260] AH00354: Child: Starting 150 worker threads.

PHP Logs:
[20-Aug-2015 21:45:11 Europe/Berlin] PHP Warning:  include(lang/1%00'=1.php): failed to open stream: No such file or directory in C:\xampp\security\htdocs\index.php on line 12

[20-Aug-2015 21:45:11 Europe/Berlin] PHP Warning:  include(): Failed opening 'lang/1%00'=1.php' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\security\htdocs\index.php on line 12

[20-Aug-2015 21:45:11 Europe/Berlin] PHP Notice:  Undefined variable: TEXT in C:\xampp\security\htdocs\index.php on line 13

[20-Aug-2015 21:45:19 Europe/Berlin] PHP Warning:  include(lang/1%00'=1.php): failed to open stream: No such file or directory in C:\xampp\security\htdocs\index.php on line 12

[20-Aug-2015 21:45:19 Europe/Berlin] PHP Warning:  include(): Failed opening 'lang/1%00'=1.php' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\security\htdocs\index.php on line 12

[20-Aug-2015 21:45:19 Europe/Berlin] PHP Notice:  Undefined variable: TEXT in C:\xampp\security\htdocs\index.php on line 13

[22-Oct-2015 14:25:41 UTC] PHP Fatal error:  Class 'TicketModel' not found in C:\xampp\htdocs\osticket\include\class.orm.php on line 123

[22-Oct-2015 14:25:47 UTC] PHP Fatal error:  Class 'TicketModel' not found in C:\xampp\htdocs\osticket\include\class.orm.php on line 123

[22-Oct-2015 14:25:50 UTC] PHP Fatal error:  Class 'TicketModel' not found in C:\xampp\htdocs\osticket\include\class.orm.php on line 123

[22-Oct-2015 14:26:03 UTC] PHP Fatal error:  Class 'TicketModel' not found in C:\xampp\htdocs\osticket\include\class.orm.php on line 123

[22-Oct-2015 14:26:04 UTC] PHP Fatal error:  Class 'TicketModel' not found in C:\xampp\htdocs\osticket\include\class.orm.php on line 123

[22-Oct-2015 14:26:06 UTC] PHP Fatal error:  Class 'TicketModel' not found in C:\xampp\htdocs\osticket\include\class.orm.php on line 123

**Comment by colonelpopcorn** [comment]
I'm such a goober...when I gave myself access to other departments all my tasks showed up.
![image](https://cloud.githubusercontent.com/assets/13068221/10818583/38be2c04-7e19-11e5-8d89-80e736e732cb.png)
