### ISSUE TITLE
v1.10-rc.2-135-g1aaa313 - Email processing issue with new email to existing ticket from agent

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket-1.8#2691]
Found an issue, when an assigned agent replies to an existing ticket via email the message is posted correctly.

bug: When an agent sends a new mail with [#030000] in the subject a new ticket is created instead

If the enduser replies to and existing ticket via email the message is posted correctly.
If the enduser sends a new mail with [#030000] in the subject the message is posted correctly.

**Comment by ntozier** [comment]
I do not think that this is a bug.  
The agent doesn't own the ticket, and is not a collaborator.  
Since the email has a new message-id it is not considered the same ticket.
The agent needs to reply to a system generated email or be a collaborator on the ticket for it to update.

**Comment by kest874** [comment]
Ok, make perfect sense now, it's working as designed.
