### ISSUE TITLE
Ticket via Email: Same sender, different name

### ISSUE THREAD

**Issue by temkretz** [osTicket/osTicket-1.8#2698]
I just noticed that when you create tickets via email and the emails have the same FROM address but different FROM names e.g. Hans Wurst <mymail@example.org> and Peter Pan <mymail@example.org> osTicket detects them as different users but auto-assigns the first name it can associate with the FROM address.
The result is that I have all my tickets labels with the same name but they were sent with different names.
Any solution for this?

**Comment by ntozier** [comment]
Yes.  Do not use multiple email addresses for the same person. 
Each user should have a unique email.

**Comment by temkretz** [comment]
okay, thanks for the quick response!
