### ISSUE TITLE
How can an agent see just his department tickets?

### ISSUE THREAD

**Issue by alirezastack** [osTicket/osTicket-1.8#2717]
Is there a way an agent see just his department tickets not all tickets?

**Comment by ssellmeier** [comment]
Hello,

you will need to do the following:
 * Create a group with the desired ticket-permissions and the department you want the user to see tickets of
 * Create an account with type "agent" (not Administrator!), select the previously created group and also the department as "main-department"

The user is now only able to see the tickets of this department.
