### ISSUE TITLE
How to send ticket reply from agent email address?

### ISSUE THREAD

**Issue by alirezastack** [osTicket/osTicket-1.8#2721]
When an agent reply to a ticket it is sent from the main email address (i.e. support@example.com), but I want it to be sent from agent's email address. I searched throughly, but couldn't find a way to config this settings. Does OsTicket support this configurations?

**Comment by mfelber** [comment]
My understanding is that this is not possible. Only departement email adresses could be used for outgoing mails. 

In the next major release 1.10 it will be possible to use the agents "name" on replies (but still not their email address):
https://github.com/osTicket/osTicket-1.8/pull/2700
