### ISSUE TITLE
1.9.12 - When deleting a ticket the attachments won't be deleted

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket-1.8#2724]
I have noticed that when you delete a ticket the attachments from the corresponding ticket are still in the database. This also occurs when you use the file storage plugin and store the attachments in the filesystem (then the attachments are still stored in the filesystem)

I got no errors in my web server error log or in the osticket system log.
I have tested it with my production and my testing environments:

Hosted Debian Squeeze 2.6.18
Apache 2.2.16
PHP Version 5.5.30 (mod_php)
MySQL Version 5.5.44

XAMPP on Windows 7
osTicket v1.9.12 
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14
Maria DB 10.0.17
PHP Version 5.6.14

Bitnami LAMP-Stack-VM
Apache 2.4.12
MySQL Version 5.6.25
PHP Version 5.5.27

I think the popup before you confirm the delete action implies that they will be deleted:
![delete](https://cloud.githubusercontent.com/assets/5539456/11114026/aac91706-8921-11e5-9d3c-8993611e0bb1.jpg)

Am I misinterpreting this dialogue or is this a bug (that the attachments will not be deleted)?

**Comment by infectormp** [comment]
https://github.com/osTicket/osTicket-1.8/issues/1966#issuecomment-93736718
https://github.com/osTicket/osTicket-1.8/issues/1966#issuecomment-94456719

**Comment by mfelber** [comment]
Ah, ok I understand :-)

Thank you @infectormp for the hint!
