### ISSUE TITLE
Editor backspace problem?

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket-1.8#2744]
Maybe it is me or Mozilla/Chrome but for long time the editor when replying a ticket from the back-end give me problem (have not used the front-end). When writing and then use backspace it often wont delete anything, and sudden it delete in the top or another place. Sometime it wont go to a new line when hit enter. The only way to fix it is to use the "code" viewer/editor and fix it in html.

**Comment by ntozier** [comment]
please see
https://github.com/osTicket/osTicket-1.8/issues/2373

This appears to be a duplicate report, please close it.

**Comment by gitfve** [comment]
Where to get a fix for the problem, I use v1.9.12?
Where find "Redactor"
