### ISSUE TITLE
How to see ticket history, reply to ticket and so on from API?

### ISSUE THREAD

**Issue by alirezastack** [osTicket/osTicket-1.8#2746]
I have seen that there is a ticket creation api method to create ticket via API. The question is how to have an API that could return ticket history for a specific user? I couldn't find any solution for it.

**Comment by ntozier** [comment]
I would do that in at:
osticket.com/forums
The Suggestions and Feed Back section.

**Comment by alirezastack** [comment]
Thank you. Sorry for asking question in an inappropriate place.
http://osticket.com/forum/discussion/86866/how-to-see-ticket-history-reply-to-ticket-and-so-on-from-api
