### ISSUE TITLE
Create Ticket with Email

### ISSUE THREAD

**Issue by MelikaAF** [osTicket/osTicket-1.8#2759]
Hello
I Hope Someone Can Help Me,
I Set Up osTicket (v1.9.12) and Outgoing Emails working well; emails notify agent, admin and department manager when new ticket create , and notify them when ticket close but i have problem with incoming Emails , i cant create ticket with email or reply tickets with mail.
in fact I want the functionality where the system should automatically create a ticket if my client sends an email to : support@mydomain.com and also can reply to emails and can see my reply in ticket in osTicket.

Kindly help me at the earliest.

Thanks a lot
Melika

**Comment by ntozier** [comment]
Then you should probably post at: 
osticket.com/forum/

You should read this thread: http://www.osticket.com/forum/discussion/77765/please-read-before-requesting-assistance before requesting assistance.  You also will probably want to read this wiki article: http://osticket.com/wiki/POP3/IMAP_Setting_Guide

**Comment by MelikaAF** [comment]
Thank You So Much
