### ISSUE TITLE
DB Error #1062

### ISSUE THREAD

**Issue by Demy1992** [osTicket/osTicket-1.8#2770]
Hi, I'm new at this. Sorry for my bad English. I had this problem yesterday (my version is 1.9.12)

[INSERT INTO ost_draft SET `namespace`='ticket.client.jlfvc1sqrvc7' ,body='' ,staff_id='0' ,created=NOW()]

Duplicate entry '0' for key 'PRIMARY'<br />
<br />
---- Recular ----<br />
#0 (raíz)/include/mysqli.php(177): osTicket->logDBError('DB Error #1062', '[INSERT INTO os...')<br />
#1 (raíz)/include/class.draft.php(93): db_query('INSERT INTO ost...')<br />
#2 (raíz)/include/class.draft.php(111): Draft->save(0, Array, Array)<br />
#3 (raíz)/include/ajax.draft.php(22): Draft->create(Array, Array)<br />
#4 (raíz)/include/ajax.draft.php(148): DraftAjaxAPI->_createDraft(Array)<br />
#5 [internal function]: DraftAjaxAPI->createDraftClient('ticket.client.j...')<br />
#6 (raíz)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#7 (raíz)/include/class.dispatcher.php(38): UrlMatcher->dispatch('ticket.client.j...', Array)<br />
#8 (raíz)/include/class.dispatcher.php(120): Dispatcher->resolve('ticket.client.j...', Array)<br />
#9 (raíz)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/ticket.c...', NULL)<br />
#10 (raíz)/ajax.php(49): Dispatcher->resolve('/draft/ticket.c...')<br />
#11 {main}

The error is spaming all the time. Can I stop the SPAM (via code) or can I solve it?

Greetings :)

**Comment by ntozier** [comment]
You can try dropping the contents of the ost_draft table. The error literally says I tried to add this record as #0, and it already exists.

**Comment by Demy1992** [comment]
Nothing changed. When I create a ticket the System spam me this message:

Unable to save draft. Refresh the current page to restore and continue your draft

**Comment by Demy1992** [comment]
I solved it. Was a problem with the auto_increment of the DB.
