### ISSUE TITLE
Sorting tickets sorts pages, not full view

### ISSUE THREAD

**Issue by mnacl** [osTicket/osTicket-1.8#2773]
Version 1.10-rc.2

When you sort the list of tickets, like open tickets, it sorts them in the correct order on each page but not the full list of tickets. In other words, it does the sorting on each page of tickets displayed and not on the list of tickets before they are split into pages. Example:

Top of page 1:
![1](https://cloud.githubusercontent.com/assets/9755180/11576051/4232e5ba-99e2-11e5-8abc-cb0678dbd925.JPG)

Top of page 2:
![2](https://cloud.githubusercontent.com/assets/9755180/11576075/565946ce-99e2-11e5-85be-bc46fbb0b3ae.JPG)

Top of page 3:
![3](https://cloud.githubusercontent.com/assets/9755180/11576078/5b1a357e-99e2-11e5-8770-7e04bcef3332.JPG)

**Comment by ntozier** [comment]
So you mean this? 
https://github.com/osTicket/osTicket-1.8/issues/2499
or
https://github.com/osTicket/osTicket-1.8/issues/2488

Please close duplicate report.

**Comment by mnacl** [comment]
Sorry, my search wasn't thorough enough before posting. Closed as a duplicate.
