### ISSUE TITLE
SQL Database with ISO Countrycode and Countryname in DE, EN, RU, FR, ES, IT

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket-1.8#2775]
Hello all,

after searching Google for a database with translations of countrynames and not found one that is good to use, I made a databse with ISO Code and Country names in DE, EN, RU, FR, ES and IT. If some of you want such a database, its free to use.

Regards

Guido

[countries.txt](https://github.com/osTicket/osTicket-1.8/files/52024/countries.txt)

Rename it to .sql, ist a MySQL dump.

**Comment by greezybacon** [comment]
How does this pertain to osTicket?
