### ISSUE TITLE
v1.9.12 - change ticket source

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2782]
hey people,

i dont can add a new ticket source.
see someone's fault or what am I doing wrong?

the error 
![2015_12_09_08_44_06_osticket_staff_control_panel](https://cloud.githubusercontent.com/assets/13413719/11679473/b0fe1032-9e51-11e5-8c72-bd8650b12b40.png)

and the additional seetings

![a12001d5cdc0b4f63a3f58d3a1331b](https://cloud.githubusercontent.com/assets/13413719/11679502/dbea3fb4-9e51-11e5-9edf-9eed6499ef7f.png)
![e3eae0dcb6fc58b33f5e65b9c1bded](https://cloud.githubusercontent.com/assets/13413719/11679503/dc35cf24-9e51-11e5-825f-359a688dc14a.png)
![b2539429ed46e3009276f8bc81e016](https://cloud.githubusercontent.com/assets/13413719/11679505/dc36de50-9e51-11e5-8a46-fbdae75c96af.png)
![dcf127cf7c53cb9a5776f40b723626](https://cloud.githubusercontent.com/assets/13413719/11679504/dc363b08-9e51-11e5-97ff-2e449a5ceb61.png)

**Comment by SebTM** [comment]
You have a mistake in your change in the "class.ticket.php" (3. Screenshot):

The condiation is "!in_array(strtolower" so you need to write "monitoring" with an small "m". Then it will work, I think ;)

**Comment by oneilak** [comment]
oooooookkk it works ... :-D why?!

thx

**Comment by ntozier** [comment]
My guess is that the system is converting the value to lower case prior to inserting it into the DB to avoid case sensitive issues (and of course since it is... caused one)

**Comment by oneilak** [comment]
crazy but okay ...:-)

**Comment by greezybacon** [comment]
Consider the following logic:

Would the person whose **lower-cased** name is JARED please stand up... 

That's the logic of `!in_array(strtolower($x), array($y, $z, $w))`. Logically the values in `array($y, $z, $w)` would all need to be lower case for there to possibly be a match, right?

**Comment by armancik20** [comment]
I’ve followed tutorial but ticket source, I don’t out
