### ISSUE TITLE
Printing tickets/long answer Issue

### ISSUE THREAD

**Issue by shiko2009** [osTicket/osTicket-1.8#2796]
I am trying to figure out why my tickets are not printing correctly. 
The ticket thread prints out correctly when it's more than 25 or so words, but the "long answer" setting does not print out correctly no matter how I have the settings. It does not "word wrap" like the ticket thread does. Is there a fix for this? am I doing something wrong?
The first picture is the Staff control panel.
The second photo is the print from the control panel...
This Problem is solved for Version 1.8 but still exist on v1.10-rc.2
![105ay3k](https://cloud.githubusercontent.com/assets/16225171/11791343/4f8018c6-a2a9-11e5-92c2-53620310531f.png)

**Comment by shiko2009** [comment]
up
Please i Need to resolve this problem Urgent

**Comment by ntozier** [comment]
I'm not sure how I can assist you since you haven't told us which version of osTicket you are running.
You could always not use the long answer option until its fixed.
As a reminder 1.10rc2 is a release candidate and should not be run in production environments.

**Comment by greezybacon** [comment]
I disagree. The renderer for v1.10 was specifically changed to address this issue. Are you *sure* it's broken on v1.10?

**Comment by shiko2009** [comment]
I am running in Version 1.10rc2 ,,, and yes i am sure it's broken in this version because i am facing big problem in printing tickets

**Comment by greezybacon** [comment]
This is what it looks like in v1.10

<img width="875" alt="screen shot 2015-12-21 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/672074/11936748/7696b8da-a7d5-11e5-84ad-f2fbf57d0d26.png">

**Comment by shiko2009** [comment]
Thanks Guys for your reply
i still have the problem but i found alternative solution
