### ISSUE TITLE
Agent/Department signature is not appended when sending response

### ISSUE THREAD

**Issue by alirezastack** [osTicket/osTicket-1.8#2822]
When I select department signature I can see a grey signature below the rich text editor, but when send the ticket it is sent without the signature.

Is there something I should set in order to send my signature or department's?

**Comment by alirezastack** [comment]
![screen shot 2015-12-26 at 11 02 00 am](https://cloud.githubusercontent.com/assets/6417083/12005551/2353c138-abc0-11e5-8605-a1b62fbd0069.png)

**Comment by greezybacon** [comment]
@alirezastack did you solve this by editing the email templates?

**Comment by alirezastack** [comment]
I apologize, it was due to the modifications I've been made to the code. It works like a charm.

I have implemented ticket history. Signature has been replaced by ticket history. It is now correct. thanks.

**Comment by greezybacon** [comment]
As a heads up, v1.10 will include a feature to add `%{ticket.thread}` to the notification email and it will include the entire ticket history.

Cheers,

**Comment by alirezastack** [comment]
wow that is awesome. we are waiting until then.
