### ISSUE TITLE
Incorrect "Thank you" pages displayed

### ISSUE THREAD

**Issue by GoodbyeWorld** [osTicket/osTicket-1.8#2823]
I think I found a bug. 

I have a use case that requires multiple Help Topics, each with a different "Thank you" page. 

This should be doable by simply creating multiple "Thank you" pages, each with the content they require, and configuring each Help Topic to use the corresponding "Thank you" page. 

The issue is that they are not displayed to the user. Instead, the "Thank you" page configured at the Company level is used, even if that "Thank you" page is disabled. 

This is simple to reproduce, just create a new "Thank you" page, configure a Help Topic to use it, and without signing-in as an agent or user, create a new ticket. You'll be taken to the Company configured Thank you page. 

I reproduced this on both the osTicket Download page version of 1.10 RC2, and a current version I retrieved via `git clone -b develop-next https://github.com/osTicket/osTicket-1.8 .` and then deploying etc..

**Comment by GoodbyeWorld** [comment]
Just wondering if there's anything I can do that would help the development team with this one.  I notice there's been no response - is that because you need more info?  Just let me know what you need to tackle this and I'll do what I can.

**Comment by greezybacon** [comment]
I see the problem is `class.topic.php` line 63.
```php
var $page;
```
should be deleted. That's what's breaking the system

**Comment by GoodbyeWorld** [comment]
@greezybacon - I tested your suggestion and it appears to have worked.  Thanks!

I'm new to github - are you planning to correct that, or would it be helpful for me to submit a pull request with that adjustment?
