### ISSUE TITLE
tickets keep growing after blocking sender email

### ISSUE THREAD

**Issue by dooglus** [osTicket/osTicket-1.8#2839]
I have a couple of tickets which get longer each day. There were both initially spam emails with invalid reply addresses maybe a month ago. I guess OSticket tried replying to them, and isn't handling the bounce replies very gracefully:

![screenshot from 2016-01-03 14 50 51](https://cloud.githubusercontent.com/assets/573356/12081311/4c8e0f16-b22a-11e5-8137-b243bb931700.png)

Note the reply count in the 5 thousands for both tickets.

I've selected 'ban email' for both tickets, but it hasn't helped. Presumably because the bounces aren't coming from the same address as the initial spam came from.

I think I'm using osTicket-v1.9.9-1-gbe2f138.zip, but can't find a way to tell for sure.

I can no longer open those two tickets because they're too big. Is there a way to delete them, or to stop them growing any further?

**Comment by ntozier** [comment]
1.9.12 is current.  Please upgrade to current prior to reporting issues.

To delete you can tick the check box, and select delete.

**Comment by greezybacon** [comment]
We've rewritten the thread display system in v1.10 to handle very very long threads. I haven't tested with 5k threads, but it handles threads with about 900 items and 1600 attachments well. Just to post that we are working on the performance end of things as well.

**Comment by dooglus** [comment]
I upgraded to 1.9.12 and was able to delete the two large tickets. They didn't come back yet either.

I should have just upgraded and not bothered you. I'll close this issue now.
