### ISSUE TITLE
Hide tickets from specific timeline

### ISSUE THREAD

**Issue by SolidK0RE** [osTicket/osTicket-1.8#2846]
Can we have global option to hide tickets from specific date? Like hide ticket from the last year, etc.

**Comment by ntozier** [comment]
Close your tickets and they wont show up in open/my?
Use Advanced Search on created (specify between range) [optional: and save the search]?
There are a number of ways to do this that do not involve changing the code base

**Comment by greezybacon** [comment]
This is possible with #2577. You can change the criteria of all the queues as well as define you own custom ones

**Comment by SolidK0RE** [comment]
Yes! this is it. Many thanks @greezybacon :+1:
