### ISSUE TITLE
agents sending emails to clients

### ISSUE THREAD

**Issue by DanYNWA** [osTicket/osTicket-1.8#2853]
I was wondering if there is a way for agents to send emails responses to clients? Is there a mod or a plugin at all?

**Comment by ntozier** [comment]
I do not understand your question.  You have control over sending emails... Agent responses to users get emailed to the user that owns the ticket (and any collaborators on the ticket).

Did you perhaps not configure email?
Or disable the Autoresponders or Alerts and Notices?

**Comment by telx85** [comment]
I think what he is trying to get at is ...

Can agents reply to a ticket using email??

So if I get an email for a support ticket 123456, I click reply to that email and type my response will it be sent to the clients (and collaborators).

The answer is no. But his question asks is there a mod for this or better yet is there a road map for this to be made possible if desired?

**Comment by ntozier** [comment]
Q: Can agents reply to a ticket using email??
A: Yes...  But not to the client.  Email responses from Agents are logged as Internal Notes.

Q: But his question asks is there a mod for this 
A: Yes.  It's been posted about on the forums.

Q: or better yet is there a road map for this to be made possible if desired?
A: Not that I am aware of.
