### ISSUE TITLE
Feature: Show Status on queues

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2878]

**Comment by ntozier** [comment]
Huh?

**Comment by kest874** [comment]
This will be available in 1.11 see https://github.com/osTicket/osTicket-1.8/pull/2577

**Comment by mfelber** [comment]
I guess he knows that because he is one of the participants in #2577. Maybe he tries to say something different..

**Comment by ntozier** [comment]
presumption.  What was said is that this will be in the next major release after 1.10.  
What the number is can be speculated to be 1.11, but it might not be.

**Comment by kest874** [comment]
Yes true, probably should have said sometime after 1.10, when you do testing on https://github.com/osTicket/osTicket-1.8/pull/2577 the upgrader shows as 1.11
