### ISSUE TITLE
404 Page When "Application" link is clicked

### ISSUE THREAD

**Issue by eljagg** [osTicket/osTicket-1.8#2887]
Hi,
I have installed the Equipment Plugin and when I go to "My Preferences" => "Applications" I get he following error, it appears to be a broken link. Can anyone point me in the right direction on how I can fix the issue.

Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

**Comment by ntozier** [comment]
There is no equipment plugin here.
There is one that was written by a community member poctob.
You would want co close this issue report and open one at his project page. We do not provide support for it here.  You can do so here:
https://github.com/poctob/OSTEquipmentPlugin

**Comment by eljagg** [comment]
Thank you, I understand.
