### ISSUE TITLE
Can 2 ticked be merged to one from the same poster?

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket-1.8#2894]
Sometime customer create new ticket with the same problem, I want to merge them together, but how?

**Comment by mfelber** [comment]
There is no merge function in osTicket yet. 
You have to do it manually: Transfer manually the desired content from ticket a to ticket b and close ticket b.

As you can see on github or in the forum this is discussed many many times.
There are considerations to implement such a function in osTicket but I personally don't think that this will coming soon (cause there are many many other things on the to do list): https://github.com/osTicket/osTicket-1.8/issues/1225

**Comment by gitfve** [comment]
ok
