### ISSUE TITLE
Osticket still submits ticket with empty required fields.

### ISSUE THREAD

**Issue by TascaAutoGroup** [osTicket/osTicket-1.8#2895]
I am having an issue with this. I have also tried digging around this forum for help and what I did find was not helping me at all. I would like to know what needs to be done to get this fixed. It is pretty annoying trying to contact a person when no number is being submitted with the ticket.

**Comment by ntozier** [comment]
Version of osTicket?

phone numbers are associated with users, not tickets.

**Comment by TascaAutoGroup** [comment]
its v1.9.12. That field is in the ticket details form.

**Comment by TascaAutoGroup** [comment]
Wow. No body has a clue as to what might be causing this?

**Comment by ntozier** [comment]
Click on the user.
Their phone number is displayed there.

**Comment by TascaAutoGroup** [comment]
I understand that, but I set up the ticket details up in a fashion so that the user has to put in their contact number. So I tested that and when I click the submit button it does display the error saying that phone number is required but it still submits the ticket.

**Comment by greezybacon** [comment]
If the information is in the "contact information" for and a user is matched based on the email address, then the rest of the information, including required information is ignored, because a profile already exists for the user. The user should click [profile] to change their information. However, for new users (new email addresses), all required fields should be required.

**Comment by TascaAutoGroup** [comment]
That makes sense now. The issue is the previous admin allowed users to just submit a ticket without registering and they never asked for a phone number. I just tested that with an user I know never submitted a ticket and it did not submit the form. Time to make some changes. Thanks for the input.
