### ISSUE TITLE
Ticket:  amount of time spent

### ISSUE THREAD

**Issue by kajla** [osTicket/osTicket-1.8#2897]
Please add an amount of time spent to a ticket.
Example:
Ticket create date: Yesterday
Close date: Today, but the real spent time is 3 hours.

**Comment by ntozier** [comment]
Admin panel -> Manage -> Forms -> Ticket Details.
add you custom field.
make it required before a ticket can be closed.

**Comment by kajla** [comment]
Okey, I added it, but when I choose Ticket status to "Closed", don't ask it. This option only works on "Update Ticket" panel, it's not okey.
I want to show a popup window, when I close a ticket.

**Comment by ntozier** [comment]
Then you did not click "Require entry to close a thread".

![capture](https://cloud.githubusercontent.com/assets/1315768/12753527/817f3010-c995-11e5-9850-f6bb1e883438.PNG)

**Comment by kajla** [comment]
Thank you for your help, but the Field setup and the settings of the Field configuration are missing here.
Admin panel -->  Manage --> Forms --> Choose a built-in forms: New Ticket (missing Ticket Details).

osTicket version: v1.9.12 (19292ad)

**Comment by ntozier** [comment]
Then you will have to wait until 1.10 is released.

**Comment by kajla** [comment]
Oh, thank you very much! :)
Then we are waiting for the stable version of osTicket 1.10. :)
