### ISSUE TITLE
Feature: Change the date of a thread entry

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2898]
This would be a nice feature to date things that were done at the right time and day. Example - I tried a fix for something on Friday but did not put the notes in the system, I go back on Monday and put the notes in the system. Now the notes are saved on Monday. Something came in over the weekend, now my notes are after the weekend entry but happened before.

**Comment by ntozier** [comment]
backdating is the devil.
seriously.
Enter your notes when you are supposed to enter them and you wont have this problem.
/shivers at the thought of backdating

**Comment by greezybacon** [comment]
Sounds like you should add a custom date field to your ticket details for or create a new form with a custom date field. Perhaps label it "Time of Servcice". Then, it can be changed as often as necessary, and the date isn't part of the communication thread.
