### ISSUE TITLE
Multi-part messages not getting detected as such?

### ISSUE THREAD

**Issue by thefinn93** [osTicket/osTicket-1.8#2900]
I installed osTicket (latest off osticket.org, appears to be 1.9.12) and found that HTML/formatted/etc emails don't render properly. Here's an example:

![screenshot from 2016-02-02 10 11 14](https://cloud.githubusercontent.com/assets/692970/12759410/c972da66-c995-11e5-8a29-7752991d165d.png)

From a quick search of this repo it appears they are supposed to be supported and I couldn't find any similar issues, so I can only conclude that I'm doing something wrong (maybe on the mailserver end), but I'm not sure what. Any hints would be appreciate. 

Thanks!

**Comment by ntozier** [comment]
It looks to me like you have disabled html threads.

Admin panel -> Settings -> Tickets -> Enable HTML Ticket Thread

**Comment by thefinn93** [comment]
It looks like that was already enabled :(

Thanks for the quick reply though!

**Comment by greezybacon** [comment]
What server software are you using? Exchange? Can you post the entire raw email (with the headers and everything)?

**Comment by thefinn93** [comment]
Mail software is postfix and courier. I don't see an option to get the raw headers out of osTicket and it deleted it from IMAP, so I sent a new email and got the headers with a different IMAP client before the osTicket email cron job ran. [here they are](https://gist.github.com/thefinn93/25e79673591281f6f1f6). I really appreciate your help on this

**Comment by thefinn93** [comment]
Update: Turns out postfix was inexplicably configured to strip out the `MIME-Version` header, which was causing this. I have absolutely no idea why that was thought to be a good or reasonable thing to do, nor how it got there, but removing that header check line made this go away. Interesting that Thunderbird ignores that.

Thanks for working with me on this
