### ISSUE TITLE
1.10 ORM adding a database column to organization orm issue (field not defined) need assitance

### ISSUE THREAD

**Issue by kest874** [osTicket/osTicket-1.8#2904]
I've added 'department' as a column to the organization table to store the ID of a selected department, the settings:

![image](https://cloud.githubusercontent.com/assets/12860950/12785135/9995eff2-ca50-11e5-88dc-074f9ecacf98.png)

Dropdown pulls from the department table, the id of the selected department gets saved to the 'department' column that I added:

![image](https://cloud.githubusercontent.com/assets/12860950/12785205/fc676d68-ca50-11e5-879b-86e0563316d5.png)

I can retrieve the selected department when I go back into the settings.

The issue arrives when I want to select the department ID stored int he column in class.ticket.php, following this piece of code:
![image](https://cloud.githubusercontent.com/assets/12860950/12785302/776dd916-ca51-11e5-8a04-37b34e197354.png)

I am testing:
![image](https://cloud.githubusercontent.com/assets/12860950/12785310/8ec1fbba-ca51-11e5-8b32-f1d73b9e5b82.png)

function in class.organization.php is:

![image](https://cloud.githubusercontent.com/assets/12860950/12785344/c049375c-ca51-11e5-8bf6-35a372a650ea.png)

When I open a new ticket it throws an orm exception:

Fatal error: Uncaught exception 'OrmException' with message 'Organization: department: Field not defined' in /var/www/osttest/include/class.orm.php:337 

Looking at the object:

![image](https://cloud.githubusercontent.com/assets/12860950/12785422/1867117a-ca52-11e5-97b5-8a290ed907e1.png)

the added department colum is missing.

The million dollar question, what did I miss?  @greezybacon @protich  can one of you give me a clue as to where to look?

**Comment by greezybacon** [comment]
The system keeps a cache of the database fields lazily so it doesn't have to keep asking the database. You probably just need to restart PHP / Apache

**Comment by greezybacon** [comment]
FYI- We do have custom data for organizations including list selections. It might be easier to just use the software to track the organization department. Then write a plugin to intercept the `ticket.created` signal and do something with the affiliated `user->organization`. Then use `$organization->getDynamicData()->getAnswer('department')` to fetch your department selection in php.

**Comment by kest874** [comment]
@greezybacon Restarting PHP resolved the issue, I forgot that the fields were cached.

I'm using 1.10 (with custom queues) for our IT support system with some modifications to get it fully working. I've modified the same base for a "Suggestion" tracking system, the idea here is to ease the setup so that ticket filters aren't required to set the department and team.  I'm using the organization to hold the team members, the department to hold the team "agents" and the "team" for assignment for the team facilitator and team leader.
