### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket-1.8#2906]
No new updates, since 08-15? Is it dead? If so it is nice to know, so I can find some other software to support our customers. It was a nice free support system, but there are too many malfunction at the moment, and now we/i have waited since 08-15... Sorry to say.

**Comment by AlexYoung28** [comment]
give them a chance!!

**Comment by quazardous** [comment]
@gitfve 
I'm new to osTicket but check the commits before:
https://github.com/osTicket/osTicket-1.8/commits/develop

And I've got my issue tagged some hours ago... so it's not dead... maybe you can contribute to speed things up ?

**Comment by gitfve** [comment]
I agree @AlexYoung28 but there are so many editor bug in the staff panel that I cant understand why they not make a hot fix. And there have not been any new release since 08-15, long time ago... From start of 2015 to 08-15 there was many new release and hotfix, and one since. But I close it and hope they still working on next release, because it is nice ticket system, and free.

**Comment by quazardous** [comment]
osTicket recoded in symfony or with drupal 8 ;p

@gitfve you're right it's a nice software but parts are so old OMG ;p
