### ISSUE TITLE
1.10: Relative Time settings

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket-1.8#2921]
Where is the Relative Time setting for system? There is a Relative Time setting for agents.

**Comment by ntozier** [comment]
No description provided.

**Comment by jdelhome3578** [comment]
The system setting should include the relative time setting and the profile should include in the options to use system default, Relative, Straight time.

**Comment by infectormp** [comment]
+1

**Comment by protich** [comment]
Enhancement addressed in PR #2700. It's already merged to develop-next.

**Comment by jdelhome3578** [comment]
@protich I just downloaded the latest and I don't see the option

**Comment by jdelhome3578** [comment]
@ntozier @protich @greezybacon
The system setting should include the relative time setting and the profile should include in the options to use system default, Relative, Straight time.

**Comment by jdelhome3578** [comment]
@protich please re-open

**Comment by Hannibal226** [comment]
@jdelhome3578 
If I read this correct what @protich wrote "It's already merged to [code]develop-next[/code]." it doesn't help to download latest version.
AFAIK the [code]develop-next[/code] hast first to be merged to [code]develop[/code].

No guarenteee on this, but  maybe anyone can confirm.

CHEERS

**Comment by jdelhome3578** [comment]
OK everyone I have downloaded the latest from the develop-next branch and have tested it. I don't see the option in the global settings for relative time. The option is only viable in the profile settings for the agent. In those setting it has an option for using system defaults. How can you use system defaults when there is no option for it in the system settings?

**Comment by greezybacon** [comment]
@jdelhome3578 I don't like the configuration, but I think it means "use the normal time format settings for the system", or "use (humanized) relative time"

**Comment by jdelhome3578** [comment]
@greezybacon I would recommend a global setting and then a profile setting to use system default, relative time or  regular time options.
