### ISSUE TITLE
Disable new tickets from web interface

### ISSUE THREAD

**Issue by BassemN** [osTicket/osTicket-1.8#2925]
Hello,
Great script!!
Can I disable new tickets from web interface(open.php) and allow it only via API?

Thanks

**Comment by greezybacon** [comment]
Yes, set the user registration to required (in Settings -> Users), and set the registration mode to DISABLED. This idea is explained in the help tip for both settings.

**Comment by BassemN** [comment]
@greezybacon  Thank you very much
