### ISSUE TITLE
Is difficolt paste code into ticket because something is truncated.

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#2945]
Hi,
some times OsTicket is used from hosting company ...
The issue is... when as customer i post a code inside OsTicket not past this code as Text but delete some row.

The same issue is present in the operator side.
If I copy the email address of the person who opened the ticket this is showed by OsTicket as < email@email.ext > but all text inside <> will be truncated.

This is not good. I can understand is a security feature but this make create ticket very hard some time as you are not able to insert code. The code should be not interpreted but pasted as text.

If you try other ticket system as Hesk... here you don't have the issue, you can paste code and code is reported as text.

Hope my English can let you understand what I mean.

Softaculous for example is using OsTicket.
If I have to paste some embed code in the ticket or php code the text are not pasted as text only but is deleted... only some row is showed.. and Softaculous has not enalbed attachment so you can only paste the code in the ticket who not paste what you paste because text are trucked, some times.

**Comment by JediKev** [comment]
I really can't understand your question.  I've tried copy/pasting code and just strictly writing code in a ticket response, I sent it and everything is fine from both agent and user.  Screenshots, version number, and a clearer question would help out a lot!

**Comment by ntozier** [comment]
@PeopleInside 
For starters what version of osTicket?

You do realize that "<email@faux.net>" isn't valid "code" by any coding language I'm familiar with.
Where are you seeing emails in this format?  ie where are you copy and pasting it from?
Because that looks like an email address format ie: firstname lastname <email@faux.net>

**Comment by PeopleInside** [comment]
Unable to replicate for now.
Sorry.
