### ISSUE TITLE
Valid CSRF Token Required when login in admin panel

### ISSUE THREAD

**Issue by Eric111** [osTicket/osTicket-1.8#304]
I just installed v1.80 over v1.73 and get this error when i login to the admin panel:
Valid CSRF Token Required
Upgrading went smoothely.

So i cannot login anymore... :-(

**Comment by xtremevision** [comment]
Hi,

Same problem for us. Just installed latest from repo using git, and we're getting "Valid CSRF Token Required". Can't login to admin.

Our config:
- varnish port 80
- nginx port 8080
- php-fpm socket
- CentOS 7 x64, MariaDB 5.5.41, php 5.4.16

Any ideas?

Thanks,
Michael.

**Comment by greezybacon** [comment]
Are you sure your proxy server is brokering the `Cookie` and `Set-Cookie` headers?

**Comment by xtremevision** [comment]
Hi @greezybacon,

Pardon my possible ignorance, but what do you mean by "brokering"? Perhaps uploading my varnish and nginx config files would help?

Cheers,
Michael.

[root@xtreme-vision varnish]# cat default.vcl
#
# This is an example VCL file for Varnish.
#
# It does not do anything by default, delegating control to the
# builtin VCL. The builtin VCL is called when there is no explicit
# return statement.
#
# See the VCL chapters in the Users Guide at https://www.varnish-cache.org/docs/
# and http://varnish-cache.org/trac/wiki/VCLExamples for more examples.

# Update of varnish 4 to work with wordpress
# Marker to tell the VCL compiler that this VCL has been adapted to the
# new 4.0 format.
vcl 4.0;

# Default backend definition. Set this to point to your content server.
backend default {
    .host = "127.0.0.1";
    .port = "8080";
    .connect_timeout = 600s;
    .first_byte_timeout = 600s;
    .between_bytes_timeout = 600s;
    .max_connections = 800;
}

# Only allow purging from specific IPs
acl purge {
    "localhost";
    "127.0.0.1";
}

# This function is used when a request is send by a HTTP client (Browser)
sub vcl_recv {
        # Normalize the header, remove the port (in case you're testing this on various TCP ports)
        set req.http.Host = regsub(req.http.Host, ":[0-9]+", "");

        # Remove has_js and CloudFlare/Google Analytics __* cookies.
        set req.http.Cookie = regsuball(req.http.Cookie, "(^|;\s*)(_[_a-z]+|has_js)=[^;]*", "");
        # Remove a ";" prefix, if present.
        set req.http.Cookie = regsub(req.http.Cookie, "^;\s*", "");

        # Allow purging from ACL
        if (req.method == "PURGE") {
                # If not allowed then a error 405 is returned
                if (!client.ip ~ purge) {
                        return(synth(405, "This IP is not allowed to send PURGE requests."));
                }
                # If allowed, do a cache_lookup -> vlc_hit() or vlc_miss()
                return (purge);
        }

        # Post requests will not be cached
        if (req.http.Authorization || req.method == "POST") {
                return (pass);
        }

        # --- WordPress specific configuration

        # Did not cache the admin and login pages
        if (req.url ~ "wp-(login|admin)" || req.url ~ "preview=true") {
        return (pass);
        }

        # Remove the "has_js" cookie
        set req.http.Cookie = regsuball(req.http.Cookie, "has_js=[^;]+(; )?", "");

        # Remove any Google Analytics based cookies
        set req.http.Cookie = regsuball(req.http.Cookie, "__utm.=[^;]+(; )?", "");

        # Remove the Quant Capital cookies (added by some plugin, all __qca)
        set req.http.Cookie = regsuball(req.http.Cookie, "__qc.=[^;]+(; )?", "");

        # Remove the wp-settings-1 cookie
        set req.http.Cookie = regsuball(req.http.Cookie, "wp-settings-1=[^;]+(; )?", "");

        # Remove the wp-settings-time-1 cookie
        set req.http.Cookie = regsuball(req.http.Cookie, "wp-settings-time-1=[^;]+(; )?", "");

        # Remove the wp test cookie
        set req.http.Cookie = regsuball(req.http.Cookie, "wordpress_test_cookie=[^;]+(; )?", "");

        # Are there cookies left with only spaces or that are empty?
        if (req.http.cookie ~ "^ *$") {
                    unset req.http.cookie;
        }

        # Cache the following files extensions
        if (req.url ~ "\.(css|js|png|gif|jp(e)?g|swf|ico)") {
                unset req.http.cookie;
        }

        # Normalize Accept-Encoding header and compression
        # https://www.varnish-cache.org/docs/3.0/tutorial/vary.html
        if (req.http.Accept-Encoding) {
                # Do no compress compressed files...
                if (req.url ~ "\.(jpg|png|gif|gz|tgz|bz2|tbz|mp3|ogg)$") {
                                unset req.http.Accept-Encoding;
                } elsif (req.http.Accept-Encoding ~ "gzip") {
                        set req.http.Accept-Encoding = "gzip";
                } elsif (req.http.Accept-Encoding ~ "deflate") {
                        set req.http.Accept-Encoding = "deflate";
                } else {
                        unset req.http.Accept-Encoding;
                }
        }

        # Check the cookies for wordpress-specific items
        if (req.http.Cookie ~ "wordpress_" || req.http.Cookie ~ "comment_") {
                return (pass);
        }
        if (!req.http.cookie) {
                unset req.http.cookie;
        }

        # --- End of WordPress specific configuration

        # Did not cache HTTP authentication and HTTP Cookie
        if (req.http.Authorization || req.http.Cookie) {
                # Not cacheable by default
                return (pass);
        }

        # Cache all others requests
        return (hash);
}

sub vcl_pipe {
        return (pipe);
}

sub vcl_pass {
        return (fetch);
}

# The data on which the hashing will take place
sub vcl_hash {
        hash_data(req.url);
        if (req.http.host) {
        hash_data(req.http.host);
        } else {
        hash_data(server.ip);
        }

        # If the client supports compression, keep that in a different cache
        if (req.http.Accept-Encoding) {
                hash_data(req.http.Accept-Encoding);
        }

        return (lookup);
}

# This function is used when a request is sent by our backend (Nginx server)
sub vcl_backend_response {
        # Remove some headers we never want to see
        unset beresp.http.Server;
        unset beresp.http.X-Powered-By;

        # For static content strip all backend cookies
        if (bereq.url ~ "\.(css|js|png|gif|jp(e?)g)|swf|ico") {
                unset beresp.http.cookie;
        }
        # For css/js enable gzip
        if (bereq.url ~ "\.(css|js|png|gif|jp(e?)g)|swf|ico") {
                 set beresp.do_gzip = true;
        }
        if (bereq.url ~ "custom_style\.php") {
                 set beresp.do_gzip = true;
        }
        if (bereq.url ~ "\.(css|js)") {
                set beresp.http.Vary = "Accept-Encoding";
        }

        # Don't store backend
        if (bereq.url ~ "wp-(login|admin)" || bereq.url ~ "preview=true") {
                set beresp.uncacheable = true;
                set beresp.ttl = 30s;
                return (deliver);
        }

        # Only allow cookies to be set if we're in admin area
                if (!(bereq.url ~ "(wp-login|wp-admin|preview=true)")) {
                unset beresp.http.set-cookie;
        }

        # don't cache response to posted requests or those with basic auth
        if ( bereq.method == "POST" || bereq.http.Authorization ) {
                set beresp.uncacheable = true;
                set beresp.ttl = 120s;
                return (deliver);
        }

        # don't cache search results
        if ( bereq.url ~ "\?s=" ){
                set beresp.uncacheable = true;
                set beresp.ttl = 120s;
                return (deliver);
        }

        # only cache status ok
        if ( beresp.status != 200 ) {
                set beresp.uncacheable = true;
                set beresp.ttl = 120s;
                return (deliver);
        }

        # A TTL of 2h
        set beresp.ttl = 2h;
        # Define the default grace period to serve cached content
        set beresp.grace = 30s;

        return (deliver);
}

# The routine when we deliver the HTTP request to the user
# Last chance to modify headers that are sent to the client
sub vcl_deliver {
        if (obj.hits > 0) {
                set resp.http.X-Cache = "cached";
        } else {
                set resp.http.x-Cache = "uncached";
        }

        # Remove some headers: PHP version
        unset resp.http.X-Powered-By;

        # Remove some headers: Apache version & OS
        unset resp.http.Server;

        # Remove some heanders: Varnish
        #unset resp.http.Via;
        #unset resp.http.X-Varnish;

        return (deliver);
}

sub vcl_init {
        return (ok);
}

sub vcl_fini {
        return (ok);
}

**Comment by xtremevision** [comment]
Actually I don't nginx conf is worth pasting, since it has nothing to do with cookies...

**Comment by xtremevision** [comment]
Hi,

I fixed it, this section was responsible:

```
        # Only allow cookies to be set if we're in admin area
        if (!(bereq.url ~ "(wp-login|wp-admin|preview=true)")) {
                unset beresp.http.set-cookie;
        }
```

changed to:

```
        # Only allow cookies to be set if we're in admin area
        if (!(bereq.url ~ "(wp-login|wp-admin|preview=true|scp/login.php)")) {
                unset beresp.http.set-cookie;
        }
```

Cheers,
Michael.

**Comment by greezybacon** [comment]
@xtremevision looks like you resolved the issue. Please reopen it if the issue resurfaces.

**Comment by MassimoDIFA** [comment]
Hi, I have same issue, behind proxy sometime I can login but I'm quite always unable. No one of suggested fix helped me.

**Comment by TomAshley303** [comment]
I'm currently experiencing this issue. I also know PHP. Help me help.

**Comment by Richardvi** [comment]
Affirmative. Same problem here.

On PHP7 this fails. On PHP5 this works.

I had to go back to an old backup.

**Comment by ntozier** [comment]
@TomAshley303 and @Richardvi can you two both provide actual PHP versions for 5 and 7 that you used?

**Comment by Richardvi** [comment]
Working for me: 5.6.31
Not working for me: 7.1.7

**Comment by Richardvi** [comment]
Serverinformatie
--
osTicket versie | v1.10 (901e5ea) —  Bij de tijd
Web Server Software | Apache
MySQLversie | 10.0.29
PHPversie | 5.6.31

gdlib | Ten behoeve van afbeeldingsbewerking en PDFprinten
imap | Ten behoeve van emailontvangst
xml | XML API
xml-dom | Ten behoeve van emailverwerking
json | Bevordert de prestaties bij het creeren en verwerken van JSON
mbstring | Hoogst aanbevolen bij niet westeuropese taalinhoud
phar | Hoogst aanbevolen voor plugins en taalpakketten
intl | Hoogst aanbevolen bij niet westeuropese taalinhoud
fileinfo | wordt gebruikt om bestandstypen van uploads te detecteren
APCu | Verbetert de algehele prestaties
Zend Opcache | Verbetert de algehele prestaties

cgi.fix_pathinfo | "1" is aanbevolen als AJAX niet werkt
date.timezone | Europe/Amsterdam

Schema | deb5715_osti1 (localhost)
Schema signatuur | 98ad7d550c26ac44340350912296e673
ruimte in gebruik | 2.48 MiB
Ruimte voor bijlages | 0.06 MiB
Tijdszone | CEST (Geïnterpreteerd als Europe/Berlin)

**Comment by ntozier** [comment]
osTicket supports php7 not pgp7.1 which is likely your issue.

**Comment by Richardvi** [comment]
Sorry, you are right. I went back to 7.0. See what happens.

**Comment by ntozier** [comment]
Please let us know :)

**Comment by mdpeters67** [comment]
Has anyone solved the PHP 7 compatibility problem?

**Comment by ntozier** [comment]
@mdpeters67 what PHP7 compatibility issue are you talking about? 
I only know of PHP7.1 compatibility issues at this time.

**Comment by mdpeters67** [comment]
OK ... so more specifically PHP7.1.

**Comment by mdpeters67** [comment]
Has anyone solved the PHP 7.1 compatibility problem?

**Comment by mfelber** [comment]
@mdpeters67 Maybe this helps you: https://github.com/osTicket/osTicket/pull/3773

**Comment by mdpeters67** [comment]
That worked! I followed the one line fix here: https://github.com/osTicket/osTicket/commit/424bfc99d93b920f6162b602eeea41125086425d
Thank you for helping!

**Comment by chasedivine** [comment]
This topic has moved around a lot, but I just installed osTicket version 1.10.1 from the GoDaddy site "running on Linux".  I am getting the same issue with "Valid CSRF Token Required" I have updated the file and tried all the things here without luck.  I am running PHP 7.0, tried it on PHP 7.1 same issue, All default install setting were picked from GoDaddy to install on the root folder.  Https, http, chrome, IE, android, all tried same error.  
I installed the software directly from the site, tested it on 1and1 VPS with all default setting in place running on Windows IIS.  Same error...Please help?

**Comment by tobilobaajibola** [comment]
The latest version is compatible with Php 7.0, so you can downgrade from 7.1 to 7.0.
