### ISSUE TITLE
insert image: upload into Landing Page

### ISSUE THREAD

**Issue by balojs** [osTicket/osTicket-1.8#334]
I have a problem when inserting an image is not displayed
![screenshot](https://f.cloud.github.com/assets/3303352/1778459/eb7c7a5a-6834-11e3-9a8b-79d8bf5f1ba4.png)

![screenshot](https://f.cloud.github.com/assets/3303352/1778447/bdf38894-6834-11e3-9693-4e601fffd916.png)

**Comment by greezybacon** [comment]
Is this still an issue? We have had and have resolved several issues saving and associating images with the inline HTML editor.

**Comment by knockiiing** [comment]
Hi Jared,

I haven't since take a look.

I will install the new version and check.

Thanks

Patrick

**Comment by ebell451** [comment]
@greezybacon Using 1.9.6, I'm not having an issue with adding images to knowledgebase articles or to pages (specifically the landing page). I added images by dragging and dropping and linking to images from other sites.

@steadhouse some of your images work...about half of the articles...but some do not. It would be interesting to see how/when they were initially created and when/what version. Most if not all say updated August 1, 2014.

* Working images: *https://helpdesk.nwcu.edu/file.php?key=3vmmsam8m_mzrajpw3ukoflckw_ad5ny&expires=1427328000&signature=10f135ef1c8cd1028700cfb2ec59c69238239b14&disposition=inline* from **[Add Money to Your NCU Print Account](https://helpdesk.nwcu.edu/kb/faq.php?id=25)**

* Non-working images: *cid:nwhmslagfyum3fdusyugrior3qrfua7o* from **[How to Set Your NCU E-mail Signature](https://helpdesk.nwcu.edu/kb/faq.php?id=32)**

**Comment by steadhouse** [comment]
I believe all of our newer KB articles with images have been OK, so I would guess this is just an issue with the older version. I think we may have been on 1.9.1 back then... or somewhere around there.

Thanks!

**Comment by greezybacon** [comment]
Can anyone try the patch in #1960 to see if it addresses the issue?
