### ISSUE TITLE
Popup when sending form in Chrome

### ISSUE THREAD

**Issue by goll420** [osTicket/osTicket-1.8#484]
Reported this on the osTicket forums and was asked to drop an issue in here by Jared. This is from the body of the forum post I made.

One thing I have noticed, and is not a problem but just a niggle more than anything. When I update a ticket or anything via a form, with the WYSIWYG editor it always gives me a popup asking if I want to leave the page when I click the submit button.

![osticketpopup](https://f.cloud.github.com/assets/6523595/2018219/2038d9ba-880a-11e3-9a3c-fe87f8faa33a.jpg)

**Comment by greezybacon** [comment]
Can anyone see if the patch in #1898 addresses the issue?
