### ISSUE TITLE
Adding new faq, category is marked as internal even though its public

### ISSUE THREAD

**Issue by itguy1024** [osTicket/osTicket-1.8#534]
Related topic https://github.com/osTicket/osTicket-1.8/issues/74

I created a Category and made it public. Added 5 articles to it and each time I add a new one it still says internal.
From the client side the category shows up but none of the articles.

**Comment by Deepcuts** [comment]
Same problem here.
Standard install without the bootstrap theme.

**Comment by greezybacon** [comment]
@Deepcuts can you post some screenshots?

**Comment by Deepcuts** [comment]
![image](https://cloud.githubusercontent.com/assets/4704834/6697850/26565916-ccfc-11e4-935d-801a6b42d0ee.png)
![image](https://cloud.githubusercontent.com/assets/4704834/6697853/2e2a3c7a-ccfc-11e4-9277-292713f8a399.png)

**Comment by greezybacon** [comment]
I think I finally found it. Can anyone try the patch in #1867?

**Comment by Deepcuts** [comment]
Thank you very much @greezybacon for your time and efforts.
The patch fixes the issue for me.

**Comment by mlahloudsi** [comment]
Dear greezybaco,
Unfortunately, I've tried the patch ID #1867, but, nothing has changed in the user page
![faq_4](https://cloud.githubusercontent.com/assets/11594647/11324861/3546d064-9136-11e5-95e4-60846c499d00.JPG)
.
The FAQ is usually invisible for the users (please see Attachment)
![faq_1](https://cloud.githubusercontent.com/assets/11594647/11324842/9a57b186-9135-11e5-82a9-397e3c88b483.JPG)
![faq_2](https://cloud.githubusercontent.com/assets/11594647/11324844/9ab2cde6-9135-11e5-99b2-f30cb25edec8.JPG)
![faq_3](https://cloud.githubusercontent.com/assets/11594647/11324843/9a633f6a-9135-11e5-945b-4df403c7dfe1.png)
![faq_4](https://cloud.githubusercontent.com/assets/11594647/11324865/48b4da4c-9136-11e5-93e3-3a565c4bd1a7.JPG)
