### ISSUE TITLE
Ticket Filters - "Stop Processing On Match" doesn't work

### ISSUE THREAD

**Issue by mattpharr** [osTicket/osTicket-1.8#672]
I'm using the 1.8 develop-next branch of osTicket

I have one filter whose Execution Order is set to "1" and the "Stop Processing On Match" checkbox is checked.

I have another filter whose Execution Order is set to "98".

To me, this seems like it would apply filter #1 and then stop running through the rest of the filters, correct? However, it actually appears to skip filter #1 completely and just apply filter #98.

After doing some more investigation, it appears as though the filters are being applied in reverse order. If I edit line 762 in include/class.filter.php and change it to "$sql.=' ORDER BY execorder DESC';", the filters seem to work as expected so far.

I'm not sure if that's the correct place to edit & I'm new to git/github and osTicket, so I figured I should let someone else investigate this.

**Comment by greezybacon** [comment]
Closing the issue as it should be fixed in the latest versions. Please reopen if the problem persists
