### ISSUE TITLE
advanced search range date probleme

### ISSUE THREAD

**Issue by saroy** [osTicket/osTicket-1.8#690]
hi
in advanced search range date hit result in format mm/dd/yy even if i change date format in setting to dd/mm/yy

if i choose range date from 01/02/2014 to 01/03/2014(dd/mm/yy) one month it give result for 2 days (mm/dd/yy) from 02/01/2014 to 03/01/2014

thamks

**Comment by greezybacon** [comment]
@saroy can you see if the patch in #1848 addresses the issue?
