### ISSUE TITLE
Log IP address for each thread reply.

### ISSUE THREAD

**Issue by dbinoj** [osTicket/osTicket-1.8#724]
I would like to log ipaddress from which the reply was made for each thread reply. I see that the ip_address field is empty for replies in ost_ticket_thread. How do I populate these fields?

**Comment by henesnarfel** [comment]
I would like to see this as well.  It appears that the only ip that is being tracked is the clients.  We need to track the Staff as well.  We are using some generic helpdesk accounts and would like to know the exact computer some of these actions are coming from as some are doing things they shouldn't be.

I've made this change in the file include/class.ticket.php.  If you look at the function postMessage it sets the ip address.  Just copy that functionality and paste it in the postReply and postNote functions

**Comment by greezybacon** [comment]
I agree. We have the column for it in the database. The system should always record the remote IP if possible

**Comment by ntozier** [comment]
Seconded.

**Comment by greezybacon** [comment]
Can anyone try the patch in pull request #1846?

**Comment by infectormp** [comment]
Confirm, ip for post and notice loged to database after this patch.

**Comment by dbinoj** [comment]
working. confirmed.

On Tue, Mar 17, 2015 at 5:13 PM, infectormp <notifications@github.com>
wrote:

> Confirm, ip for post and notice loged to database after this patch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osTicket/osTicket-1.8/issues/724#issuecomment-82297872>
> .
>



-- 
Binoj D | http://www.dbinoj.com
