### ISSUE TITLE
Adding new faq, category is marked as internal even though its public

### ISSUE THREAD

**Issue by sikksakk** [osTicket/osTicket-1.8#74]
When adding a new FAQ entry, the category is shown as internal though it actually is public.

![newfaq_category](https://f.cloud.github.com/assets/2955755/1452675/b3d0eab6-42da-11e3-8993-337ba91925b1.PNG)
![newfaq_internal](https://f.cloud.github.com/assets/2955755/1452676/b61d72bc-42da-11e3-9303-8ac308e5a5c8.PNG)

**Comment by greezybacon** [comment]
@sikksakk after a terrific delay, could you try the patch in #1867?

**Comment by infectormp** [comment]
patch work fine
