### ISSUE TITLE
Ticket Filters Continue processing after match

### ISSUE THREAD

**Issue by pfurches** [osTicket/osTicket-1.8#802]
I setup multiple ticket filters and told them to stop processing after a match.  All my tickets continue processing filters until all filters are checked.

For example: I have tickets that are high or emergency priority assigned to our supervisor team.  I put it the process order as #1 and told it to stop processing on match.  Later in my filters another rule processed the same ticket and reassigned to another team based on schools assignment.

How are filters processed?  Low to High or High to Low?  Should the #1 rule checking priority stop processing the ticket once it matches the filter rule?

When I changed the execution order around everything seemed to work the way I expected.  I made the high priority rule #99 and the school filters #98 and the ticket assigned as expected.  Checking and unchecking stop on match did not seem to help.

TIA for all of your help.

**Comment by greezybacon** [comment]
I'm closing this issue as it was addressed. Please reopen it if the problem persists
