### ISSUE TITLE
Advanced Searching "DATE issue"

### ISSUE THREAD

**Issue by cervedgroup** [osTicket/osTicket-1.8#901]
![searchdate](https://cloud.githubusercontent.com/assets/6535381/2982101/2c36fb98-dc10-11e3-9005-bf18bff5685d.JPG)

--- result (include tickets not closed on selected date) ---
![searchresult](https://cloud.githubusercontent.com/assets/6535381/2982142/d9b79228-dc10-11e3-9eb5-a28142ff156e.JPG)

**Comment by greezybacon** [comment]
Can anyone try the patch in #1848 to see if it addresses the issue?

**Comment by cervedgroup** [comment]
tryed on 1.9.6, maybe something was wrong, because when i click on "advanced " nothing happens

**Comment by cervedgroup** [comment]
sorry, my mistake, didn't made a full refresh ... now it's WORKS!!
Thank you Jared!
