### ISSUE TITLE
Navigation warning after draft saved

### ISSUE THREAD

**Issue by RandomInsano** [osTicket/osTicket-1.8#984]
If navigating away from a page with changes, there is a dialog that is presented so you don't accidentally lose your work. This is absolutely awesome since I'm bad for doing that.

It also seems that if you click one of the submission buttons, this dialog isn't shown, which is great.

The problem happens once a draft is saved. The submit button for a ticket response becomes reset, and so you are presented with a 'do you want to leave this page' when it's pretty obvious you want to send off your work. It only happens on the "Post Reply" tab, the other options work perfectly fine.

I'm assuming some variable is just accidentally getting reset when the draft becomes saved.

Sorry I don't have much time to dig deep into this. If there are any questions about it, I'd be glad to run tests and the like.

**Comment by greezybacon** [comment]
Could anyone try the patch in #1898 to see if it addresses the issue?
